using Luxel.Gallery;
using Luxel.Gallery.UI;

namespace Luxel.UI.Gallery;

internal static partial class UiControlDocs
{
    private static readonly ControlDocsPage[] RenderingPages =
    [
        Page(
            "Canvas2D",
            "Rendering",
            "Canvas2D",
            "即時描画コールバックで軽量な二次元図形や独自可視化を描く領域です。",
            ["軽量な二次元図形や独自の読み取り専用可視化を即時描画する場合。"],
            ["標準 Widget の子構造、フォーカス、支援技術向け意味が必要な場合。"],
            "Canvas2D(320, 180, canvas => Draw(canvas))",
            "描画に使うモデルは呼び出し側が所有し、再描画の契機も外部状態から与えます。",
            "幅、高さ、描画コールバックが主要入力です。",
            "標準の子 Widget、フォーカス、アクセシビリティ意味は提供しません。必要な操作は別コントロールで用意してください。",
            "実寸を明示し、周囲の Border や Box で背景と余白を構成します。",
            "高水準のレイアウト、テキスト入力、支援技術向け代替表現は自動生成されません。描画資源の寿命はホストに従います。",
            "Canvas2D",
            alternatives: [new("GpuView", "GPU レンダラーの出力を埋め込みます。")]
        ),
        Page(
            "DiagramBlock",
            "Rendering",
            "DiagramBlock",
            "文書中の図表記述を表示するブロックです。説明資料や構造図の埋め込みに使います。",
            ["説明文書の中へ図表記述を読み取り専用で埋め込む場合。"],
            ["ノードや接続を直接編集するグラフ UI が必要な場合。"],
            "DiagramBlock(source)",
            "図表ソースは呼び出し側が所有し、表示側は解析・描画結果を保持します。",
            "図表ソースと表示幅などを指定します。",
            "基本は閲覧用途です。図形ごとのキーボード移動や読み上げ情報は提供されないため、同内容のテキストを併記してください。",
            "文書幅に合わせ、周囲の背景と余白をテーマで整えます。",
            "不正な記述や未対応構文は表示できません。編集器ではなく、再構築時に解析結果も更新されます。",
            "DiagramBlock",
            alternatives: [new("NodeGraphView", "ノードと接続を対話編集します。")],
            componentType: "global::Luxel.Diagram.DiagramBlock"
        ),
        Page(
            "GpuView",
            "Rendering",
            "GpuView",
            "GPU 描画結果を UI ツリー内へ表示するための専用領域です。",
            ["GPU レンダラーの出力を専用領域として UI ツリーへ埋め込む場合。"],
            ["通常の二次元 Widget 構成や、支援技術で直接操作する内容を表示する場合。"],
            "GpuView(width, height, renderer)",
            "描画モデルと GPU 資源はレンダラー側が所有し、Widget は表示領域とホスト接続を担います。",
            "寸法、描画処理、必要なホスト資源を指定します。",
            "標準 UI の意味や支援技術向け代替はありません。操作を付ける場合は入力座標とフォーカス管理を明示します。",
            "明示サイズを基本とし、周囲の Border で背景と余白を構成します。",
            "GPU 利用可能なホストが必要です。資源作成・破棄とデバイス喪失への対応はレンダラー側の責任です。",
            "GpuView",
            alternatives: [new("Canvas2D", "軽量な二次元図形を CPU 側コールバックで描きます。")]
        ),
        Page(
            "Icon",
            "Rendering",
            "Icon",
            "小さな記号を表示し、操作や状態の識別を補助します。",
            ["小さな記号で操作や状態の識別を補助する場合。"],
            ["記号だけで操作の意味を伝える場合や、長い説明を表示する場合。"],
            "Icon(iconName, size: 16)",
            "状態は持たず、指定した記号と色を表示します。",
            "アイコン識別子、size、color が主要入力です。",
            "Icon 単体は操作対象ではありません。意味のあるラベルを併記し、色や形だけへ依存しないでください。",
            "文字サイズや周辺コントロールと釣り合う寸法・テーマ色を使います。",
            "未登録記号は表示できません。支援技術向け名称を自動提供しません。",
            "Icon",
            alternatives: [new("Text", "文字ラベルで意味を直接伝えます。")]
        ),
        Page(
            "ImageBlock",
            "Rendering",
            "ImageBlock",
            "ResourceSystem から画像を読み込み、文書やコンテンツ内へ表示するブロックです。",
            ["ResourceSystem の画像を文書やコンテンツブロックとして表示する場合。"],
            ["CPU 側ピクセル列を頻繁に更新する低水準プレビューが必要な場合。"],
            "ImageBlock(new ImagePayload(path, alt), resources, 360)",
            "画像ハンドルとキャッシュは ResourceSystem、パスと代替文は呼び出し側が所有します。",
            "ImagePayload、ResourceSystem、表示幅が主要入力です。",
            "閲覧用途です。代替文を必ず与えてください。ただし支援技術へ自動伝達されることは保証されません。",
            "指定幅を基準に実寸比を保ち、文書の余白と背景に合わせます。",
            "ロード中や失敗時はプレースホルダーになり得ます。ResourceSystem の Pump とスコープ寿命が必要です。",
            "ImageBlock",
            alternatives: [new("ImageView", "CPU 側の RGBA ピクセル列を直接表示します。")]
        ),
        Page(
            "ImageView",
            "Rendering",
            "ImageView",
            "CPU 側の RGBA ピクセル列を表示する低水準画像ビューです。動的プレビューやデバッグ表示に使います。",
            ["CPU 側の RGBA ピクセル列を動的プレビューやデバッグ表示へ使う場合。"],
            ["ResourceSystem から文書用画像を読み込む場合や、GPU で直接描画する場合。"],
            "var view = ImageView(192, 144); view.SetPixels(w, h, rgba);",
            "ピクセル配列は呼び出し側が生成し、ビューは最新内容を GPU 実体化まで保持します。",
            "表示寸法と SetPixels(width, height, rgba) が中心です。",
            "操作や代替文は提供しません。説明テキストを別に用意してください。",
            "Widget サイズへ拡大縮小されます。鮮明さが必要なら入力解像度と表示寸法を合わせます。",
            "RGBA 配列長と寸法を一致させる必要があります。画像資源はビューの寿命に従います。",
            "ImageView",
            alternatives: [new("ImageBlock", "ResourceSystem の画像を文書ブロックとして表示します。")]
        ),
        Page(
            "MathBlockView",
            "Rendering",
            "MathBlockView",
            "数式記述をブロック表示する閲覧コントロールです。技術文書や説明画面に使います。",
            ["技術文書や説明画面へ数式を読み取り専用でブロック表示する場合。"],
            ["数式そのものを対話編集する場合や、通常の短い本文だけを表示する場合。"],
            "MathBlockView(source)",
            "数式ソースは呼び出し側、整形・描画結果はビューが所有します。",
            "数式ソースと表示幅などを指定します。",
            "閲覧用途です。読み上げ可能な説明を併記し、数式の支援技術変換を前提にしないでください。",
            "本文幅と文字色に合わせ、長い式が切れない領域を確保します。",
            "未対応構文や不正な式は表示できません。編集機能はありません。",
            "MathBlockView",
            alternatives: [new("Text", "数式記法を解釈しない通常文字列を表示します。")],
            componentType: "global::Luxel.MathText.MathBlockView"
        ),
        Page(
            "Sparkline",
            "Rendering",
            "Sparkline",
            "小さな領域へ時系列の傾向を簡潔に表示します。",
            ["小さな領域で時系列の傾向だけを素早く示す場合。"],
            ["正確な値、軸、凡例、複数系列の比較が必要な場合。"],
            "Sparkline(values, width: 120, height: 28)",
            "値列は呼び出し側が所有し、表示はそのスナップショットを描画します。",
            "values、width、height、color が中心です。",
            "閲覧専用です。正確な値と意味をテキストでも提示し、図だけへ依存しないでください。",
            "周辺の文字サイズと情報密度に合わせ、テーマで十分なコントラストを確保します。",
            "軸、凡例、詳細操作、支援技術向けデータ表は自動ではありません。",
            "Sparkline",
            alternatives: [new("Canvas2D", "軸や注釈を含む独自可視化を描きます。")]
        ),
        Page(
            "Spinner",
            "Rendering",
            "Spinner",
            "完了時刻が短く予測できない処理中であることを示します。",
            ["進捗率が分からない短い処理について、処理中であることを補助表示する場合。"],
            ["進捗率、完了時刻、取消操作を示す場合や、文字説明なしで重要状態を伝える場合。"],
            "Spinner(spinnerSize: 20, color: UiTheme.T.Primary)",
            "回転角は Widget 内部が保持し、処理中かどうかと Widget の表示寿命は呼び出し側が所有します。",
            "`spinnerSize` と `color` が固有パラメーターです。進捗値、処理状態、取消イベントはありません。",
            "操作はなく、実体化中は animation tick ごとに回転を継続します。処理内容や完了は別の文字情報でも通知します。",
            "周囲の文言と整列し、テーマ色へ追従させます。",
            "進捗率は表しません。連続 animation を登録するため、不要になった Spinner は Widget ツリーから外し、長時間処理には状態文や取消経路を併設します。",
            "Spinner",
            alternatives: [new("Text", "処理内容や状態を文字で明示します。")]
        ) with
        {
            Anatomy = "24 点の円弧ポリラインを持つ一つの描画ノードから構成します。",
            Variants = "`spinnerSize` で直径、`color` で色を指定します。進捗値 variant はありません。",
            FocusActivationDismissal = "focus、activation、dismissal はありません。表示の追加・削除は呼び出し側が行います。",
            Accessibility = new("隣接する文字で処理内容を示します。", "専用の progressbar/status semantic role は公開しません。", "処理中状態や進捗値は保持・公開しません。", "円弧色と背景のコントラストを確認します。", "実体化中は毎 tick 約 5 rad/s で連続回転します。", "動きを減らす設定、進捗率、完了通知は提供しません。"),
            Api = new("Spinner", "`spinnerSize` と `color` が固有パラメーターです。進捗値、処理状態、取消イベントはありません。", "固有イベントはありません。処理の完了・失敗・取消は外部状態で管理します。"),
        },
        Page(
            "SurfaceView",
            "Rendering",
            "SurfaceView",
            "独立した RetainedCanvas と UiHost を子サーフェスとして埋め込みます。プレビューや隔離された UI に使います。",
            ["独立した RetainedCanvas と UiHost を隔離されたプレビューとして埋め込む場合。"],
            ["通常の子 Widget を同じホストで構成するだけの場合。"],
            "var surface = SurfaceView(320, 200); surface.SetContent(child);",
            "子ツリーのフォーカス、オーバーレイ、状態は子 UiHost 内に閉じます。親は SurfaceView と内容設定を所有します。",
            "表示寸法と SetContent が中心です。",
            "入力はローカル座標へ変換して子へ転送されます。親子をまたぐキーボード・支援技術統合は保証されません。",
            "固定寸法を基本とし、親側の Border で境界を明示します。",
            "子ごとに framebuffer とホスト資源を使います。大量配置を避け、破棄時に子資源も解放される前提で設計します。",
            "SurfaceView",
            alternatives: [new("Box", "同じ UiHost 内で通常の子 Widget を配置します。")]
        ),
        Page(
            "TableBlock",
            "Rendering",
            "TableBlock",
            "行列データを文書内で表示し、セルを直接編集できる表ブロックです。",
            ["文書内の小規模な行列データを表示し、セルを直接編集する場合。"],
            ["大量行の仮想化、列操作、行単位選択が必要な場合。"],
            "TableBlock(payload, 420, updated => Commit(updated))",
            "TablePayload は呼び出し側が所有し、編集確定ごとの commit で新しい内容を受け取ります。",
            "payload、表示幅、commit が中心です。",
            "セルを選択して編集し、Tab または Enter で移動します。最下段の Enter で行が追加されます。表の読み上げ意味は保証されません。",
            "列幅は全幅から配分されます。文書面と編集フォーカス色をテーマに合わせます。",
            "大規模データ、列の高度な型、仮想化には向きません。確定内容を永続化する責任は commit 側にあります。",
            "TableBlock",
            alternatives: [new("DataGrid", "大量行を仮想化し、行単位で選択します。")],
            keyboard: [new("`Tab` / `Enter`", "次の編集セルへ移動します。"), new("末尾行の `Enter`", "新しい行を追加します。")]
        ),
    ];
}
