using Luxel.Gallery;
using Luxel.Gallery.UI;

namespace Luxel.UI.Gallery;

internal static partial class UiControlDocs
{
    private static readonly ControlDocsPage[] RenderingPages =
    [
        Page(
            "Canvas2D",
            "Rendering",
            "Canvas2D",
            "Scene2D コマンドをコールバックで組み立て、一つの保持描画ノードとして表示する低水準 2D 領域です。静的描画と tick 時間による連続描画を選べます。",
            ["標準 Widget では表しにくい小規模な図形、注釈付き可視化、描画デモを一つのノードで実装する場合。", "決定的な tick 時間で独自アニメーションを描く場合。"],
            ["子 Widget のレイアウト、フォーカス、入力、semantic role が必要な場合。", "大量データの仮想化や GPU コマンドを直接記録する場合。"],
            "Canvas2D(320, 180, draw: scene => DrawStatic(scene),\n    animate: (scene, time) => DrawFrame(scene, time))",
            "描画モデルと callback は呼び出し側が所有します。`time` は Canvas2D 内部の累積 tick 秒で、同じ Widget の再実体化をまたいで継続します。",
            "`canvasWidth`、`canvasHeight`、任意の `draw(Action<Scene2D>)`、任意の `animate(Action<Scene2D, float>)` が固有入力です。共通 width/height はレイアウトで参照しません。",
            "Canvas2D 自身は hit target、focus、keyboard、scroll、semantic node を登録しません。必要な操作は隣接する標準コントロールで提供します。",
            "Scene2D 内の各色をそのまま保持します。要求寸法は最低 1 px で親制約へ収めますが、自身の矩形で描画を clip しません。",
            "`animate` があると毎 tick 新しい Scene2D を encode して Content を差し替えます。reduced-motion 設定や停止 API はなく、callback 例外・描画量・代替説明は呼び出し側で設計します。",
            "Canvas2D",
            alternatives: [new("GpuView", "GPU command、shader、offscreen target を直接扱う場合。"), new("Sparkline", "単一系列の小さな傾向表示だけで足りる場合。")]
        ) with
        {
            Anatomy = "一つの透明な Widget root と、`draw` の後に `animate` を呼んで構築した一つの `Scene2D` Content から構成します。子 Widget は持ちません。",
            Variants = "`draw` だけの静的形、`animate` だけまたは両方を使う連続形があります。固有の背景、clip、入力 variant はありません。",
            FocusActivationDismissal = "フォーカス、activation、dismissal はありません。図を操作させる場合は座標処理を別コントロールへ実装するか、標準 Widget を選びます。",
            Accessibility = new("隣接する見出し・説明・データ要約で図の目的を示します。", "専用 semantic role と図形ごとの semantic node は公開しません。", "hover、選択、再生状態を保持・公開しません。", "各 Scene2D 色と背景のコントラストを callback 側で確認し、色だけで系列や状態を区別しません。", "`animate` は host tick ごとに継続し、動きを減らす設定を自動参照しません。静止表示を選べる外部状態や `draw` だけの代替を用意します。", "読み上げ可能なテキスト、表、値一覧は自動生成されません。"),
            ThemeLayout = new("テーマ色は自動適用されません。必要なら callback が `UiTheme` 由来の値を読み、テーマ変更時の再実体化・再描画を設計します。", "`canvasWidth`/`canvasHeight` の自然サイズを親制約へ収めます。Scene2D の座標系は要求寸法基準です。", "要求値は最低 1 px ですが、親に小さく制約されても描画コマンド自体を縮小・clip しないため、callback は実際の表示制約を前提にしすぎないようにします。"),
            Constraints = new("子レイアウト、hit testing、テキスト入力、自己 clip はありません。animated 形は毎フレーム Scene2D を再 encode するため、形状数と割り当てを小さく保ちます。", "Canvas2D 自身は明示破棄する GPU 資源を持たず、animation 登録は realization scope の破棄で外れます。callback が閉包する外部資源は呼び出し側が解放します。", "Scene2D を処理できる選択中の 2D rasterizer で動作し、GpuView のような GPU 専用 capability は要求しません。"),
            Api = new("Canvas2D", "`canvasWidth`、`canvasHeight`、`draw`、`animate` が主要 API です。`animate` の時間は wall clock ではなく累積 tick 秒です。", "固有イベントはありません。`animate` がある間は callback を毎 tick 呼び、scope 破棄時に登録を解除します。"),
        },
        Page(
            "DiagramBlock",
            "Rendering",
            "DiagramBlock",
            "Mermaid flowchart の限定サブセットを解析し、ランク配置したノードと有向辺を読み取り専用で描く文書ブロックです。",
            ["説明文書へ小規模な LR/RL/TB/TD/BT flowchart を埋め込み、矩形・角丸・ひし形ノードと矢印を表示する場合。"],
            ["Mermaid 全構文、subgraph、style、click、複雑な交差最小化、ノード編集が必要な場合。"],
            "Luxel.Diagram.Factories.DiagramBlock(\"\"\"\nflowchart LR\nsource[入力] --> result{結果}\n\"\"\")",
            "初回レイアウトで parse/layout 結果を Widget 内に cache します。同じインスタンスの `source` を後から変更しても再 parse しないため、図を更新するときは新しい DiagramBlock を作ります。",
            "`source` と `maxWidth` が固有パラメーターです。対応方向、ノード形、`-->` と任意の辺ラベルだけを使用します。",
            "閲覧専用で、hit target、focus、keyboard、semantic node はありません。図と同じ内容を本文や箇条書きでも提示します。",
            "Surface、BorderColor、TextMuted、Text のテーマ色へ recolor します。自然幅が有限の利用幅を超えると図全体を等比縮小します。",
            "対応外の行は例外ではなく黙って無視されます。線は直線、ランク内は宣言順で、混雑した図の交差最小化や個別スクロールはありません。",
            "DiagramBlock",
            alternatives: [new("NodeGraphView", "ノードと接続を対話編集する場合。"), new("Canvas2D", "独自の図形、配置、注釈を直接描く場合。")],
            related: [new("Examples/Embeds/Diagram/Basic", "Flowchart 埋め込み", "対応する Mermaid サブセットを文書面へ描く実例です。", StoryKind.Basic)],
            componentType: "global::Luxel.Diagram.DiagramBlock"
        ) with
        {
            Anatomy = "parse 済み `DiagramSpec`、rank layout の `DiagramLayoutResult`、箱の fill/stroke、辺、ノード文字、辺ラベルを色群ごとに分けた五つの Scene2D ノードから構成します。",
            Variants = "方向は LR/RL を横、TB/TD/BT を縦として扱います。ノードは `id[label]`、`id(label)`、`id{label}`、辺は `A --> B` または `A -->|label| B` です。",
            FocusActivationDismissal = "フォーカス、activation、dismissal はありません。ノード単位の選択やリンク起動も実装しません。",
            Accessibility = new("本文の見出しと、ノード・関係を説明するテキストを図の前後に置きます。", "diagram、image、node、edge の semantic role は公開しません。", "ノード選択や展開状態はありません。", "テーマの Surface/Text/BorderColor/TextMuted の組み合わせを利用し、縮小後もラベルが読める幅を確保します。", "アニメーションはありません。", "視覚的な線や方向は読み上げられません。同等の関係を文章やリストでも提供します。"),
            ThemeLayout = new("箱、枠、辺、文字を host Theme の色へ effect で追従させます。", "初回 parse/layout の自然サイズを使い、`maxWidth > 0` ならその値、0 なら親 `MaxW` を縮小上限にします。", "幅だけでなく高さも同じ scale で縮めます。拡大はせず、空または全行未対応なら 0 サイズです。"),
            Constraints = new("対応外構文はエラー表示せず無視されます。後勝ちのノード再宣言はラベルと形を更新し、循環は配置を止めず逆向き辺として描きます。", "外部資源と animation はありません。cache した parse/layout は同一インスタンスの寿命中に更新されないため、source 更新時は Widget を再生成します。", "標準 Scene2D/font host で動作します。Mermaid runtime やブラウザー JavaScript は使用しません。"),
            Api = new("DiagramBlock", "`source` と `maxWidth` が主要 API です。parser は flowchart/graph の限定構文だけを扱います。", "イベントはありません。source を動的更新する event/model contract もありません。"),
        },
        Page(
            "GpuView",
            "Rendering",
            "GpuView",
            "GpuDevice と専用 offscreen surface を callback へ渡し、GPU 描画結果または Loading/Failed 状態を UI ツリーへ合成する GPU 専用ビューです。",
            ["shader、pipeline、buffer を使う GPU サンプルやリアルタイム出力を固定領域へ埋め込む場合。", "resource signal の準備状態を Loading/Failed/Ready として一つの表示面で扱う場合。"],
            ["Scene2D だけで表せる軽量 2D 描画の場合。", "CPU/Skia-only host、標準 Widget の入力・semantics、デバイス喪失の自動復旧が必要な場合。"],
            "GpuView(320, 240, render: (device, surface, time) =>\n{\n    using GpuCommandBuffer command = device.MainQueue.StartCommandRecording();\n    Record(command, surface.ColorTarget, time);\n    surface.CopyColorToFramebuffer(command);\n    command.Finish();\n    device.MainQueue.Submit(command);\n    return GpuViewRenderResult.Ready;\n}, animated: false, dispose: ReleaseResources)",
            "GpuView が `ColorTarget` と aligned device-local `Framebuffer` を realization scope 内で所有します。callback が捕捉する shader/pipeline/buffer は呼び出し側が所有し、必要なら `dispose` で解放します。",
            "`viewWidth`、`viewHeight`、`render(GpuDevice, GpuViewSurface, float)`、`animated`、`dispose` と `GpuViewRenderResult` が中心です。共通 width/height は参照しません。",
            "入力、focus、keyboard、semantic node は登録しません。render callback は描画専用で、座標入力 API はありません。操作は周囲の Button/Slider などから外部モデルへ与えます。",
            "Ready では framebuffer、Loading/Failed ではテーマの SurfaceAlt と静的状態 Icon を表示します。要求寸法は最低 1 px で、offscreen 解像度と表示寸法は親制約により異なり得ます。",
            "GPU 2D rasterizer が必須です。callback は command の記録・submit と通常 `CopyColorToFramebuffer` を担当します。デバイス喪失の監視・自動再作成はなく、例外は Failed 表示へ変換されます。",
            "GpuView",
            alternatives: [new("Canvas2D", "Scene2D を CPU 側で encode し、選択中の 2D rasterizer へ任せる場合。"), new("SurfaceView", "独立した子 UiHost と入力ブリッジを埋め込む場合。")]
        ) with
        {
            Anatomy = "GpuView root、bindless framebuffer を描く image node、Loading/Failed 用の背景と Icon、`Rgba8Unorm` ColorTarget と 64 pixel stride の device-local Framebuffer を持つ `GpuViewSurface` から構成します。",
            Variants = "`animated: true` は即時描画後に毎 tick、`false` は effect 依存の signal 更新時に描画します。表示状態は `Ready`、`Loading`、`Failed` の三つです。",
            FocusActivationDismissal = "フォーカス、activation、dismissal はありません。GPU 出力自体を直接操作する契約は提供しません。",
            Accessibility = new("周囲の見出しと状態文で出力の目的・Loading・失敗を文字でも示します。", "image、status、application などの semantic role は公開しません。", "`GpuViewRenderResult` は視覚 fallback を切り替えますが semantic 状態として公開しません。", "GPU 出力内の色と fallback Icon/背景のコントラストを確認し、状態を色だけへ依存させません。", "`animated` 既定値は true で毎 tick 描画します。reduced-motion は自動適用されないため、外部設定に応じて false を選ぶか静止 callback を用意します。", "出力内容、Loading、Failed の読み上げ情報は自動生成されません。"),
            ThemeLayout = new("fallback は SurfaceAlt、TextMuted、Danger を使います。Ready 出力の色は render callback が決めます。", "`viewWidth`/`viewHeight` を最低 1 px にして親制約へ収めますが、surface 自体は要求寸法の uint 解像度で確保します。", "親に小さく制約されると大きい offscreen framebuffer を表示矩形へ縮小します。共通 width/height と自己 clip は使いません。"),
            Constraints = new("一フレームごとに callback が GPU work を記録・submit し、Ready 前に framebuffer へ copy する責務があります。animated 形の頻度と GPU 同期を小さく保ちます。", "realization scope の破棄で `dispose` callback を呼んだ後に surface を破棄します。callback-owned 資源は `dispose` を再実体化ごとに呼ばれても安全な単位で所有します。", "`GpuDeviceRasterizer2D` がない CPU/Skia host では `NotSupportedException` です。device replacement/loss の自動復旧はなく、外部資源と Widget を再作成します。"),
            Api = new("GpuView", "`GpuViewRender`、`GpuViewSurface.ColorTarget/Framebuffer/StridePixels`、`CopyColorToFramebuffer`、`animated`、`dispose` が主要 API です。", "render 例外は `UiError` へ報告して `Failed` にします。`dispose` は realization lease 解放時に呼ばれ、固有入力イベントはありません。"),
        },
        Page(
            "Icon",
            "Rendering",
            "Icon",
            "閉じた `IconKind` 列挙から小さなベクター記号を描きます。装飾にも pointer-only の簡易 hit target にもできますが、単体 Button の代替ではありません。",
            ["ラベル付き Button や入力欄の leading/trailing slot で、操作や状態の視覚識別を補助する場合。", "小さな静的記号をテーマ色と線幅で描く場合。"],
            ["アイコンだけで意味や状態を伝える場合。", "キーボード focus、button semantics、十分な touch target を持つ独立操作が必要な場合。"],
            "Icon(IconKind.Search, iconSize: 16, stroke: 1.5f,\n    color: Bind.From(() => UiTheme.T.TextMuted))",
            "内部状態は持ちません。kind、色、寸法は Bindable、click 後の業務状態は `onClick` の呼び出し側が所有します。",
            "`kind`、`iconSize`、`stroke`、任意の `onClick(Icon sender)`、`color` が固有 API です。利用可能 kind は enum で固定されています。",
            "`onClick` がある場合だけ上下左右 2 px 拡張した pointer hit target と Hand cursor を登録します。focus と keyboard activation は登録しません。",
            "色未指定時は Theme.Text です。正方形サイズは raw `iconSize` を親制約へ収めますが、描画は raw サイズ基準で自己 clip しません。",
            "未知の enum cast は空描画です。Loading kind は静的な三点で、アニメーションではありません。pointer-only click を主要操作へ使わないでください。",
            "Icon",
            alternatives: [new("Button", "ラベル、focus、keyboard、button semantics を持つ独立操作が必要な場合。"), new("Text", "意味を文字で直接伝える場合。")],
            related: [new("Controls/Rendering/Icon/Examples/Kinds", "IconKind 一覧", "主要 kind とテーマ外の色指定を比較します。", StoryKind.Example)]
        ) with
        {
            Anatomy = "24×24 相当の正規化座標から組む一つの Scene2D vector node と、任意の拡張 pointer hit rectangle から構成します。",
            Variants = "`IconKind` は Check、Close、ChevronDown/Right/Left、Plus、Minus、Dot、Circle、Search、Loading、Failed です。`iconSize`、`stroke`、`color` を変更できます。",
            FocusActivationDismissal = "`onClick` 付きでも focus target にはならず、pointer click だけで activation します。dismissal はありません。独立操作には Button を使います。",
            Accessibility = new("Icon と一緒に見える文字ラベルまたは Tooltip を置きます。独立操作なら Button のラベルに含めます。", "専用 image/button semantic role は公開しません。", "disabled、pressed、selected、loading 状態を保持・公開しません。", "線と背景のコントラストを確認し、色や形だけで状態を区別しません。", "固有アニメーションはなく、`IconKind.Loading` も静止画です。", "`onClick` 付きでもキーボードと支援技術から起動できません。"),
            ThemeLayout = new("`color` 未指定時は Theme.Text へ effect で追従します。", "`iconSize` の正方形を親制約へ収め、margin/alignment は外側レイアウトが扱います。", "hit target は描画寸法より各辺 2 pxだけ広い実装です。十分な操作面が必要なら Button/Border で包みます。raw 描画が constrained Size を超える場合の clip はありません。"),
            Constraints = new("閉じた enum と組み込み path だけを描き、任意 SVG/名前登録/画像読込はありません。", "固有資源と subscription はありません。onClick の閉包寿命は呼び出し側が管理します。", "標準 Scene2D 2D host で動作します。pointer click 以外の入力経路はありません。"),
            Api = new("Icon", "`IconKind kind`、`iconSize`、`stroke`、`color`、任意の `OnClick` が主要 API です。", "`OnClick` がある場合だけ pointer click で `OnClick(this)` を発火します。keyboard event はありません。"),
        },
        Page(
            "ImageBlock",
            "Rendering",
            "ImageBlock",
            "ResourceSystem の画像を等比表示し、読み込み状態、見える alt caption、pointer による横幅 resize を備える文書用 image block です。",
            ["Markdown 画像の URI、代替文字列、ResourceSystem を文書内の一つの block として表示する場合。", "読み込み後に利用者が bottom-right handle を横ドラッグして表示幅を調整する場合。"],
            ["CPU pixel buffer を高頻度更新する場合。", "キーボード resize、semantic image/alt exposure、crop/fit mode が必要な場合。"],
            "ImageBlock(new ImagePayload(path, \"サンプル画像\"), resources, maxWidth: 360)",
            "ResourceSystem が decode/cache を共有し、ImageBlock は ResourceHandle、state subscription、表示幅、focus、GPU upload buffer を保持します。`Dispose` で handle ref-count と buffer を解放します。",
            "`payload(Src, Alt)`、`resources`、`maxWidth` が固有入力です。読み込み後の表示幅は内部 `_displayWidth` で保持し、専用 setter/event はありません。",
            "読み込み後は全体を focusable hit target にし、右下 20 px の handle を横ドラッグすると幅を更新します。keyboard resize/action はなく、alt は caption/placeholder として見える文字です。",
            "画像は実寸比を保ち、自然幅と maxWidth の小さい方から開始します。focus 中は Primary の outline/handle、caption は TextMuted、placeholder は SurfaceAlt です。",
            "GPU rasterizer と ResourceSystem pump が必要です。alt は semantic tree に公開されません。明示 Dispose が必要で、source/payload を同一インスタンスで差し替える契約はありません。",
            "ImageBlock",
            alternatives: [new("ImageView", "ResourceSystem を使わず CPU RGBA8 pixels を直接更新する場合。"), new("Text", "画像内容を確実に読み上げられる説明として提供する場合。")]
        ) with
        {
            Anatomy = "ResourceHandle/CpuImage、host-mapped GPU image buffer、画像 node、focus outline、右下 resize handle、任意 caption、または Loading/Failed placeholder と文字から構成します。",
            Variants = "Resource 状態に応じて Loading/Failed placeholder と loaded image を切り替えます。`Alt` が空でなければ loaded image の下に caption を追加し、`maxWidth` は最低 40 pxです。",
            FocusActivationDismissal = "loaded 状態では pointer hit で focus を取得します。bottom-right handle の horizontal drag で resize しますが、Enter/Space/矢印の activation はなく、dismissal もありません。",
            Accessibility = new("`ImagePayload.Alt` を具体的な説明にし、必要なら同内容を本文にも書きます。", "image role と alt semantic description は公開しません。Alt は見える caption/placeholder 文字としてだけ描きます。", "resource loading/failed、focus、表示幅を semantic 状態として公開しません。", "画像内容だけに情報を依存せず、outline、handle、caption、placeholder のテーマコントラストを確認します。", "固有アニメーションはありません。Resource 状態変化で placeholder から画像へ再実体化します。", "キーボードだけで resize できず、alt が支援技術へ自動伝達されません。本文による代替を用意します。"),
            ThemeLayout = new("outline/handle は Primary、caption/placeholder 文字は TextMuted、placeholder 面は SurfaceAlt を使います。画像 pixels 自体はテーマ変更しません。", "loaded 時は `min(maxWidth, image.Width)` を自然幅にし、drag 幅を `min(120, natural)` から `maxWidth` へ clamp して等比高 + caption 高を計算します。", "親の有限制約で最終 Size はさらに収められます。placeholder は `maxWidth × 56` を要求します。画像 crop、別 fit mode、自己スクロールはありません。"),
            Constraints = new("Resource state 更新で `MarkNeedsRealize` し、loaded 時に CpuImage 全体を GPU buffer へ upload します。大画像の upload と一インスタンス一 buffer のコストを見込みます。", "`Dispose` が state subscription、ResourceHandle、GPU buffer を解放します。Widget ツリーから外すだけでは IDisposable は自動実行されないため所有者が明示破棄します。", "ResourceSystem と GPU 2D rasterizer が必要です。CPU/Skia-only host では loaded image upload ができず、device loss の自動復旧もありません。"),
            Api = new("ImageBlock", "`ImagePayload(Src, Alt)`、`ResourceSystem`、`maxWidth`、`Dispose` が主要 API です。表示幅は pointer drag で内部更新します。", "公開 commit/resize event はありません。resource state subscription が再実体化を要求し、`Content` の永続化や width 書戻しは行いません。"),
        },
        Page(
            "ImageView",
            "Rendering",
            "ImageView",
            "CPU の premultiplied RGBA8 pixels を host-mapped GPU buffer へ upload し、指定表示寸法へ nearest 拡縮する低水準画像ビューです。",
            ["デバッグ preview、CPU renderer 出力、同寸法 pixel buffer を頻繁に差し替える場合。", "ResourceSystem の URI/decode/cache を介さず caller-provided pixels を表示する場合。"],
            ["文書画像、alt caption、resource loading state、semantic image が必要な場合。", "CPU/Skia-only host や自動 device-loss recovery が必要な場合。"],
            "ImageView view = ImageView(width: 192, height: 144);\nview.SetPixels(sourceWidth, sourceHeight, premultipliedRgba);",
            "SetPixels は入力を upload/copy し、実体化前だけ pending CPU copy を保持します。RgbaImagePresenter が GPU buffer を所有し、ImageView の所有者が `Dispose` を呼びます。",
            "表示 `width`、`height` と `SetPixels(int width, int height, ReadOnlySpan<byte> rgba)`、`Dispose` が中心です。",
            "hit target、focus、keyboard、semantic node、alt text はありません。操作や画像説明は隣接 Widget で提供します。",
            "表示寸法は最低 1 px で親制約へ収め、source pixels を nearest sampling で全面へ拡大縮小します。自己 clip はありません。",
            "GPU rasterizer が必須です。短い/非正寸法入力は黙って無視し、余分な bytes は無視します。同 device・同 source 寸法だけ buffer を再利用し、明示 Dispose が必要です。",
            "ImageView",
            alternatives: [new("ImageBlock", "ResourceSystem、loading placeholder、caption、pointer resize を使う文書画像の場合。"), new("GpuView", "pixels を CPU へ戻さず GPU command で直接描く場合。")]
        ) with
        {
            Anatomy = "ImageView Widget、一つの image Scene2D node、source pixels を保持する一つの host-mapped bindless `GpuBuffer` から構成します。",
            Variants = "表示 width/height と source width/height は独立です。同 source 寸法更新は buffer reuse、寸法または device 変更は再確保です。fit/filter variant はありません。",
            FocusActivationDismissal = "フォーカス、activation、dismissal はありません。",
            Accessibility = new("画像の目的、値、失敗状態を隣接 Text で示します。", "image semantic role と alt description は公開しません。", "loading、failed、selected 状態は保持・公開しません。pixels 未設定時は空描画です。", "透明 pixels は premultiplied RGBA を使い、背景上で必要なコントラストを画像生成側で確保します。", "固有アニメーションはありません。高頻度 SetPixels は外部更新ループが駆動します。", "画像内容の読み上げ、focus、拡大操作は提供しません。"),
            ThemeLayout = new("テーマ色は自動適用されません。pixels をそのまま表示します。", "表示 width/height を最低 1 px として親制約へ収め、source 全体を constrained Size へ nearest 拡縮します。", "source aspect ratio は自動保持しません。鮮明さ・比率が必要なら表示寸法を source 比率へ合わせます。描画は raw Size へ作られますが自己 clip はありません。"),
            Constraints = new("`rgba.Length >= width * height * 4` が必要で、短い入力は no-op、長い入力は先頭必要分だけ使います。毎更新で host-mapped buffer へ全 bytes を copy します。", "同寸法は buffer reuse、変更時は旧 buffer を dispose して再確保します。Widget removal は `Dispose` を呼ばないため、所有者が明示破棄します。", "GPU 2D rasterizer 専用です。device change 後は次の SetPixels で再確保できますが、旧 pixels の自動復元と device-loss handling はありません。"),
            Api = new("ImageView", "表示 `width`/`height`、`SetPixels`、`Dispose` が主要 API です。source は premultiplied RGBA8 を推奨します。", "イベントはありません。SetPixels は成功/失敗値を返さず、不正入力を黙って無視します。"),
        },
        Page(
            "MathBlockView",
            "Rendering",
            "MathBlockView",
            "TeX の限定サブセットを parse・組版し、ベクター文字と分数線・根号・括弧を一つの読み取り専用 block として描きます。",
            ["技術文書へ上付き・下付き、分数、根号、ベクトル、matrix/pmatrix/bmatrix、Greek/演算子を表示する場合。"],
            ["完全な TeX/LaTeX、数式編集、MathML semantics、番号付け、改行数式が必要な場合。"],
            "Luxel.MathText.Factories.MathBlockView(\"\"\"\\frac{a_i}{\\sqrt{x^2 + y^2}}\"\"\", fontSize: 20, maxWidth: 420)",
            "初回レイアウトで parse node を cache します。同じインスタンスの source を後から変えても再 parse しないため、式更新時は新しい MathBlockView を作ります。",
            "`source`、`fontSize`、`maxWidth` が固有パラメーターです。source は block delimiter の内側だけを渡します。",
            "閲覧専用で、hit target、focus、keyboard、semantic node はありません。式の意味や読みを周囲の本文でも説明します。",
            "Theme.Text へ recolor し、自然幅が finite maxWidth/親幅を超えると全体を等比縮小します。改行や横スクロールはしません。",
            "未知 command は `\\cmd` の文字として残り、不完全 group は部分/空 node へ縮退します。完全な TeX error reporting、semantic math、source 更新はありません。",
            "MathBlockView",
            alternatives: [new("Text", "TeX を解釈せず短い文字列または Unicode 数式を表示する場合。"), new("TextArea", "数式 source を編集する場合。")],
            related: [new("Examples/Embeds/Math/Basic", "数式埋め込み", "分数、行列、ベクトルを文書面へ描く実例です。", StoryKind.Basic)],
            componentType: "global::Luxel.MathText.MathBlockView"
        ) with
        {
            Anatomy = "cache した MathNode、計測した MathBox、一つの Scene2D に追加する font glyph と分数線・根号・括弧 stroke から構成します。",
            Variants = "`fontSize` と `maxWidth` を選びます。構文 variant は script、frac、sqrt、vec、matrix/pmatrix/bmatrix、Greek/演算子/関数名です。",
            FocusActivationDismissal = "フォーカス、activation、dismissal はありません。選択、copy、編集も提供しません。",
            Accessibility = new("式の目的、変数、読み方、結論を周囲の Text で説明します。", "math、formula、text の semantic node は公開しません。", "編集、選択、エラー状態はありません。", "Theme.Text と背景のコントラストを確認し、縮小後の stroke と文字が読める幅を確保します。", "アニメーションはありません。", "TeX source や組版結果は読み上げ可能な MathML へ変換されません。"),
            ThemeLayout = new("全 glyph/stroke を Theme.Text へ effect で recolor します。", "source の改行を空白へ置き換えて一つの block として測り、`maxWidth > 0` または親 `MaxW` を超えると scale down します。", "拡大と自動改行はせず、幅・高さを同率で縮めます。長大な式は小さくなりすぎるため、式を分割するか説明を併記します。"),
            Constraints = new("TeX 全仕様、macro、environment 一般、error diagnostic はありません。未知 command は literal 表示されるため、見た目を確認します。", "外部資源と animation はありません。cache した parse node は同一インスタンスで更新されないため source 変更時は再生成します。", "標準 Scene2D/vector font host で動作し、ブラウザー MathJax/KaTeX は使用しません。"),
            Api = new("MathBlockView", "`source`、`fontSize`、`maxWidth` と TexParser の限定構文が主要 API です。", "イベントはありません。source update、selection、copy contract は提供しません。"),
        },
        Page(
            "Sparkline",
            "Rendering",
            "Sparkline",
            "数値系列の傾向を小さな折れ線＋面または棒で示す読み取り専用 micro chart です。値は `SetValues` で差し替えます。",
            ["fps、memory、短い時系列などの傾向だけを狭い領域で補助表示する場合。", "同寸法の一つの系列を実体化後も軽量に更新する場合。"],
            ["正確な値、軸、単位、凡例、複数系列、zoom/hover detail が必要な場合。"],
            "Sparkline line = Sparkline(width: 120, height: 28, bars: false);\nline.SetValues(values, min: 0, max: 100);",
            "SetValues は values を内部配列へ copy し、min/max とともに Sparkline が保持します。データの業務上の正本と更新頻度は呼び出し側が所有します。",
            "表示 `width`、`height`、`bars`、`lineColor`、`background` と `SetValues(values, min?, max?)` が中心です。",
            "hit target、focus、keyboard、semantic node はありません。正確な最新値、単位、期間を隣接 Text でも示します。",
            "幅・高さは最低 8 px、既定色は Primary と SurfaceAlt です。折れ線は 1.5 px、面は同色 25% alpha、bars は bottom anchored です。",
            "軸、label、clip、selection、animation はありません。各 SetValues で配列 copy と Scene2D 再構築を行い、明示 range 外の値や親の tight 制約では描画が矩形外へ出る場合があります。",
            "Sparkline",
            alternatives: [new("Canvas2D", "軸、注釈、複数系列を独自描画する場合。"), new("Text", "値と変化量を文字だけで明確に伝える場合。")]
        ) with
        {
            Anatomy = "背景 node、25% alpha fill node、line node の三層と、copy された float values/min/max から構成します。",
            Variants = "`bars: false` は 2 点以上で line＋area、`bars: true` は 1 点以上で bars です。range は data 自動または明示 min/max です。",
            FocusActivationDismissal = "フォーカス、activation、dismissal はありません。hover tooltip や点選択もありません。",
            Accessibility = new("系列名、現在値、単位、期間、増減を隣接 Text で示します。", "chart、image、data point の semantic role は公開しません。", "選択、hover、更新中状態を保持・公開しません。", "lineColor と background のコントラストを確認し、上昇・下降や閾値を色だけに依存させません。", "固有アニメーションはなく、SetValues 時に形状が即時差し替わります。", "軸・値表・読み上げ可能な系列は自動生成されません。"),
            ThemeLayout = new("lineColor 未指定時は Primary、background 未指定時は SurfaceAlt へ effect で追従します。", "width を Length として解決して最低 8 px 基準、height は最低 8 px とし、親制約へ収めます。", "描画 shape は解決前の最低 height と解決 width を使い自己 clip しません。aspect ratio と source 点間隔は全幅へ均等配分します。"),
            Constraints = new("SetValues は入力全体を copy し、形状再構築は点数に比例します。高頻度・大量点では downsample します。NaN/Infinity の特別処理はありません。", "固有 GPU resource と Dispose はありません。実体化後の SetValues は既存 node Content を差し替えます。", "標準 Scene2D host で動作します。支援技術向け値表は別 Widget で提供します。"),
            Api = new("Sparkline", "`width`、`height`、`bars`、`lineColor`、`background`、`SetValues(ReadOnlySpan<float>, float? min, float? max)` が主要 API です。", "イベントはありません。SetValues は呼び出しごとに values を copy して表示を更新します。"),
        },
        Page(
            "Spinner",
            "Rendering",
            "Spinner",
            "完了率を持たない処理中を補助表示する、常時回転する円弧 indicator です。処理状態や完了通知は所有しません。",
            ["短時間で完了率を計算できない処理の横に、文字状態を補助する小さな busy indicator を置く場合。"],
            ["進捗率、残り時間、取消、成功/失敗を示す場合。", "reduced-motion に応じて自動停止する indicator が必要な場合。"],
            "Spinner(spinnerSize: 20, color: Bind.From(() => UiTheme.T.Primary))",
            "回転角は Widget 内部で保持し、同じインスタンスの再実体化をまたいで継続します。実際の処理中/完了/失敗状態は呼び出し側が所有し、表示有無で Spinner の寿命を管理します。",
            "`spinnerSize` と `color` が固有パラメーターです。進捗値、running、animation disable、cancel event はありません。",
            "操作、focus、keyboard、semantic node はありません。実体化中は animation tick ごとに約 5 rad/s で回転します。",
            "色未指定時は Theme.Primary です。raw spinnerSize の正方形を親制約へ収めますが、描画と回転中心は raw size 基準です。",
            "常時 animation を登録し、reduced-motion を参照しません。共通 transform は回転更新で上書きされ、自己 clip もありません。不要時はツリーから外します。",
            "Spinner",
            alternatives: [new("Text", "処理内容、完了、失敗を文字で明示する場合。"), new("Sparkline", "進行率ではなく直近の処理量推移を示す場合。")]
        ) with
        {
            Anatomy = "24 点の円弧 polyline を持つ一つの Scene2D node と、中心回転 transform を毎 tick 更新する animation callback から構成します。",
            Variants = "`spinnerSize` で直径、`color` で色を指定します。進捗値、静止、速度、線幅 variant はありません。",
            FocusActivationDismissal = "focus、activation、dismissal はありません。表示の追加・削除は呼び出し側が行います。",
            Accessibility = new("隣接する文字で処理内容と処理中であることを示します。", "progressbar/status/busy semantic role は公開しません。", "処理中状態、進捗値、完了、失敗を保持・公開しません。", "円弧色と背景のコントラストを確認します。", "実体化中は毎 tick 約 5 rad/s で連続回転し、reduced-motion や停止パラメーターはありません。動きを避ける利用者向けには Spinner を出さず静的な状態文を使います。", "動きだけでは状態を読み上げられません。長時間処理には文字状態と取消経路を併設します。"),
            ThemeLayout = new("color 未指定時は Theme.Primary へ effect で追従します。", "spinnerSize の正方形を親制約へ収め、周囲の文字と Center/Stack で整列します。", "正値 clamp はなく、constrained Size より raw spinnerSize が大きい場合も描画を自己 clip しません。継承 transform は animation transform で上書きされます。"),
            Constraints = new("一つの animation callback を継続登録します。大量配置や非表示のままの保持を避け、処理終了時に Widget ツリーから外します。", "animation 登録は realization scope 破棄時に解除されます。外部処理や cancel token の寿命は呼び出し側が管理します。", "標準 Scene2D/tick host で動作します。platform reduced-motion 設定との統合はありません。"),
            Api = new("Spinner", "`spinnerSize` と `color` が固有 API です。進捗値、running、速度、取消 event はありません。", "固有イベントはありません。処理の完了・失敗・取消は外部状態で管理し、表示を外します。"),
        },
        Page(
            "SurfaceView",
            "Rendering",
            "SurfaceView",
            "独立した child RetainedCanvas、UiHost、GPU raster surface を一枚の画像として親 UI へ埋め込み、pointer・keyboard・text/IME 入力を橋渡しする iframe 相当のビューです。",
            ["Gallery preview、隔離された editor surface、独自 theme/overlay/focus state を持つ子 UI 島を固定矩形へ埋め込む場合。", "親 root を再構築せず `SetContent` で子 root を差し替える場合。"],
            ["同じ UiHost の通常 child Widget で十分な場合。", "CPU/Skia-only host、親子を統合した Tab 順・semantic tree・device-loss recovery が必要な場合。"],
            "SurfaceView surface = SurfaceView(320, 200);\nsurface.ChildTheme = previewTheme;\nsurface.SetContent(child, logicalWidth: 320, logicalHeight: 200);",
            "SurfaceView が child canvas/host/raster scene/surface registration/output buffers を所有し、親の再実体化をまたいで child state を保持します。所有者が明示 `Dispose` します。",
            "`surfaceWidth`、`surfaceHeight`、`SetContent(root, logicalWidth?, logicalHeight?)`、`Child`、`ChildTheme`、`ContentError`、`LastContentError`、`Dispose` が中心です。",
            "click、hover、move、drag、context、wheel と focus 中の key/text/composition/commit/IME を子へ 1:1 座標で転送します。親 Tab は親 focus traversal が消費し、Escape は子へ先に渡ります。",
            "child は透明 premultiplied surface へ描画し、親 node は実際の constrained Size で clip します。RenderScale に応じた物理解像度を使い、ChildTheme 未指定時は親 theme signal を共有します。",
            "GpuDeviceRasterizer2D と UiRendererState-backed composition host が必須です。child semantics は親へ bridge されず、explicit Dispose と device replacement 時の再生成が必要です。",
            "SurfaceView",
            alternatives: [new("Border", "同じ UiHost 内で一つの通常 child を装飾・clip する場合。"), new("GpuView", "子 UI ではなく GPU callback の描画結果だけを埋め込む場合。")]
        ) with
        {
            Anatomy = "child RetainedCanvas、child UiHost、IRasterScene2D、UiSurfaceState、PersistentUiOutput/GpuBuffer、親側 image node、入力 bridge 用 focus/hit/scroll target から構成します。",
            Variants = "ChildTheme を親と共有する形と独立 Signal を渡す形、surface と同じ logical size または小さい logical size を使う形があります。専用 fit/scale variant はありません。",
            FocusActivationDismissal = "pointer hit で親側 SurfaceView focus target を取得し、以後 key/text/IME を子へ転送します。Tab は親の次 focus target へ移動して子へ届かず、Escape は子が未消費なら親 overlay dismissal へ進みます。",
            Accessibility = new("埋め込み領域の見える見出しと操作説明を親側に置きます。", "SurfaceView も child semantic tree も親 `ISemanticProvider` tree へ公開しません。", "child focus、overlay、selection、error は子内に保持され、親 semantic 状態として公開しません。", "子 theme と親境界のコントラストを確認し、埋め込み面の境界を Border などで視覚化します。", "SurfaceView 自身の animation はありませんが、child host の animation は登録 surface が tick し続けます。reduced-motion は child 実装へ委ねます。", "親 Tab 順と child Tab 順は統合されず、支援技術から child controls を走査する契約もありません。代替の親操作を検討します。"),
            ThemeLayout = new("ChildTheme 未設定時は初回 child host 作成時に親 theme Signal を共有し、指定時はその Signal を使います。作成後に property 自体を差し替えても host signal は入れ替わりません。", "surfaceWidth/Height を最低 1 px として親制約へ収め、output は `ceil(requested size × RenderScale)` の物理解像度で確保します。", "親 image node は constrained Size で clip します。logicalWidth/Height は surface 以下へ上限 clamp し、未指定の後続 SetContent は以前の logical size を保持します。座標は display と child logical の間で scale しません。"),
            Constraints = new("child UI ごとに独立 canvas、host、render surface、device-local output を持つため、大量配置を避けます。変更のある frame だけ child raster を更新しますが child animations は tick を継続します。", "Widget removal は Dispose を呼びません。`Dispose` で surface 登録解除、child host/raster scene/canvas/buffer を解放します。ContentError 後は次の SetContent まで child tick を停止します。", "GPU composition host 専用です。初回 device/rasterizer を cache し、同一インスタンスを replacement device へ移行しません。dispose して再作成します。"),
            Api = new("SurfaceView", "`SetContent`、`Child`、`ChildTheme`、`ContentError`/`LastContentError`、`Dispose` と input bridge が主要 API です。", "child tick 例外は最初の一件を `ContentError` へ通知して保持します。SetContent は error を clear し、root reference または logical size の変更を child host へ反映します。"),
        },
        Page(
            "TableBlock",
            "Rendering",
            "TableBlock",
            "GFM pipe table のプレーン文字列セルを描画し、単一セル編集、IME、行列の追加削除、focus session 単位の commit を行う小規模な文書用 editable table です。",
            ["Markdown 文書内の小規模な表を直接編集し、payload snapshot を focus session ごとに commit する場合。", "日本語 IME を含む一行プレーン文字列セルと列 alignment を扱う場合。"],
            ["大量行、virtualization、列型、sorting/filtering、行選択、grid semantics、horizontal scrolling が必要な場合。", "Tab でセル内移動する spreadsheet 契約が必要な場合。通常 host では Tab は global focus traversal が先に消費します。"],
            "TableBlock(payload, maxWidth: 420, commit: updated => Save(updated))",
            "payload から初回に rows/aligns の local copy を作り、選択セルと TextEditor を TableBlock が保持します。通常編集は focus を失うと dirty payload を一度 commit し、呼び出し側が永続 model/undo を更新します。",
            "`payload`、`maxWidth`、`commit(Action<TablePayload>)` が固有入力です。TablePayload の `Rows[0]` は header、cells は v1 plain string です。",
            "pointer で cell/caret を選び、Left/Right/Home/End/Delete/Backspace、Up/Down、Enter、Escape と IME を扱います。right-click menu で row/column を追加削除します。Tab/Shift+Tab は UiHost が focus traversal に使うため通常は TableBlock の cell 移動へ届きません。",
            "header は SurfaceAlt、grid は BorderColor、selection/caret/IME target は Primary 系です。列は内容幅を測り、maxWidth 内で全列へ余剰配分または比例縮小します。",
            "全 cell を毎 refresh で描画し virtualize しません。Grid/Row/Cell semantics はなく、横 scroll と text clipping もありません。大規模・長文表には向きません。",
            "TableBlock",
            alternatives: [new("DataGrid", "大量行の仮想化、列見出し、行選択、grid semantics が必要な場合。"), new("TextArea", "表構造ではなく複数行テキストを編集する場合。")],
            keyboard:
            [
                new("`Left` / `Right`", "編集中セルの caret/selection を移動します。"),
                new("`Home` / `End`", "編集中セルの先頭または末尾へ移動します。"),
                new("`Up` / `Down`", "現在セルを local copy へ反映して同じ列の前後行へ移動します。"),
                new("`Enter`", "現在セルを反映して次の行へ移動し、最終行なら空行を追加します。"),
                new("`Backspace`", "通常は文字削除。header 以外の空行先頭ではその空行を削除します。"),
                new("`Delete`", "選択範囲または次の文字を削除します。"),
                new("`Escape`", "編集中セルを local copy の直前値へ戻します。session 全体の変更は取り消しません。"),
                new("`Tab` / `Shift+Tab`", "UiHost の global focus traversal が先に処理し、TableBlock から focus を移します。focus loss で dirty payload を commit します。"),
            ]
        ) with
        {
            Anatomy = "local row/align copy、選択 cell と TextEditor、header background、selection/IME layers、grid lines、全 cell text、caret、FocusTarget/ITextInput、context menu actions から構成します。",
            Variants = "列ごとの `TableAlign.None/Left/Center/Right`、payload 行列、maxWidth だけを扱います。typed cell、multi-line、read-only、disabled、virtualized variant はありません。",
            FocusActivationDismissal = "pointer drag-start で cell を選び focus を取得します。focus loss で current cell と dirty session を commit します。Escape は current cell の未反映 edit だけを戻し、context menu dismissal は host policy に従います。",
            Accessibility = new("表の目的を見出しで、各列の意味を header row の見える文字で示します。", "Grid、Row、GridCell、textbox の semantic role は公開しません。", "選択 cell、editing、dirty、row/column count を semantic 状態として公開しません。", "header、grid、selection、caret、IME underline、文字のテーマコントラストを確認します。", "caret は約 0.53 秒ごとに点滅し、reduced-motion 設定は参照しません。重要状態を点滅だけへ依存させません。", "支援技術向け表構造と keyboard spreadsheet navigation は保証されません。大量データやアクセシブルな表には DataGrid を選びます。"),
            ThemeLayout = new("Font/FontSm と SurfaceAlt、BorderColor、Text、TextMuted、Primary を host Theme から使います。", "各列は全 row の文字幅 + 16 px を測って最低 40 pxとし、合計が available より小さければ均等加算、大きければ比例縮小します。row height は font size の約 1.9 倍です。", "maxWidth は最低 80 pxで、有限親幅との小さい方が available です。text は cell 内で clip/ellipsis しないため、比例縮小後に長文が罫線外へ描かれ得ます。高さは全 row を実体化した合計です。"),
            Constraints = new("refresh は全 grid lines と全 cell text を再 encode し、列計測も全 cell を走査します。小規模文書表に限定し、長文・大量行では DataGrid を使います。", "local copy は同一 Widget 内に留まります。focus loss commit を受けた所有者が payload を保存/undo へ反映します。context menu の構造変更は即時 CommitIfDirty を呼びます。", "標準 focus/text/IME/context-menu host を使います。UiHost の Tab interception により内部 `case Key.Tab` は通常入力経路では到達しません。semantic platform adapter へ表構造は出ません。"),
            Api = new("TableBlock", "`TablePayload`、`maxWidth`、`commit`、`ITextInput`、row/column context actions が主要 API です。", "通常 edit は local copy に蓄積し focus loss で dirty payload を一度 commit します。context menu の構造変更は直後に commit し、callback がない場合は外部永続化しません。"),
        },
    ];
}
