using Luxel.Gallery;
using Luxel.Gallery.UI;

namespace Luxel.UI.Gallery;

internal static partial class UiControlDocs
{
    private static readonly ControlDocsPage[] CollectionsPages =
    [
        Page(
            "Accordion",
            "Collections",
            "Accordion",
            "見出しごとに内容を折りたたみ、長い設定や補足情報を段階的に開示します。",
            ["一つの補足領域を見出しから必要なときだけ開示する場合。"],
            ["展開で後続レイアウトを押し下げる必要がある場合や、項目コレクションを一つのインスタンスへ渡したい場合。"],
            "var expanded = new Signal<bool>(false);\nAccordion(\"詳細\", details, expanded: expanded)",
            "`expanded` を渡した場合は呼び出し側の `Signal<bool>` が開閉状態を所有します。未指定時は Widget の生存中だけ内部 Signal が状態を保持します。",
            "`title`、`content`、任意の `expanded`、`fontSize`、`background`、`foreground` が中心です。項目コレクションは受け取りません。",
            "見出し領域のポインター操作で `expanded` を切り替えます。フォーカス登録、キーボード操作、専用の支援技術メタデータは実装していません。",
            "ヘッダー高は 40 px で、背景色と文字色はテーマまたはパラメーターに従います。内容はヘッダー直下のクリップ領域で 0.25 秒かけてスライド表示されます。",
            "レイアウト上の `Size` はヘッダー高だけで、展開内容は下へオーバーフローします。展開時に後続の兄弟を再配置しないため、末尾配置や重なりを管理できるレイアウトで使います。",
            "Accordion",
            alternatives: [new("Stack", "常に表示する内容を通常の縦配置にします。")]
        ) with
        {
            Anatomy = "一つの 40 px ヘッダーと、その直下でクリップされる一つの content Widget から構成します。",
            Variants = "外部 `expanded` Signal を渡す制御形と、未指定時の内部状態形があります。背景、前景、文字サイズを指定できます。",
            FocusActivationDismissal = "ヘッダーは hit target ですが focus target ではありません。開閉はポインターだけで起動し、dismissal はありません。",
            Accessibility = new("`title` の見える文字列で目的を示します。", "専用の button/expanded semantic role は公開しません。", "展開状態を支援技術へ公開しません。重要内容へ別経路を用意します。", "ヘッダー文字と背景のコントラストをテーマで確認します。", "内容は 0.25 秒のスライドで表示されます。", "キーボードとスクリーンリーダーだけで開閉する契約はありません。"),
            Api = new("Accordion", "`title`、`content`、任意の `expanded`、`fontSize`、`background`、`foreground` が中心です。項目コレクションは受け取りません。", "固有イベントはなく、開閉結果は `expanded` Signal への書き戻しで観測します。"),
        },
        Page(
            "DataGrid",
            "Collections",
            "DataGrid",
            "列見出しを持つ行データを仮想化して表示し、選択と並べ替えを扱う表形式のコレクションビューです。",
            ["同じ列構造を持つ多数のレコードを比較し、行単位で選択・並べ替えする場合。"],
            ["自由編集できる表計算、可変高セル、カード状項目、階層表示が必要な場合。"],
            "var rows = new Signal<IReadOnlyList<DataGridRow>>([new(\"a\", [\"設定\", \"有効\"])]);\nDataGrid(items: rows, columns: [new DataGridColumn(\"name\", \"名前\", 180)], onSelect: (_, row) => Select(row.Key))",
            "items の Signal と行データの永続状態は呼び出し側が所有します。選択キー、フォーカス、スクロール位置は DataGrid が保持し、OnReorder は並べ替え要求だけを通知するため、呼び出し側で items を更新します。",
            "items、columns、height、rowHeight、OnSelect、OnReorder が中心です。AllowReorder を有効にする場合も、DataGridRow.Key と DataGridColumn.Key は安定した一意値にします。",
            "ポインターで行を選択し、Shift で範囲選択、Ctrl で追加・解除できます。Up/Down、Home/End、PageUp/PageDown で移動し、Space で選択します。無効行は移動と選択から除外され、SemanticRole.Grid、Row、GridCell を公開します。",
            "列幅は DataGridColumn.Width、表示高は height、行高は rowHeight で決まり、列幅は 24、行高は 18、見出し高は 22 を下回りません。色は UiTheme の Text、TextMuted、SurfaceAlt に追従し、親から有限幅を与えます。",
            "文字列セルの閲覧と行選択に特化し、セル編集、並べ替え規則、フィルター、横スクロールは提供しません。表示行だけを実体化します。ドラッグ並べ替えには UiHost が必要で、OnReorder 後のモデル更新は呼び出し側の責務です。",
            "DataGrid",
            alternatives: [new("GridView", "同じ大きさのカード状項目を複数列で表示します。")],
            keyboard: [new("`Up` / `Down`", "有効な行へフォーカスを移動します。"), new("`Home` / `End`", "先頭または末尾の有効行へ移動します。"), new("`PageUp` / `PageDown`", "表示ページ単位で移動します。"), new("`Space`", "フォーカス行を選択します。"), new("`Shift` / `Ctrl` + 選択", "範囲追加または選択の追加・解除を行います。")]
        ),
        Page(
            "DocumentTabs",
            "Collections",
            "DocumentTabs",
            "複数文書の切替、並べ替え、変更状態の表示に使うタブ列です。",
            ["文書の選択、変更状態、閉じる要求、並べ替えをタブ列で扱う場合。"],
            ["少数の静的な内容だけを切り替える場合や、アプリ全体を移動する場合。"],
            "DocumentTabs(tabs, active)",
            "文書一覧、選択中 ID、Dirty 状態は文書モデル側が所有します。",
            "DocTab 一覧、active、選択・閉じる・並べ替え通知が中心です。",
            "ポインターによる選択と並べ替えを扱います。キーボードや読み上げ対応は実装を確認し、代替の文書一覧を検討してください。",
            "利用可能幅に合わせて配置し、選択・Dirty 表示はテーマ色に従います。",
            "文書内容や保存処理は管理しません。タブを閉じる前の確認も呼び出し側の責任です。",
            "DocumentTabs",
            alternatives: [new("Tabs", "閉じる操作のない少数内容を切り替えます。")]
        ),
        Page(
            "GridView",
            "Collections",
            "GridView",
            "同じ大きさの項目を複数列へ仮想化して並べ、選択と並べ替えを扱うコレクションビューです。",
            ["同じ大きさの項目を複数列で走査・選択・並べ替えする場合。"],
            ["列ごとの意味比較、階層表示、項目ごとに異なる複雑なレイアウトが必要な場合。"],
            "var items = new Signal<IReadOnlyList<GridViewItem>>([new(\"a\", \"プロジェクト A\")]);\nGridView(items: items, itemWidth: 144, itemHeight: 80, onSelect: (_, item) => Open(item.Key))",
            "items の Signal と項目データは呼び出し側が所有します。選択キー、フォーカス、列数、スクロール位置は GridView が保持し、OnReorder を受けた呼び出し側が items の順序を更新します。",
            "items、height、itemWidth、itemHeight、OnSelect、OnReorder が中心です。AllowReorder を有効にすると同じ GridView 内のドラッグ要求を通知します。GridViewItem.Key は安定した一意値にします。",
            "ポインターで項目を選択し、Shift で範囲選択、Ctrl で追加・解除できます。Left/Right/Up/Down、Home/End で移動し、Space で選択します。無効項目は移動と選択から除外され、SemanticRole.Grid と GridCell を公開します。",
            "itemWidth は 48、itemHeight は 24 を下回らず、利用可能幅から列数を計算します。height で表示領域を固定し、UiTheme の Text、TextMuted、SurfaceAlt で文字と選択面を描画します。",
            "各項目は GridViewItem.Label の文字表示に限定され、任意の子 Widget、可変サイズ、画像描画は提供しません。表示セルだけを実体化します。ドラッグ並べ替えには UiHost が必要で、モデル変更は OnReorder の受信側が行います。",
            "GridView",
            alternatives: [new("DataGrid", "列の意味を揃えてレコードを比較します。")],
            keyboard: [new("矢印キー", "グリッド上の有効項目へ移動します。"), new("`Home` / `End`", "先頭または末尾の有効項目へ移動します。"), new("`Space`", "フォーカス項目を選択します。"), new("`Shift` / `Ctrl` + 選択", "範囲追加または選択の追加・解除を行います。")]
        ),
        Page(
            "ListView",
            "Collections",
            "ListView",
            "同種の項目を縦方向に表示し、選択や並べ替えを扱う一覧です。",
            ["同種の項目を縦一覧で仮想化し、選択や並べ替えを扱う場合。"],
            ["複数列の比較、階層表示、カード状の複数列配置が必要な場合。"],
            "ListView(items, selected)",
            "項目コレクションと選択状態は呼び出し側が所有します。並べ替え結果もモデルへ反映します。",
            "items、itemBuilder、selected、選択・並べ替え通知が中心です。",
            "ポインター選択と構成に応じた並べ替えを扱います。キーボード一覧操作と支援技術意味は保証されないため代替操作を検討します。",
            "行高、選択色、区切り、幅をテーマと親レイアウトで統一します。",
            "大量データでの仮想化可否を確認してください。項目 ID を安定させないと再構築時に選択対応が崩れます。",
            "ListView",
            alternatives: [new("TreeView", "階層データを展開・折りたたみします。")],
            related: [new("Controls/Collections/ListView/Examples/Reorder", "並べ替え", "ドラッグ並べ替え要求と外部モデル更新を確認します。", StoryKind.Example)]
        ),
        Page(
            "NavigationView",
            "Collections",
            "NavigationView",
            "画面の主要領域を切り替えるナビゲーションと内容領域を構成します。",
            ["アプリケーションの主要領域を安定した目的地として切り替える場合。"],
            ["同じ文脈内の少数内容や、開いている文書を切り替える場合。"],
            "NavigationView(items, selected, content)",
            "項目一覧と選択 ID はアプリケーション状態として上位が所有します。",
            "項目、selected、内容生成、選択通知が中心です。",
            "ポインター選択を扱います。現在位置を文字でも示し、キーボード移動と読み上げは対象ホストで検証してください。",
            "利用幅に応じたナビゲーション領域と内容領域を設計し、選択色はテーマへ追従させます。",
            "ルーティング、履歴、権限管理は自動ではありません。項目 ID を安定させます。",
            "NavigationView",
            alternatives: [new("Tabs", "同じ文脈内の内容を切り替えます。")]
        ),
        Page(
            "ScrollViewer",
            "Collections",
            "Scroll",
            "利用領域を超える一つの子要素をスクロール表示します。",
            ["一つの子要素が利用領域を超えるため、任意位置までスクロールさせる場合。"],
            ["大量項目の仮想化が必要な場合や、入れ子のスクロール領域を作る場合。"],
            "Scroll(child, height: 320)",
            "スクロール位置はビューが保持し、内容モデルは呼び出し側が所有します。",
            "child、幅・高さ、スクロール方向などが中心です。",
            "ホイールやポインター入力を扱います。キーボードスクロール、フォーカス追従、読み上げ順はホストで確認してください。",
            "少なくとも一方向の表示寸法を制約し、スクロール可能であることを視覚的に示します。",
            "無制約の入れ子スクロールは操作性を損ないます。再生成時の位置保持は Widget 寿命に依存します。",
            "ScrollViewer",
            alternatives: [new("ListView", "大量の同種項目を仮想化します。")]
        ),
        Page(
            "TabStrip",
            "Collections",
            "TabStrip",
            "文書や作業対象を横一列で切り替え、変更マーカー、Badge、閉じる操作、ドラッグ移動、オーバーフローを扱うタブ列です。",
            ["複数文書や編集対象を切り替え、閉じる操作、変更状態、並べ替えを同じ列で扱う場合。"],
            ["単純な内容切替、アプリ全体の移動、主要ページを過剰に詰め込む場合。"],
            "TabStrip(items: tabs, selectedKey: activeKey,\n    onSelect: (_, key) => Select(key), onCloseRequest: (_, key) => Close(key))",
            "items と selectedKey の正本は呼び出し側が所有します。TabStrip はフォーカス、横方向の ScrollOffset、OverflowCount を保持し、OnSelect、OnCloseRequest、OnDropRequest は要求だけを通知するため、選択・削除・並べ替え結果をモデルへ反映します。",
            "items、selectedKey、dragChannel、OnSelect、OnCloseRequest、OnDropRequest が中心です。TabStripItem は Key、Title、Marker、Badge、Tooltip、Closable、Disabled を持ち、同じ dragChannel の TabStrip 間でドロップを受け付けます。",
            "ポインターで選択・閉じる・ドラッグし、ホイールまたはオーバーフロー操作で隠れたタブへ移動します。Left/Right は有効タブ間を循環し、Home/End、Enter/Space、Delete に対応します。SemanticRole.TabList と Tab を公開し、無効タブを移動対象から除外します。",
            "高さは 32、各タブ幅は 64〜190、オーバーフロー領域は 28 を基準にします。選択面と下線は SurfaceAlt と Primary、通常・無効文字は TextMuted に追従します。親から有限幅を与え、Tooltip と Marker もテーマ色へ合わせます。",
            "TabStripItem.Key は空にできず重複も許されません。長い Title は最大幅で切られ、オーバーフロー操作は一覧メニューではなく表示位置を進めます。ドラッグ/ドロップ には UiHost と一致する dragChannel が必要で、閉じる操作やドロップ後のデータ変更は呼び出し側の責務です。",
            "TabStrip",
            alternatives: [new("Tabs", "閉じる・並べ替えのない少数内容を切り替えます。")],
            keyboard: [new("`Left` / `Right`", "有効なタブ間を循環します。"), new("`Home` / `End`", "先頭または末尾の有効タブへ移動します。"), new("`Enter` / `Space`", "フォーカス中のタブを選択します。"), new("`Delete`", "閉じる要求を通知します。")]
        ),
        Page(
            "Tabs",
            "Collections",
            "Tabs",
            "同じ文脈内の少数の表示内容をタブで切り替えます。",
            ["同じ文脈内にある少数の内容を、閉じる操作なしで切り替える場合。"],
            ["文書の変更状態・閉鎖・並べ替え、またはアプリ全体の目的地移動を扱う場合。"],
            "Tabs(items, selected)",
            "選択値の Signal と各内容の状態は呼び出し側が所有します。",
            "項目、selected、内容、選択通知が中心です。",
            "ポインターで選択します。タブ順と内容の対応を明確にし、キーボード移動と読み上げは対象ホストで検証します。",
            "選択状態を色だけでなく形でも示し、内容領域との境界をテーマで整えます。",
            "多数項目や主要ルーティングには不向きです。非表示内容の保持可否は構築方法に依存します。",
            "Tabs",
            alternatives: [new("TabStrip", "文書の閉じる要求、変更状態、並べ替えを扱います。")]
        ),
        Page(
            "TreeView",
            "Collections",
            "TreeView",
            "階層データを展開・折りたたみしながら表示・選択します。",
            ["親子関係を持つ階層データを展開・折りたたみしながら選択する場合。"],
            ["平坦な一覧、列比較、自由なグラフ接続を表示する場合。"],
            "TreeView(nodes, selected)",
            "ノードモデル、展開状態、選択状態の永続化範囲を呼び出し側で決めます。",
            "nodes、children、selected、展開・選択通知が中心です。",
            "ポインターで展開と選択を行います。キーボード階層移動と支援技術意味は保証されないため、必要なら検索や平坦な一覧を併設します。",
            "深さをインデントで示し、選択・展開記号をテーマで明瞭にします。",
            "巨大階層の仮想化、循環検出、遅延ロードはモデル側の設計に依存します。ノード ID を安定させます。",
            "TreeView",
            alternatives: [new("ListView", "平坦な同種項目を一覧表示します。")]
        ),
    ];
}
