<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Luxel\Luxel.csproj" />
    <ProjectReference Include="..\Luxel.Animation\Luxel.Animation.csproj" />
    <ProjectReference Include="..\Luxel.Ecs\Luxel.Ecs.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
