const nav=document.querySelector('#stories'),content=document.querySelector('#content'),search=document.querySelector('#search'),theme=document.querySelector('#theme');
const sidebar=document.querySelector('#sidebar'),sidebarToggle=document.querySelector('#sidebar-toggle'),reviewPanel=document.querySelector('#review-panel'),reviewToggle=document.querySelector('#review-toggle'),reviewClose=document.querySelector('#review-close');
const reviewStatus=document.querySelector('#review-status'),reviewComment=document.querySelector('#review-comment'),reviewSaveState=document.querySelector('#review-save-state'),reviewFallback=document.querySelector('#review-export-fallback');
let stories=[],activeReviewPath=null,storageAvailable=true;
const languageAliases={slang:'cpp',hlsl:'cpp',powershell:'shell',pwsh:'shell',csharp:'cs'},openKey='luxel-gallery-tree-open',reviewKey='luxel-gallery-review:v1:'+location.pathname,reviewUiKey='luxel-gallery-review-ui:'+location.pathname,sidebarUiKey='luxel-gallery-sidebar-ui:'+location.pathname;
function highlight(root){if(typeof hljs==='undefined')return;for(const code of root.querySelectorAll('pre code')){const match=[...code.classList].find(x=>x.startsWith('language-'));const requested=match?.slice(9).toLowerCase();const language=languageAliases[requested]||requested;if(language&&hljs.getLanguage(language)){if(match)code.classList.replace(match,'language-'+language)}else if(requested){code.classList.add('no-highlight')}hljs.highlightElement(code)}}
const route=()=>{const p=new URLSearchParams(location.hash.slice(1));return{story:p.get('story')||stories[0]?.path,section:p.get('section')}};
const key=()=>route().story;
const storyHash=path=>'#story='+encodeURIComponent(path);
function safeGet(name){try{return localStorage.getItem(name)}catch{storageAvailable=false;return null}}
function safeSet(name,value){try{localStorage.setItem(name,value);return true}catch{storageAvailable=false;reviewSaveState.textContent='保存できません。コピーまたはJSONバックアップを利用してください。';reviewSaveState.classList.add('error');return false}}
function savedOpen(){try{return new Set(JSON.parse(safeGet(openKey)||'[]'))}catch{return new Set}}
function hasSavedOpen(){return safeGet(openKey)!==null}
function saveOpen(){const paths=[...nav.querySelectorAll('details.tree-folder[open]')].map(x=>x.dataset.path);safeSet(openKey,JSON.stringify(paths))}
function treeFor(items){const root={children:new Map(),story:null};for(const story of items){let node=root;for(const part of story.path.split('/')){if(!node.children.has(part))node.children.set(part,{children:new Map(),story:null});node=node.children.get(part)}node.story=story}return root}
function renderLevel(node,prefix,open,expandAll){const list=document.createElement('ul');list.className='tree-level';for(const [name,child] of node.children){const path=prefix?prefix+'/'+name:name;const item=document.createElement('li');if(child.children.size){const details=document.createElement('details');details.className='tree-folder';details.dataset.path=path;details.open=expandAll||open.has(path)||(!hasSavedOpen()&&!prefix);const summary=document.createElement('summary');summary.textContent=name;details.append(summary,renderLevel(child,path,open,expandAll));if(!expandAll)details.addEventListener('toggle',saveOpen);if(child.story){const own=document.createElement('a');own.href=storyHash(child.story.path);own.dataset.path=child.story.path;own.textContent=name+' — overview';details.prepend(own)}item.append(details)}else if(child.story){const a=document.createElement('a');a.href=storyHash(child.story.path);a.dataset.path=child.story.path;a.textContent=name;item.append(a)}list.append(item)}return list}
function reveal(path){const parts=path.split('/');for(let i=1;i<parts.length;i++){const folder=nav.querySelector('details.tree-folder[data-path="'+CSS.escape(parts.slice(0,i).join('/'))+'"]');if(folder)folder.open=true}}
function setActive(path){for(const a of nav.querySelectorAll('a[data-path]')){const active=a.dataset.path===path;a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')}}
function emptyReviewStore(){return{version:1,stories:{}}}
function readReviewStore(){try{const parsed=JSON.parse(safeGet(reviewKey)||'null');return parsed?.version===1&&parsed.stories?parsed:emptyReviewStore()}catch{return emptyReviewStore()}}
function writeReviewStore(store){return safeSet(reviewKey,JSON.stringify(store))}
function currentStoryUrl(path){return location.href.split('#')[0]+storyHash(path)}
function saveCurrentReview(){if(!activeReviewPath)return;const store=readReviewStore(),comment=reviewComment.value,status=reviewStatus.value;if(!comment.trim()&&status==='unchecked')delete store.stories[activeReviewPath];else store.stories[activeReviewPath]={status,comment,url:currentStoryUrl(activeReviewPath),updatedAt:new Date().toISOString()};if(writeReviewStore(store)){reviewSaveState.textContent='この端末に保存しました · '+new Date().toLocaleTimeString();reviewSaveState.classList.remove('error')}updateReviewCounts()}
function loadReview(path){activeReviewPath=path;const note=readReviewStore().stories[path];reviewStatus.value=note?.status||'unchecked';reviewComment.value=note?.comment||'';reviewSaveState.textContent=storageAvailable?'':'保存できません。コピーまたはJSONバックアップを利用してください。';updateReviewCounts()}
function annotatedStories(){const notes=readReviewStore().stories;return stories.filter(story=>notes[story.path]&&(notes[story.path].comment.trim()||notes[story.path].status!=='unchecked'))}
function updateReviewCounts(){const count=annotatedStories().length;reviewToggle.textContent=count?'フィードバック ('+count+')':'フィードバック'}
function navigateAnnotated(delta){saveCurrentReview();const items=annotatedStories();if(!items.length)return;let index=items.findIndex(x=>x.path===activeReviewPath);if(index<0)index=delta>0?-1:0;location.hash=storyHash(items[(index+delta+items.length)%items.length].path)}
function statusLabel(status){return status==='reviewed'?'確認済み':status==='needs-change'?'要修正':'未確認'}
function reviewMarkdown(){saveCurrentReview();const store=readReviewStore(),items=stories.filter(x=>store.stories[x.path]);const lines=['# Luxel Gallery feedback','',`Gallery: ${location.href.split('#')[0]}`,''];for(const story of items){const note=store.stories[story.path];if(!note.comment.trim()&&note.status==='unchecked')continue;lines.push('## '+story.path,'',`- 状態: ${statusLabel(note.status)}`,`- URL: ${note.url||currentStoryUrl(story.path)}`,'',note.comment.trim()||'（コメントなし）','')}if(lines.length===4)lines.push('フィードバックはまだありません。','');return lines.join('\n')}
function download(name,text,type){const blob=new Blob([text],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),0)}
async function copyReviews(){const markdown=reviewMarkdown();try{await navigator.clipboard.writeText(markdown);reviewSaveState.textContent='全フィードバックをコピーしました。';reviewFallback.hidden=true}catch{reviewFallback.value=markdown;reviewFallback.hidden=false;reviewFallback.focus();reviewFallback.select();reviewSaveState.textContent='自動コピーできないため、下の欄を選択しました。'}}
function openIssue(){saveCurrentReview();const note=readReviewStore().stories[activeReviewPath]||{status:'unchecked',comment:''};const title='Gallery feedback: '+activeReviewPath;const body=['## Story','',activeReviewPath,'','## Status','',statusLabel(note.status),'','## Gallery URL','',currentStoryUrl(activeReviewPath),'','## Feedback','',note.comment.trim()||'（コメントを記入してください）'].join('\n');open('https://github.com/ikihiki/luxel/issues/new?title='+encodeURIComponent(title)+'&body='+encodeURIComponent(body),'_blank','noopener')}
function syncVisualViewport(){const viewport=window.visualViewport,height=viewport?.height||innerHeight,offset=viewport?.offsetTop||0,inset=Math.max(0,document.documentElement.clientHeight-height-offset);document.documentElement.style.setProperty('--visual-viewport-height',height+'px');document.documentElement.style.setProperty('--keyboard-inset',inset+'px')}function setReviewOpen(open){document.body.classList.toggle('review-open',open);reviewToggle.setAttribute('aria-expanded',String(open));reviewPanel.setAttribute('aria-hidden',String(!open));safeSet(reviewUiKey,open?'open':'closed');if(!open&&reviewPanel.contains(document.activeElement))reviewToggle.focus()}
function setSidebarOpen(open){document.body.classList.toggle('sidebar-collapsed',!open);sidebarToggle.setAttribute('aria-expanded',String(open));sidebar.setAttribute('aria-hidden',String(!open));safeSet(sidebarUiKey,open?'open':'closed')}
async function show(){saveCurrentReview();const requested=key();const s=stories.find(x=>x.path===requested||(x.aliases||[]).includes(requested))||stories[0];if(!s)return;const r=await fetch(s.fragment);content.innerHTML=r.ok?await r.text():'<p>ページを読み込めませんでした。</p>';highlight(content);setActive(s.path);reveal(s.path);loadReview(s.path);document.title=s.path+' — Luxel Gallery';const section=route().section;if(section)requestAnimationFrame(()=>document.getElementById(section)?.scrollIntoView());else content.scrollTo?.(0,0);if(matchMedia('(max-width: 1180px)').matches)setSidebarOpen(false)}
function draw(q=''){nav.innerHTML='';const needle=q.trim().toLowerCase();const filtered=stories.filter(x=>(x.searchText||x.path).toLowerCase().includes(needle));nav.append(renderLevel(treeFor(filtered),'',savedOpen(),needle.length>0));const current=key();if(current){setActive(current);reveal(current)}}
const saved=safeGet('luxel-gallery-theme');if(saved==='light')document.documentElement.dataset.theme='light';
theme.addEventListener('click',()=>{const light=document.documentElement.dataset.theme!=='light';document.documentElement.dataset.theme=light?'light':'';safeSet('luxel-gallery-theme',light?'light':'dark')});
sidebarToggle.addEventListener('click',()=>setSidebarOpen(document.body.classList.contains('sidebar-collapsed')));reviewToggle.addEventListener('click',()=>setReviewOpen(!document.body.classList.contains('review-open')));reviewClose.addEventListener('click',()=>setReviewOpen(false));
reviewComment.addEventListener('input',saveCurrentReview);reviewComment.addEventListener('focus',()=>{document.body.classList.add('review-keyboard');syncVisualViewport()});reviewComment.addEventListener('blur',()=>{document.body.classList.remove('review-keyboard');syncVisualViewport()});reviewStatus.addEventListener('change',saveCurrentReview);document.querySelector('#review-prev').addEventListener('click',()=>navigateAnnotated(-1));document.querySelector('#review-next').addEventListener('click',()=>navigateAnnotated(1));document.querySelector('#review-copy').addEventListener('click',copyReviews);document.querySelector('#review-download-md').addEventListener('click',()=>download('luxel-gallery-feedback.md',reviewMarkdown(),'text/markdown;charset=utf-8'));document.querySelector('#review-download-json').addEventListener('click',()=>{saveCurrentReview();download('luxel-gallery-feedback.json',JSON.stringify(readReviewStore(),null,2)+'\n','application/json')});document.querySelector('#review-issue').addEventListener('click',openIssue);
document.querySelector('#review-import').addEventListener('change',async event=>{const file=event.target.files?.[0];if(!file)return;try{const data=JSON.parse(await file.text());if(data?.version!==1||!data.stories||Array.isArray(data.stories))throw new Error('invalid');if(!writeReviewStore(data))return;loadReview(activeReviewPath);reviewSaveState.textContent='JSONバックアップを復元しました。'}catch{reviewSaveState.textContent='このJSONバックアップは復元できません。';reviewSaveState.classList.add('error')}finally{event.target.value=''}});
addEventListener('pagehide',saveCurrentReview);addEventListener('hashchange',show);addEventListener('resize',syncVisualViewport);window.visualViewport?.addEventListener('resize',syncVisualViewport);window.visualViewport?.addEventListener('scroll',syncVisualViewport);search.addEventListener('input',()=>draw(search.value));
syncVisualViewport();const initialReview=safeGet(reviewUiKey),initialSidebar=safeGet(sidebarUiKey);setReviewOpen(initialReview?initialReview==='open':matchMedia('(orientation: landscape) and (min-width: 800px)').matches);setSidebarOpen(initialSidebar?initialSidebar==='open':!matchMedia('(max-width: 1180px)').matches);
fetch('manifest.json').then(r=>r.json()).then(x=>{stories=x;draw();show()}).catch(()=>content.innerHTML='<p>manifest.jsonを読み込めませんでした。</p>');