<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <LuxelProjectRole>Production</LuxelProjectRole>
    <LuxelGalleryCategory>External</LuxelGalleryCategory>
    <LuxelSubsystem>ValueDocument</LuxelSubsystem>
    <LuxelPlatform>Portable</LuxelPlatform>
    <LuxelArchitectureTier>Foundation</LuxelArchitectureTier>
  </PropertyGroup>
</Project>
