<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Luxel.Graphics\Luxel.Graphics.csproj" />
    <ProjectReference Include="..\Luxel\Luxel.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Luxel.Tests" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Luxel.Graphics" />
  </ItemGroup>
</Project>
