<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.12.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Luxel.Scripting\Luxel.Scripting.csproj" />
    <ProjectReference Include="..\Luxel.UI\Luxel.UI.csproj" />
    <ProjectReference Include="..\Luxel.Controls\Luxel.Controls.csproj" />
  </ItemGroup>
</Project>
