<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Luxel.Scripting\Luxel.Scripting.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="wwwroot\luxel-playground.css" />
    <EmbeddedResource Include="wwwroot\luxel-playground.js" />
    <None Update="wwwroot\luxel-playground.css" CopyToOutputDirectory="PreserveNewest" Pack="true" PackagePath="wwwroot\luxel-playground.css" />
    <None Update="wwwroot\luxel-playground.js" CopyToOutputDirectory="PreserveNewest" Pack="true" PackagePath="wwwroot\luxel-playground.js" />
  </ItemGroup>
</Project>
