<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Luxel.Platform.Windows\Luxel.Platform.Windows.csproj" />
    <ProjectReference Include="..\Luxel.Graphics\Luxel.Graphics.csproj" />
    <ProjectReference Include="..\Luxel\Luxel.csproj" />
    <ProjectReference Include="..\Luxel.TwoD\Luxel.TwoD.csproj" />
    <ProjectReference Include="..\Luxel.UI\Luxel.UI.csproj" />
    <ProjectReference Include="..\Luxel.Controls\Luxel.Controls.csproj" />
    <ProjectReference Include="..\Luxel.Platform\Luxel.Platform.csproj" />
    <ProjectReference Include="..\Luxel.DevTools\Luxel.DevTools.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Luxel.Graphics" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Luxel.Platform" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Luxel.Platform.Windows" />
  </ItemGroup>
</Project>
