using Luxel.Gallery.UI;

namespace Luxel.Editor.Gallery;

internal static partial class EditorControlDocs
{
    private static readonly ControlDocsPage[] Pages =
    [
        Page(
            "AssetBrowser",
            "Collections",
            "プロジェクト内の資産を階層・一覧で探し、選択や起動へつなぐブラウザーです。ファイル管理画面や素材選択に使います。",
            "プロジェクトのフォルダーと資産を一つの pane で検索・選択・起動・変更する場合。",
            "汎用ファイルシステム UI、権限管理、巨大データセットの検索基盤そのものとして使う場合。",
            "AssetBrowser(storage, operations: operations, expanded: expanded)",
            "資産ツリー、選択、現在位置、フィルター、読み込み結果は AssetBrowserModel と外部 storage が分担します。永続状態の正本は Editor session 側に置きます。",
            "`storage`、`operations`、`filter`、`expanded` と、開く・インポート・reveal・mutation の通知が中心です。",
            "ポインターによる選択、フォルダー移動、項目起動、表示モード切替を扱います。キーボード一覧操作と完全な階層 semantics は保証しないため、検索やパス操作の代替経路を用意します。",
            "エディターの表面色、選択色、アイコン尺度に合わせます。一覧とツリーを確認できる十分な幅と高さを与えます。",
            "資産の監視、インポート、権限、競合、巨大一覧の性能は storage と IAssetOperations の構成に依存します。購読とサービスの寿命を Editor session に合わせます。",
            [new("TreeView", "読み取り専用に近い一般的な階層選択を表示します。"), new("GridView", "平坦な同サイズ資産をカード状に表示します。")]),
        Page(
            "DockHost",
            "Editor",
            "複数のツール・文書パネルを分割、移動、フロート、再ドックできる作業領域です。エディターの主シェルに使います。",
            "文書やツール pane を永続的な DockTree として分割・移動・フロートする場合。",
            "二領域の単純な比率変更だけでよい場合や、一時的な補助パネルを重ねる場合。",
            "DockHost(tree, ResolveItem, closeRemoves: false)",
            "DockTree、選択、分割比率、フロート位置は Workbench 側の Signal が正本です。DockHost は生成済み子ビューをタブ切替やレイアウト変更の間キャッシュします。",
            "`tree`、`resolve`、`closeRemoves`、`hideSingleTabStrip`、タブ表示指定、`OnCloseTab` が中心です。",
            "タブ選択、ドラッグ移動、スプリッター調整、フロート操作を扱います。完全なキーボードドッキングや支援技術表現は提供しないため、配置リセットやメニュー操作を代替として用意します。",
            "アプリ全体の作業領域を明示します。ドロップ候補、選択タブ、境界をエディターテーマで区別します。",
            "レイアウトの妥当性、最小寸法、保存形式の移行、画面外フロートの回収は呼び出し側の責任です。DockTree から消えた子ビューは破棄されます。",
            [new("Splitter", "隣接する二領域の比率だけをドラッグ調整します。"), new("Drawer", "一時的な補助 pane を右端へ重ねます。")]),
        Page(
            "EditorShell",
            "Editor",
            "MenuBar、Toolbar、DocumentTabs、DockHost、Dialog、StatusBar を EditorSession の周囲に構成する portable なエディターシェルです。",
            "一つの EditorSession を Browser、Native、Gallery fixture で共通のアプリケーション chrome に載せる場合。",
            "個別 pane だけを埋め込む場合や、EditorSession を使わない独自アプリケーション shell を構成する場合。",
            "EditorKit.EditorShell(session, productName: \"Luxel Editor\")",
            "EditorSession がコマンド、設定、workspace、document、dock layout、autosave の正本を所有します。EditorShell は一時的な Toolbar 参照、子 surface、system theme を保持します。",
            "`session` と `productName` が固有パラメーターです。文書タブと DockHost は `DocumentTabs`、`DocumentsHost` として検査できます。",
            "MenuBar と Toolbar からコマンドを起動し、DocumentTabs と DockHost で文書を切り替えます。session の keymap は UiHost へ binding されます。",
            "五段の Grid で menu、toolbar、document tabs、documents/dialogs、status bar を並べます。設定の theme を UiHost theme へ同期します。",
            "EditorSession と子サービスが必要です。autosave pump と command shortcut binding は実体化スコープへ所有され、session の破棄責任は composition root にあります。",
            [new("DockHost", "既存 session の作業 pane だけを表示します。"), new("MenuBar", "コマンドメニューだけを独立して表示します。")]),
        Page(
            "MenuBar",
            "Overlay",
            "CommandRegistry から主要コマンドを階層メニューとして表示します。アプリ全体で安定した操作の入口に使います。",
            "アプリケーション全体の主要コマンドを安定した階層メニューとして公開する場合。",
            "頻繁な少数操作だけを並べる場合や、検索してコマンドを発見する入口が必要な場合。",
            "MenuBar(registry, contributions: () => activeContributions)",
            "コマンド定義、有効状態、gesture、実行処理は CommandRegistry が単一の真実として所有し、MenuBar は contribution を合成した投影になります。",
            "`registry` と `contributions` が固有パラメーターです。ルートラベルから ContextMenu を開き、登録済み Command を実行します。",
            "ポインターでルートメニューを開き項目を実行します。表示する gesture と実際の Keymap を一致させ、キーボードメニュー操作と読み上げは対象ホストで検証します。",
            "画面上端へ配置し、メニュー面、hover 行、無効状態をエディターテーマで示します。バー高は 30 px です。",
            "コマンドそのもの、Undo、権限、エラー表示は管理しません。CommandRegistry と contribution provider の寿命を Editor session に合わせます。",
            [new("Toolbar", "頻繁な少数コマンドを常時表示します。")]),
        Page(
            "SceneEditorView",
            "Editor",
            "シーンの表示、選択、編集ツールをまとめるエディタービューです。ゲームや可視化シーンの作業領域に使います。",
            "SceneDoc のエンティティ選択、移動、複製、削除、2D/3D adapter 経由の編集を一つの viewport で行う場合。",
            "プロパティだけを編集する場合や、完全なキーボード・支援技術経路が必須のデータ編集に使う場合。",
            "SceneEditorView(source: scene, viewWidth: 620, viewHeight: 360)",
            "SceneEditState と SceneHistory はビューが保持し、保存状態と document lifecycle は Editor document 側が所有します。選択と編集は公開 callback で周囲へ同期します。",
            "`source`、`viewWidth`、`viewHeight`、Adapter、Tool、SnapToGrid、OnSelectionChanged、OnEdit が中心です。",
            "viewport 上の選択、移動、marquee、pan、描画ツールを扱います。操作体系は adapter と tool に依存し、完全なキーボード操作や支援技術表現は提供しません。Hierarchy と Inspector を代替経路にします。",
            "大きな表示領域を与えます。選択輪郭、grid、handle、scene content をテーマと scene の双方に対して見分けやすくします。",
            "scene space adapter と描画資源が必要です。保存、外部競合、実行中 scene との同期、document 資源破棄は Editor host 側の責任です。",
            [new("SceneInspector", "現在選択の component field をスキーマ経由で編集します。")]),
        Page(
            "SceneInspector",
            "Editor",
            "SceneEditorView の主選択エンティティにある component をスキーマ経由で表示・編集するインスペクターです。",
            "SceneEditorView の現在選択を component schema に従って編集し、変更を同じ undo transaction 経路へ送る場合。",
            "任意 CLR object の reflection property を編集する場合や、scene 選択と無関係なフォームを作る場合。",
            "SceneInspector(editor: sceneEditor, schemas: SceneSchemas.BuiltIns(), width: 260)",
            "選択、SceneDoc、確定値、undo history は接続した SceneEditorView が所有します。SceneInspector は schema から editor を構成し、ApplyEdit を通じて変更します。",
            "`editor`、`schemas`、`width` と、component 追加・削除 helper が中心です。",
            "各 schema field editor の操作に従います。ラベル、単位、検証結果を明示し、キーボード移動と支援技術対応は組み込む入力ごとに検証します。",
            "ラベル列、値列、section、error 色を他の property pane と統一します。狭すぎて値が読めない幅を避けます。",
            "複数選択の混在値や schema 外 field の編集は提供しません。編集は SceneEditorView の transaction 経路を外さず、選択解除時の draft 扱いを確認します。",
            [new("PropertyGrid", "一般 CLR object の property を reflection ベースで編集します。")]),
        Page(
            "Toolbar",
            "Overlay",
            "CommandRegistry の toolbar contribution を短いラベルの操作列として表示するコマンドビューです。",
            "CommandRegistry で toolbar 対象になった頻繁な少数コマンドを常時表示する場合。",
            "全コマンドの発見、階層メニュー、検索、履歴を一つの面で提供する場合。",
            "Toolbar(registry, contributions: () => activeContributions)",
            "コマンド定義、有効状態、実行処理は CommandRegistry が所有し、Toolbar は toolbar contribution を投影します。Refresh で enablement を再評価します。",
            "`registry` と `contributions` が固有パラメーターです。有効な command は Button、無効な command は muted Text として表示します。",
            "有効な command はポインターで起動します。Keymap がある場合は別経路の表示と一致させ、専用の toolbar keyboard navigation や読み上げ意味は前提にしません。",
            "エディターの文字尺度、ghost button、無効色に合わせ、関連操作を短い間隔で横並びにします。",
            "コマンド検索、履歴、権限、非同期進捗は管理しません。CommandRegistry の version と EditorShell の Refresh 呼び出しに追従します。",
            [new("MenuBar", "階層化した主要コマンドを安定した入口として表示します。")]),
    ];
}
