using Microsoft.AspNetCore.Components.WebAssembly.Hosting;
using Luxel.Gallery;
using Luxel.Resources.Gallery;
using Luxel.Audio.Gallery;
using Luxel.UI.Gallery;
using Luxel.Graphics.Gallery;
using Luxel.Input.Gallery;
using Luxel.Framework.Gallery;
using Luxel.Animation.Gallery;
using Luxel.Particles.Gallery;
using Luxel.Scripting.Gallery;
using Luxel.Gallery.Playground;
using Luxel.Controls;
using Luxel.Settings;
using Luxel.Editor.Gallery;
using Luxel.DevTools.Gallery;
using Luxel.GamesSamples.Gallery;
using Luxel.Gallery.Docs;
using GalleryBrowser;

WebAssemblyHostBuilder builder = WebAssemblyHostBuilder.CreateDefault(args);
builder.RootComponents.Add<App>("#app");
var http = new HttpClient { BaseAddress = new Uri(builder.HostEnvironment.BaseAddress) };
builder.Services.AddSingleton(http);
var scripting = new BrowserRoslynGalleryRuntime(await BrowserRoslynGalleryRuntime.LoadReferencesAsync(http));
builder.Services.AddSingleton(scripting);
builder.Services.AddSingleton<ICodeLanguage>(scripting.Language);
builder.Services.AddSingleton<INativePlaygroundRunner>(scripting.Playground);
builder.Services.AddSingleton<IFileStore, InMemoryFileStore>();
builder.Services.AddResourceGallery();
builder.Services.AddAudioGallery();
builder.Services.AddUiGallery();
builder.Services.AddGraphicsGallery();
builder.Services.AddInputGallery();
builder.Services.AddFrameworkGallery();
builder.Services.AddAnimationGallery();
builder.Services.AddParticlesGallery();
builder.Services.AddScriptingGallery();
builder.Services.AddEditorGallery();
builder.Services.AddDevToolsGallery();
builder.Services.AddGamesSamplesGallery();
builder.Services.AddGalleryDocs();
await builder.Build().RunAsync();
