using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace Luxel.UI.Generators;

/// <summary>
/// <c>[assembly: Luxel.UI.GenerateAssemblyApi("Luxel.TwoD")]</c> の opt-in で、**参照アセンブリの
/// 公開型 API を XML doc コメントごと焼き込む** (TypeApiRegistry.Register の module initializer)。
/// docs の型 API リファレンス (Docs/Api2D 等) が実行時にページを組み立てる — reflection なし、
/// 手書き一覧なし。対象アセンブリは GenerateDocumentationFile=true が必要 (無いと説明が空になる)。
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class AssemblyApiGenerator : IIncrementalGenerator
{
    private static readonly SymbolDisplayFormat Short = new(
        typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameOnly,
        genericsOptions: SymbolDisplayGenericsOptions.IncludeTypeParameters,
        miscellaneousOptions: SymbolDisplayMiscellaneousOptions.UseSpecialTypes);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var source = context.CompilationProvider.Select(static (c, ct) => Collect(c, ct));
        context.RegisterSourceOutput(source, static (spc, text) =>
        {
            if (text is not null) spc.AddSource("AssemblyApi.g.cs", text);
        });
    }

    private static string? Collect(Compilation compilation, System.Threading.CancellationToken ct)
    {
        var targets = new List<string>();
        foreach (AttributeData a in compilation.Assembly.GetAttributes())
            if (a.AttributeClass?.ToDisplayString() == "Luxel.UI.GenerateAssemblyApiAttribute"
                && a.ConstructorArguments.Length == 1 && a.ConstructorArguments[0].Value is string ns)
                targets.Add(ns);
        if (targets.Count == 0) return null;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/> Luxel.UI.Generators.AssemblyApiGenerator");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("namespace Luxel.UI.Generated");
        sb.AppendLine("{");
        sb.Append("    internal static class AssemblyApiRegistration_")
          .AppendLine(StoryGenerator.Sanitize(compilation.AssemblyName ?? "Assembly"));
        sb.AppendLine("    {");
        sb.AppendLine("        [global::System.Runtime.CompilerServices.ModuleInitializer]");
        sb.AppendLine("        internal static void Init()");
        sb.AppendLine("        {");

        foreach (string ns in targets)
        foreach (IAssemblySymbol asm in compilation.SourceModule.ReferencedAssemblySymbols)
        {
            ct.ThrowIfCancellationRequested();
            INamespaceSymbol? nsSym = FindNamespace(asm.GlobalNamespace, ns);
            if (nsSym is null) continue;
            foreach (INamedTypeSymbol t in nsSym.GetTypeMembers()
                         .Where(t => t.DeclaredAccessibility == Accessibility.Public && t.TypeKind != TypeKind.Delegate)
                         .OrderBy(t => t.Name, StringComparer.Ordinal))
                EmitType(sb, ns, t);
        }

        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static INamespaceSymbol? FindNamespace(INamespaceSymbol root, string ns)
    {
        INamespaceSymbol cur = root;
        foreach (string part in ns.Split('.'))
        {
            INamespaceSymbol? next = cur.GetNamespaceMembers().FirstOrDefault(n => n.Name == part);
            if (next is null) return null;
            cur = next;
        }
        return cur;
    }

    private static void EmitType(StringBuilder sb, string ns, INamedTypeSymbol t)
    {
        string kind = t.TypeKind switch
        {
            TypeKind.Struct => "struct",
            TypeKind.Interface => "interface",
            TypeKind.Enum => "enum",
            _ => "class",
        };
        sb.Append("            global::Luxel.UI.TypeApiRegistry.Register(new global::Luxel.UI.TypeApi(")
          .Append(Lit(ns)).Append(", ").Append(Lit(t.ToDisplayString(Short))).Append(", ").Append(Lit(kind))
          .Append(", ").Append(Lit(Summary(t)))
          .AppendLine(", new global::Luxel.UI.ApiMember[] {");

        if (t.TypeKind == TypeKind.Enum)
        {
            foreach (IFieldSymbol f in t.GetMembers().OfType<IFieldSymbol>().Where(f => f.IsConst || f.HasConstantValue))
                Row(sb, f.Name, "", "field", Summary(f));
        }
        else
        {
            foreach (ISymbol m in t.GetMembers().Where(Included))
            {
                switch (m)
                {
                    case IMethodSymbol { MethodKind: MethodKind.Constructor } c:
                        Row(sb, t.Name, "(" + Params(c) + ")", "ctor", Summary(c));
                        break;
                    case IMethodSymbol { MethodKind: MethodKind.Ordinary } f:
                        string ret = f.ReturnsVoid ? "void" : f.ReturnType.ToDisplayString(Short);
                        Row(sb, f.Name, "(" + Params(f) + ") → " + ret, "method", Summary(f));
                        break;
                    case IPropertySymbol p:
                        string acc = p.SetMethod is { DeclaredAccessibility: Accessibility.Public } ? "get/set" : "get";
                        Row(sb, p.Name, p.Type.ToDisplayString(Short) + " (" + acc + ")", "prop", Summary(p));
                        break;
                    case IEventSymbol e:
                        Row(sb, e.Name, e.Type.ToDisplayString(Short), "event", Summary(e));
                        break;
                    case IFieldSymbol fd:
                        Row(sb, fd.Name, fd.Type.ToDisplayString(Short) + (fd.IsConst ? " (const)" : fd.IsStatic ? " (static)" : ""),
                            "field", Summary(fd));
                        break;
                }
            }
        }
        sb.AppendLine("            }));");
    }

    /// <summary>公開 + 宣言メンバーのみ (object 由来の override・演算子・アクセサ・暗黙生成は出さない)。</summary>
    private static bool Included(ISymbol m)
    {
        if (m.DeclaredAccessibility != Accessibility.Public || m.IsImplicitlyDeclared) return false;
        if (m is IMethodSymbol mm)
        {
            if (mm.MethodKind is not (MethodKind.Ordinary or MethodKind.Constructor)) return false;
            if (mm.IsOverride && mm.Name is "ToString" or "Equals" or "GetHashCode") return false;
        }
        return m is IMethodSymbol or IPropertySymbol or IEventSymbol or IFieldSymbol;
    }

    private static string Params(IMethodSymbol m)
        => string.Join(", ", m.Parameters.Select(p => p.Type.ToDisplayString(Short) + " " + p.Name));

    private static void Row(StringBuilder sb, string name, string type, string kind, string desc)
        => sb.Append("                new(").Append(Lit(name)).Append(", ").Append(Lit(type))
             .Append(", ").Append(Lit(kind)).Append(", ").Append(Lit(desc)).AppendLine("),");

    /// <summary>XML doc の &lt;summary&gt; を取り出して整形 (see cref → 名前、タグ剥がし)。</summary>
    private static string Summary(ISymbol s)
    {
        string? xml = s.GetDocumentationCommentXml(expandIncludes: true);
        if (string.IsNullOrEmpty(xml)) return "";
        Match m = Regex.Match(xml!, @"<summary>(.*?)</summary>", RegexOptions.Singleline);
        if (!m.Success) return "";
        string body = Regex.Replace(m.Groups[1].Value, @"<see\s+cref=""[A-Z]:([^""]*)""\s*/>", static mm =>
        {
            string full = mm.Groups[1].Value;
            int i = full.LastIndexOf('.');
            return i >= 0 ? full.Substring(i + 1) : full;
        });
        body = Regex.Replace(body, @"<[^>]+>", "");
        return Regex.Replace(body, @"\s+", " ").Trim();
    }

    private static string Lit(string s) => SymbolDisplay.FormatLiteral(s, true);
}
