<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Luxel.Shaders\Luxel.Shaders.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Luxel.Shaders.Tests" />
  </ItemGroup>
</Project>
