using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;
using Luxel.Shaders;

if (args.Length == 4 && args[0] == "--manifest")
{
    WriteManifest(args[1], args[2], args[3]);
    return;
}

if (args.Length != 3 || args[2] is not ("compute" or "graphics"))
    throw new ArgumentException("Usage: Luxel.ShaderWgslGen <slang-wgsl> <output-wgsl> <compute|graphics>");

ShaderProgramKind programKind = args[2] == "compute" ? ShaderProgramKind.Compute : ShaderProgramKind.Graphics;
string wgsl = WgslNormalizer.Normalize(File.ReadAllText(args[0]), programKind, args[0]);

Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(args[1]))!);
File.WriteAllText(args[1], "// Generated by Slang 2026.14 + Luxel.ShaderWgslGen. Do not edit.\n" + wgsl.TrimEnd() + "\n",
    new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));

static void WriteManifest(string sourceDirectory, string artifactDirectory, string outputPath)
{
    var shaders = Directory.EnumerateFiles(sourceDirectory, "*.slang")
        .OrderBy(Path.GetFileName, StringComparer.Ordinal)
        .Select(source =>
        {
            string name = Path.GetFileNameWithoutExtension(source);
            string artifact = Path.Combine(artifactDirectory, name + ".wgsl");
            if (!File.Exists(artifact)) throw new FileNotFoundException("Missing generated WGSL artifact", artifact);
            string text = File.ReadAllText(artifact);
            var entries = new List<object>();
            foreach ((string attribute, string stage) in new[] { ("vertex", "vertex"), ("fragment", "fragment"), ("compute", "compute") })
                foreach (Match match in Regex.Matches(text, $@"@{attribute}\s+(?:@workgroup_size\([^\n]+\)\s+)?fn\s+(\w+)"))
                    entries.Add(new { name = match.Groups[1].Value, stage });
            return new
            {
                name,
                artifact = name + ".wgsl",
                entries,
                abi = new
                {
                    arena = text.Contains("@group(0) @binding(0)", StringComparison.Ordinal),
                    root = text.Contains("@group(0) @binding(1)", StringComparison.Ordinal),
                    sampledResources = text.Contains("@group(1)", StringComparison.Ordinal),
                },
            };
        }).ToArray();
    var manifest = new
    {
        schema = 1,
        generator = "Slang 2026.14 + Luxel.ShaderWgslGen",
        webGpuAbi = new { arenaGroup = 0, arenaBinding = 0, arenaStrideBytes = 256, rootGroup = 0, rootBinding = 1, rootBindingSize = 256, sampledGroup = 1, textureCount = 16, samplerCount = 16 },
        shaders,
    };
    Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(outputPath))!);
    File.WriteAllText(outputPath, JsonSerializer.Serialize(manifest, new JsonSerializerOptions { WriteIndented = true }) + "\n",
        new UTF8Encoding(false));
}
