using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;

const uint ArenaStrideWords = 64;
const int TextureCount = 16;
const int SamplerCount = 16;

if (args.Length == 4 && args[0] == "--manifest")
{
    WriteManifest(args[1], args[2], args[3]);
    return;
}

if (args.Length != 3 || args[2] is not ("compute" or "graphics"))
    throw new ArgumentException("Usage: Luxel.ShaderWgslGen <slang-wgsl> <output-wgsl> <compute|graphics>");

string wgsl = File.ReadAllText(args[0]).Replace("\r\n", "\n", StringComparison.Ordinal);
bool compute = args[2] == "compute";

// Slang 2026.14 emits function-scope `const`; WGSL uses `let` for local immutable values.
wgsl = Regex.Replace(wgsl, @"(?m)^(\s+)const\s+(\w+)\s*:", "$1let $2 :");
// Slang currently lowers SV_Depth to a scalar color location; restore the WGSL depth builtin.
wgsl = wgsl.Replace("@location(0) output_0 : f32,", "@builtin(frag_depth) output_0 : f32,", StringComparison.Ordinal);
wgsl = Regex.Replace(wgsl, @"(?m)^var<uniform>\s+(\w+)\s*:", "@group(0) @binding(1) var<uniform> $1 :");
wgsl = Regex.Replace(wgsl,
    @"(?m)^@binding\(0\) @group\(0\) var g_buffers_0 : array<array<u32>>;$",
    compute
        ? "@group(0) @binding(0) var<storage, read_write> g_buffers_0 : array<u32>;"
        : "@group(0) @binding(0) var<storage, read> g_buffers_0 : array<u32>;");
wgsl = Regex.Replace(wgsl, @"g_buffers_0\[([^\]\r\n]+)\]\[([^\]\r\n]+)\]",
    m => $"g_buffers_0[((({m.Groups[1].Value}) * {ArenaStrideWords}u) + ({m.Groups[2].Value}))]");

bool usesTextures = wgsl.Contains("g_textures_0", StringComparison.Ordinal);
if (usesTextures)
{
    wgsl = Regex.Replace(wgsl, @"(?m)^@binding\(1\) @group\(0\) var g_textures_0 : array<texture_2d<f32>>;\n?", "");
    wgsl = Regex.Replace(wgsl, @"(?m)^@binding\(2\) @group\(0\) var g_samplers_0 : array<sampler>;\n?", "");
    wgsl = Regex.Replace(wgsl,
        @"textureSample\(\(g_textures_0\[([^\]]+)\]\), \(g_samplers_0\[([^\]]+)\]\), \(([^\)]+)\)\)",
        m => $"luxelSample2d({m.Groups[1].Value}, {m.Groups[2].Value}, {m.Groups[3].Value})");
    if (wgsl.Contains("g_textures_0", StringComparison.Ordinal) || wgsl.Contains("g_samplers_0", StringComparison.Ordinal))
        throw new InvalidOperationException($"Unsupported generated texture access remains in {args[0]}.");
    wgsl = BuildSampledResourceCompat() + wgsl;
}

Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(args[1]))!);
File.WriteAllText(args[1], "// Generated by Slang 2026.14 + Luxel.ShaderWgslGen. Do not edit.\n" + wgsl.TrimEnd() + "\n",
    new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));

static string BuildSampledResourceCompat()
{
    var b = new StringBuilder();
    b.AppendLine("// Fixed WebGPU sampled-resource ABI: group 1, textures 0..15, samplers 16..31.");
    for (int i = 0; i < TextureCount; i++)
        b.AppendLine($"@group(1) @binding({i}) var luxelTexture{i} : texture_2d<f32>;");
    for (int i = 0; i < SamplerCount; i++)
        b.AppendLine($"@group(1) @binding({TextureCount + i}) var luxelSampler{i} : sampler;");
    b.AppendLine();
    for (int texture = 0; texture < TextureCount; texture++)
    {
        b.AppendLine($"fn luxelSampleTexture{texture}(samplerIndex: u32, uv: vec2<f32>) -> vec4<f32> {{");
        b.AppendLine("  switch samplerIndex {");
        for (int sampler = 0; sampler < SamplerCount; sampler++)
            b.AppendLine($"    case {sampler}u: {{ return textureSample(luxelTexture{texture}, luxelSampler{sampler}, uv); }}");
        b.AppendLine($"    default: {{ return textureSample(luxelTexture{texture}, luxelSampler0, uv); }}");
        b.AppendLine("  }");
        b.AppendLine("}");
    }
    b.AppendLine("fn luxelSample2d(textureIndex: u32, samplerIndex: u32, uv: vec2<f32>) -> vec4<f32> {");
    b.AppendLine("  switch textureIndex {");
    for (int texture = 0; texture < TextureCount; texture++)
        b.AppendLine($"    case {texture}u: {{ return luxelSampleTexture{texture}(samplerIndex, uv); }}");
    b.AppendLine("    default: { return luxelSampleTexture0(samplerIndex, uv); }");
    b.AppendLine("  }");
    b.AppendLine("}");
    b.AppendLine();
    return b.ToString();
}

static void WriteManifest(string sourceDirectory, string artifactDirectory, string outputPath)
{
    var shaders = Directory.EnumerateFiles(sourceDirectory, "*.slang")
        .OrderBy(Path.GetFileName, StringComparer.Ordinal)
        .Select(source =>
        {
            string name = Path.GetFileNameWithoutExtension(source);
            string artifact = Path.Combine(artifactDirectory, name + ".wgsl");
            if (!File.Exists(artifact)) throw new FileNotFoundException("Missing generated WGSL artifact", artifact);
            string text = File.ReadAllText(artifact);
            var entries = new List<object>();
            foreach ((string attribute, string stage) in new[] { ("vertex", "vertex"), ("fragment", "fragment"), ("compute", "compute") })
                foreach (Match match in Regex.Matches(text, $@"@{attribute}\s+(?:@workgroup_size\([^\n]+\)\s+)?fn\s+(\w+)"))
                    entries.Add(new { name = match.Groups[1].Value, stage });
            return new
            {
                name,
                artifact = name + ".wgsl",
                entries,
                abi = new
                {
                    arena = text.Contains("@group(0) @binding(0)", StringComparison.Ordinal),
                    root = text.Contains("@group(0) @binding(1)", StringComparison.Ordinal),
                    sampledResources = text.Contains("@group(1)", StringComparison.Ordinal),
                },
            };
        }).ToArray();
    var manifest = new
    {
        schema = 1,
        generator = "Slang 2026.14 + Luxel.ShaderWgslGen",
        webGpuAbi = new { arenaGroup = 0, arenaBinding = 0, arenaStrideBytes = 256, rootGroup = 0, rootBinding = 1, rootBindingSize = 256, sampledGroup = 1, textureCount = 16, samplerCount = 16 },
        shaders,
    };
    Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(outputPath))!);
    File.WriteAllText(outputPath, JsonSerializer.Serialize(manifest, new JsonSerializerOptions { WriteIndented = true }) + "\n",
        new UTF8Encoding(false));
}
