<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="HarfBuzzSharp" Version="14.2.0" />
    <PackageReference Include="HarfBuzzSharp.NativeAssets.Linux" Version="14.2.0" Condition="$([MSBuild]::IsOSPlatform('Linux'))" />
  </ItemGroup>

  <PropertyGroup>

    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
