<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Luxel.Diagnostics\Luxel.Diagnostics.csproj" />
  </ItemGroup>

  <PropertyGroup>

    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Platform\Luxel.Platform.Windows\Luxel.Platform.Windows.csproj" />
    <ProjectReference Include="..\..\Framework\Luxel.Framework.UI\Luxel.Framework.UI.csproj" />
    <ProjectReference Include="..\..\Graphics\Luxel.Graphics\Luxel.Graphics.csproj" />
    <ProjectReference Include="..\..\Graphics\Luxel.Graphics.TwoD\Luxel.Graphics.TwoD.csproj" />
    <ProjectReference Include="..\..\UI\Luxel.UI\Luxel.UI.csproj" />
    <ProjectReference Include="..\..\UI\Luxel.Controls\Luxel.Controls.csproj" />
    <ProjectReference Include="..\..\Platform\Luxel.Platform\Luxel.Platform.csproj" />
    <ProjectReference Include="..\Luxel.DevTools\Luxel.DevTools.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Luxel.Graphics" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Luxel.Platform" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Luxel.Platform.Windows" />
  </ItemGroup>
</Project>
