// Generated by Slang 2026.14 + Luxel.ShaderWgslGen. Do not edit.
struct _MatrixStorage_float4x4_ColMajorstd430_0
{
    @align(16) data_0 : array<vec4<f32>, i32(4)>,
};

struct Args_std430_0
{
    @align(16) viewProj_0 : _MatrixStorage_float4x4_ColMajorstd430_0,
    @align(16) right_0 : vec3<f32>,
    @align(4) instIndex_0 : u32,
    @align(16) up_0 : vec3<f32>,
    @align(4) _pad_0 : u32,
};

@group(0) @binding(1) var<uniform> args_0 : Args_std430_0;
@group(0) @binding(0) var<storage, read> g_buffers_0 : array<u32>;

var<private> CORNERS_0 : array<vec2<f32>, i32(6)> = array<vec2<f32>, i32(6)>( vec2<f32>(-0.5f, -0.5f), vec2<f32>(0.5f, -0.5f), vec2<f32>(0.5f, 0.5f), vec2<f32>(-0.5f, -0.5f), vec2<f32>(0.5f, 0.5f), vec2<f32>(-0.5f, 0.5f) );
struct VsOut_0
{
    @builtin(position) svPos_0 : vec4<f32>,
    @location(0) color_0 : vec4<f32>,
    @location(1) uv_0 : vec2<f32>,
};

@vertex
fn vsMain(@builtin(vertex_index) vid_0 : u32, @builtin(instance_index) iid_0 : u32) -> VsOut_0
{
    var base_0 : u32 = iid_0 * u32(32);
    var _S1 : u32 = args_0.instIndex_0;
    var _S2 : u32 = g_buffers_0[(((args_0.instIndex_0) * 64u) + ((base_0)/4))];
    var _S3 : u32 = g_buffers_0[(((_S1) * 64u) + ((base_0 + u32(4))/4))];
    var _S4 : u32 = g_buffers_0[(((_S1) * 64u) + ((base_0 + u32(8))/4))];
    var center_0 : vec3<f32> = (bitcast<vec3<f32>>((vec3<u32>(_S2, _S3, _S4))));
    var _S5 : u32 = g_buffers_0[(((args_0.instIndex_0) * 64u) + ((u32(i32(base_0 + u32(12))))/4))];
    var size_0 : f32 = (bitcast<f32>((_S5)));
    var _S6 : u32 = args_0.instIndex_0;
    var _S7 : u32 = base_0 + u32(16);
    var _S8 : u32 = g_buffers_0[(((args_0.instIndex_0) * 64u) + ((_S7)/4))];
    var _S9 : u32 = g_buffers_0[(((_S6) * 64u) + ((_S7 + u32(4))/4))];
    var _S10 : u32 = g_buffers_0[(((_S6) * 64u) + ((_S7 + u32(8))/4))];
    var _S11 : u32 = g_buffers_0[(((_S6) * 64u) + ((_S7 + u32(12))/4))];
    var color_1 : vec4<f32> = (bitcast<vec4<f32>>((vec4<u32>(_S8, _S9, _S10, _S11))));
    var o_0 : VsOut_0;
    o_0.svPos_0 = (((mat4x4<f32>(args_0.viewProj_0.data_0[i32(0)][i32(0)], args_0.viewProj_0.data_0[i32(1)][i32(0)], args_0.viewProj_0.data_0[i32(2)][i32(0)], args_0.viewProj_0.data_0[i32(3)][i32(0)], args_0.viewProj_0.data_0[i32(0)][i32(1)], args_0.viewProj_0.data_0[i32(1)][i32(1)], args_0.viewProj_0.data_0[i32(2)][i32(1)], args_0.viewProj_0.data_0[i32(3)][i32(1)], args_0.viewProj_0.data_0[i32(0)][i32(2)], args_0.viewProj_0.data_0[i32(1)][i32(2)], args_0.viewProj_0.data_0[i32(2)][i32(2)], args_0.viewProj_0.data_0[i32(3)][i32(2)], args_0.viewProj_0.data_0[i32(0)][i32(3)], args_0.viewProj_0.data_0[i32(1)][i32(3)], args_0.viewProj_0.data_0[i32(2)][i32(3)], args_0.viewProj_0.data_0[i32(3)][i32(3)])) * (vec4<f32>(center_0 + vec3<f32>((CORNERS_0[vid_0].x * size_0)) * args_0.right_0 + vec3<f32>((CORNERS_0[vid_0].y * size_0)) * args_0.up_0, 1.0f))));
    o_0.color_0 = color_1;
    o_0.uv_0 = CORNERS_0[vid_0] + vec2<f32>(0.5f);
    return o_0;
}

struct pixelOutput_0
{
    @location(0) output_0 : vec4<f32>,
};

struct pixelInput_0
{
    @location(0) color_2 : vec4<f32>,
    @location(1) uv_1 : vec2<f32>,
};

@fragment
fn psMain( _S12 : pixelInput_0, @builtin(position) svPos_1 : vec4<f32>) -> pixelOutput_0
{
    var _S13 : pixelOutput_0 = pixelOutput_0( vec4<f32>(_S12.color_2.xyz, _S12.color_2.w * smoothstep(0.5f, 0.41999998688697815f, length(_S12.uv_1 - vec2<f32>(0.5f)))) );
    return _S13;
}
