// Generated by Slang 2026.14 + Luxel.ShaderWgslGen. Do not edit.
struct CompositeArgs_std430_0
{
    @align(4) uiIndex_0 : u32,
    @align(4) blurIndex_0 : u32,
    @align(4) dstIndex_0 : u32,
    @align(4) width_0 : u32,
    @align(4) height_0 : u32,
    @align(4) splitX_0 : u32,
    @align(4) _pad0_0 : u32,
    @align(4) _pad1_0 : u32,
};

@group(0) @binding(1) var<uniform> args_0 : CompositeArgs_std430_0;
@group(0) @binding(0) var<storage, read_write> g_buffers_0 : array<u32>;

fn LoadPixel_0( bufIdx_0 : u32,  x_0 : i32,  y_0 : i32,  w_0 : i32) -> vec4<f32>
{
    var _S1 : u32 = g_buffers_0[(((bufIdx_0) * 64u) + ((u32(i32(u32((y_0 * w_0 + x_0) * i32(4)))))/4))];
    return vec4<f32>(f32((((_S1 >> (u32(0)))) & (u32(255)))) / 255.0f, f32((((_S1 >> (u32(8)))) & (u32(255)))) / 255.0f, f32((((_S1 >> (u32(16)))) & (u32(255)))) / 255.0f, f32((((_S1 >> (u32(24)))) & (u32(255)))) / 255.0f);
}

fn StorePixel_0( bufIdx_1 : u32,  x_1 : i32,  y_1 : i32,  w_1 : i32,  c_0 : vec4<f32>)
{
    g_buffers_0[(((bufIdx_1) * 64u) + ((u32((y_1 * w_1 + x_1) * i32(4)))/4))] = (((((u32(saturate(c_0.x) * 255.0f + 0.5f) | (((u32(saturate(c_0.y) * 255.0f + 0.5f) << (u32(8))))))) | (((u32(saturate(c_0.z) * 255.0f + 0.5f) << (u32(16))))))) | (((u32(saturate(c_0.w) * 255.0f + 0.5f) << (u32(24))))));
    return;
}

@compute
@workgroup_size(8, 8, 1)
fn main(@builtin(global_invocation_id) tid_0 : vec3<u32>)
{
    var w_2 : i32 = i32(args_0.width_0);
    var h_0 : i32 = i32(args_0.height_0);
    var x_2 : i32 = i32(tid_0.x);
    var y_2 : i32 = i32(tid_0.y);
    var _S2 : bool;
    if(x_2 >= w_2)
    {
        _S2 = true;
    }
    else
    {
        _S2 = y_2 >= h_0;
    }
    if(_S2)
    {
        return;
    }
    var src_0 : vec4<f32>;
    if(x_2 < i32(args_0.splitX_0))
    {
        src_0 = LoadPixel_0(args_0.uiIndex_0, x_2, y_2, w_2);
    }
    else
    {
        src_0 = LoadPixel_0(args_0.blurIndex_0, x_2, y_2, w_2);
    }
    var dx_0 : i32 = x_2 - i32(args_0.splitX_0);
    if(dx_0 == i32(0))
    {
        _S2 = true;
    }
    else
    {
        _S2 = dx_0 == i32(1);
    }
    if(_S2)
    {
        src_0 = vec4<f32>(0.85000002384185791f, 0.85000002384185791f, 0.85000002384185791f, 1.0f);
    }
    else
    {
    }
    StorePixel_0(args_0.dstIndex_0, x_2, y_2, w_2, src_0);
    return;
}
