// Generated by Slang 2026.14 + Luxel.ShaderWgslGen. Do not edit.
struct PostProcessArgs_std430_0
{
    @align(4) sourceBufferIndex_0 : u32,
    @align(4) destinationBufferIndex_0 : u32,
    @align(4) width_0 : u32,
    @align(4) height_0 : u32,
    @align(4) stridePixels_0 : u32,
};

@group(0) @binding(1) var<uniform> g_args_0 : PostProcessArgs_std430_0;
@group(0) @binding(0) var<storage, read_write> g_buffers_0 : array<u32>;

@compute
@workgroup_size(8, 8, 1)
fn main(@builtin(global_invocation_id) tid_0 : vec3<u32>)
{
    var _S1 : u32 = tid_0.x;
    var _S2 : bool;
    if(_S1 >= (g_args_0.width_0))
    {
        _S2 = true;
    }
    else
    {
        _S2 = (tid_0.y) >= (g_args_0.height_0);
    }
    if(_S2)
    {
        return;
    }
    var address_0 : u32 = (tid_0.y * g_args_0.stridePixels_0 + _S1) * u32(4);
    var _S3 : u32 = g_buffers_0[(((g_args_0.sourceBufferIndex_0) * 64u) + ((u32(i32(address_0)))/4))];
    var color_0 : vec3<f32> = vec3<f32>(f32((((_S3 >> (u32(0)))) & (u32(255)))) / 255.0f, f32((((_S3 >> (u32(8)))) & (u32(255)))) / 255.0f, f32((((_S3 >> (u32(16)))) & (u32(255)))) / 255.0f);
    var _S4 : vec2<f32> = vec2<f32>(0.5f);
    var _S5 : vec2<f32> = (vec2<f32>(tid_0.xy) + _S4) / vec2<f32>(f32(g_args_0.width_0), f32(g_args_0.height_0)) - _S4;
    var color_1 : vec3<f32> = mix(color_0, color_0 * vec3<f32>(0.72000002861022949f, 0.86000001430511475f, 1.08000004291534424f), vec3<f32>(0.2800000011920929f)) * vec3<f32>(saturate(1.14999997615814209f - dot(_S5, _S5) * 1.25f));
    g_buffers_0[(((g_args_0.destinationBufferIndex_0) * 64u) + ((address_0)/4))] = (((((u32(saturate(color_1.x) * 255.0f + 0.5f) | (((u32(saturate(color_1.y) * 255.0f + 0.5f) << (u32(8))))))) | (((u32(saturate(color_1.z) * 255.0f + 0.5f) << (u32(16))))))) | (u32(4278190080)));
    return;
}
