// Generated by Slang 2026.14 + Luxel.ShaderWgslGen. Do not edit.
struct RootArgs_std430_0
{
    @align(4) inputIndex_0 : u32,
    @align(4) outputIndex_0 : u32,
    @align(4) count_0 : u32,
};

@group(0) @binding(1) var<uniform> g_args_0 : RootArgs_std430_0;
@group(0) @binding(0) var<storage, read_write> g_buffers_0 : array<u32>;

@compute
@workgroup_size(64, 1, 1)
fn main(@builtin(global_invocation_id) tid_0 : vec3<u32>)
{
    var _S1 : u32 = tid_0.x;
    if(_S1 >= (g_args_0.count_0))
    {
        return;
    }
    var _S2 : u32 = _S1 * u32(4);
    var _S3 : u32 = g_buffers_0[(((g_args_0.inputIndex_0) * 64u) + ((u32(i32(_S2)))/4))];
    g_buffers_0[(((g_args_0.outputIndex_0) * 64u) + ((_S2)/4))] = (bitcast<u32>(((bitcast<f32>((_S3))) * 2.0f)));
    return;
}
