// Generated by Slang 2026.14 + Luxel.ShaderWgslGen. Do not edit.
struct BlurArgs_std430_0
{
    @align(4) srcIndex_0 : u32,
    @align(4) dstIndex_0 : u32,
    @align(4) width_0 : u32,
    @align(4) height_0 : u32,
    @align(4) dirX_0 : i32,
    @align(4) dirY_0 : i32,
    @align(4) _pad0_0 : u32,
    @align(4) _pad1_0 : u32,
};

@group(0) @binding(1) var<uniform> args_0 : BlurArgs_std430_0;
@group(0) @binding(0) var<storage, read_write> g_buffers_0 : array<u32>;

fn LoadPixel_0( bufIdx_0 : u32,  x_0 : i32,  y_0 : i32,  w_0 : i32,  h_0 : i32) -> vec4<f32>
{
    var _S1 : u32 = g_buffers_0[(((bufIdx_0) * 64u) + ((u32(i32(u32((clamp(y_0, i32(0), h_0 - i32(1)) * w_0 + clamp(x_0, i32(0), w_0 - i32(1))) * i32(4)))))/4))];
    return vec4<f32>(f32((((_S1 >> (u32(0)))) & (u32(255)))) / 255.0f, f32((((_S1 >> (u32(8)))) & (u32(255)))) / 255.0f, f32((((_S1 >> (u32(16)))) & (u32(255)))) / 255.0f, f32((((_S1 >> (u32(24)))) & (u32(255)))) / 255.0f);
}

fn StorePixel_0( bufIdx_1 : u32,  x_1 : i32,  y_1 : i32,  w_1 : i32,  c_0 : vec4<f32>)
{
    g_buffers_0[(((bufIdx_1) * 64u) + ((u32((y_1 * w_1 + x_1) * i32(4)))/4))] = (((((u32(saturate(c_0.x) * 255.0f + 0.5f) | (((u32(saturate(c_0.y) * 255.0f + 0.5f) << (u32(8))))))) | (((u32(saturate(c_0.z) * 255.0f + 0.5f) << (u32(16))))))) | (((u32(saturate(c_0.w) * 255.0f + 0.5f) << (u32(24))))));
    return;
}

@compute
@workgroup_size(8, 8, 1)
fn main(@builtin(global_invocation_id) tid_0 : vec3<u32>)
{
    var w_2 : i32 = i32(args_0.width_0);
    var h_1 : i32 = i32(args_0.height_0);
    var x_2 : i32 = i32(tid_0.x);
    var y_2 : i32 = i32(tid_0.y);
    var _S2 : bool;
    if(x_2 >= w_2)
    {
        _S2 = true;
    }
    else
    {
        _S2 = y_2 >= h_1;
    }
    if(_S2)
    {
        return;
    }
    var _S3 : vec4<f32> = vec4<f32>(0.01999999955296516f);
    var _S4 : vec4<f32> = vec4<f32>(0.05999999865889549f);
    var _S5 : vec4<f32> = vec4<f32>(0.11999999731779099f);
    var _S6 : vec4<f32> = vec4<f32>(0.18000000715255737f);
    StorePixel_0(args_0.dstIndex_0, x_2, y_2, w_2, LoadPixel_0(args_0.srcIndex_0, x_2 + args_0.dirX_0 * i32(-4), y_2 + args_0.dirY_0 * i32(-4), w_2, h_1) * _S3 + LoadPixel_0(args_0.srcIndex_0, x_2 + args_0.dirX_0 * i32(-3), y_2 + args_0.dirY_0 * i32(-3), w_2, h_1) * _S4 + LoadPixel_0(args_0.srcIndex_0, x_2 + args_0.dirX_0 * i32(-2), y_2 + args_0.dirY_0 * i32(-2), w_2, h_1) * _S5 + LoadPixel_0(args_0.srcIndex_0, x_2 + args_0.dirX_0 * i32(-1), y_2 + args_0.dirY_0 * i32(-1), w_2, h_1) * _S6 + LoadPixel_0(args_0.srcIndex_0, x_2, y_2, w_2, h_1) * vec4<f32>(0.23999999463558197f) + LoadPixel_0(args_0.srcIndex_0, x_2 + args_0.dirX_0, y_2 + args_0.dirY_0, w_2, h_1) * _S6 + LoadPixel_0(args_0.srcIndex_0, x_2 + args_0.dirX_0 * i32(2), y_2 + args_0.dirY_0 * i32(2), w_2, h_1) * _S5 + LoadPixel_0(args_0.srcIndex_0, x_2 + args_0.dirX_0 * i32(3), y_2 + args_0.dirY_0 * i32(3), w_2, h_1) * _S4 + LoadPixel_0(args_0.srcIndex_0, x_2 + args_0.dirX_0 * i32(4), y_2 + args_0.dirY_0 * i32(4), w_2, h_1) * _S3);
    return;
}
