// Generated by Slang 2026.14 + Luxel.ShaderWgslGen. Do not edit.
struct _MatrixStorage_float4x4_ColMajorstd430_0
{
    @align(16) data_0 : array<vec4<f32>, i32(4)>,
};

struct MainArgs_std430_0
{
    @align(16) viewProj_0 : _MatrixStorage_float4x4_ColMajorstd430_0,
    @align(16) lightVP_0 : _MatrixStorage_float4x4_ColMajorstd430_0,
    @align(16) vertexBufIndex_0 : u32,
    @align(4) instanceBufIndex_0 : u32,
    @align(8) shadowBufIndex_0 : u32,
    @align(4) shadowW_0 : u32,
    @align(16) shadowH_0 : u32,
    @align(4) _pad0_0 : u32,
    @align(8) _pad1_0 : u32,
    @align(4) _pad2_0 : u32,
};

@group(0) @binding(1) var<uniform> args_0 : MainArgs_std430_0;
@group(0) @binding(0) var<storage, read> g_buffers_0 : array<u32>;

struct VsOut_0
{
    @builtin(position) svPos_0 : vec4<f32>,
    @location(0) worldPos_0 : vec3<f32>,
    @location(1) normal_0 : vec3<f32>,
    @location(2) color_0 : vec3<f32>,
};

@vertex
fn vsMain(@builtin(vertex_index) vid_0 : u32, @builtin(instance_index) iid_0 : u32) -> VsOut_0
{
    var vAddr_0 : u32 = vid_0 * u32(24);
    var _S1 : u32 = args_0.vertexBufIndex_0;
    var _S2 : u32 = g_buffers_0[(((args_0.vertexBufIndex_0) * 64u) + ((vAddr_0)/4))];
    var _S3 : u32 = g_buffers_0[(((_S1) * 64u) + ((vAddr_0 + u32(4))/4))];
    var _S4 : u32 = g_buffers_0[(((_S1) * 64u) + ((vAddr_0 + u32(8))/4))];
    var vPos_0 : vec3<f32> = (bitcast<vec3<f32>>((vec3<u32>(_S2, _S3, _S4))));
    var _S5 : u32 = args_0.vertexBufIndex_0;
    var _S6 : u32 = vAddr_0 + u32(12);
    var _S7 : u32 = g_buffers_0[(((args_0.vertexBufIndex_0) * 64u) + ((_S6)/4))];
    var _S8 : u32 = g_buffers_0[(((_S5) * 64u) + ((_S6 + u32(4))/4))];
    var _S9 : u32 = g_buffers_0[(((_S5) * 64u) + ((_S6 + u32(8))/4))];
    var vNormal_0 : vec3<f32> = (bitcast<vec3<f32>>((vec3<u32>(_S7, _S8, _S9))));
    var iAddr_0 : u32 = iid_0 * u32(80);
    var _S10 : u32 = args_0.instanceBufIndex_0;
    var _S11 : u32 = g_buffers_0[(((args_0.instanceBufIndex_0) * 64u) + ((iAddr_0)/4))];
    var _S12 : u32 = g_buffers_0[(((_S10) * 64u) + ((iAddr_0 + u32(4))/4))];
    var _S13 : u32 = g_buffers_0[(((_S10) * 64u) + ((iAddr_0 + u32(8))/4))];
    var _S14 : u32 = g_buffers_0[(((_S10) * 64u) + ((iAddr_0 + u32(12))/4))];
    var r0_0 : vec4<f32> = (bitcast<vec4<f32>>((vec4<u32>(_S11, _S12, _S13, _S14))));
    var _S15 : u32 = args_0.instanceBufIndex_0;
    var _S16 : u32 = iAddr_0 + u32(16);
    var _S17 : u32 = g_buffers_0[(((args_0.instanceBufIndex_0) * 64u) + ((_S16)/4))];
    var _S18 : u32 = g_buffers_0[(((_S15) * 64u) + ((_S16 + u32(4))/4))];
    var _S19 : u32 = g_buffers_0[(((_S15) * 64u) + ((_S16 + u32(8))/4))];
    var _S20 : u32 = g_buffers_0[(((_S15) * 64u) + ((_S16 + u32(12))/4))];
    var r1_0 : vec4<f32> = (bitcast<vec4<f32>>((vec4<u32>(_S17, _S18, _S19, _S20))));
    var _S21 : u32 = args_0.instanceBufIndex_0;
    var _S22 : u32 = iAddr_0 + u32(32);
    var _S23 : u32 = g_buffers_0[(((args_0.instanceBufIndex_0) * 64u) + ((_S22)/4))];
    var _S24 : u32 = g_buffers_0[(((_S21) * 64u) + ((_S22 + u32(4))/4))];
    var _S25 : u32 = g_buffers_0[(((_S21) * 64u) + ((_S22 + u32(8))/4))];
    var _S26 : u32 = g_buffers_0[(((_S21) * 64u) + ((_S22 + u32(12))/4))];
    var r2_0 : vec4<f32> = (bitcast<vec4<f32>>((vec4<u32>(_S23, _S24, _S25, _S26))));
    var _S27 : u32 = args_0.instanceBufIndex_0;
    var _S28 : u32 = iAddr_0 + u32(48);
    var _S29 : u32 = g_buffers_0[(((args_0.instanceBufIndex_0) * 64u) + ((_S28)/4))];
    var _S30 : u32 = g_buffers_0[(((_S27) * 64u) + ((_S28 + u32(4))/4))];
    var _S31 : u32 = g_buffers_0[(((_S27) * 64u) + ((_S28 + u32(8))/4))];
    var _S32 : u32 = g_buffers_0[(((_S27) * 64u) + ((_S28 + u32(12))/4))];
    var world_0 : mat4x4<f32> = mat4x4<f32>(r0_0, r1_0, r2_0, (bitcast<vec4<f32>>((vec4<u32>(_S29, _S30, _S31, _S32)))));
    var _S33 : u32 = args_0.instanceBufIndex_0;
    var _S34 : u32 = iAddr_0 + u32(64);
    var _S35 : u32 = g_buffers_0[(((args_0.instanceBufIndex_0) * 64u) + ((_S34)/4))];
    var _S36 : u32 = g_buffers_0[(((_S33) * 64u) + ((_S34 + u32(4))/4))];
    var _S37 : u32 = g_buffers_0[(((_S33) * 64u) + ((_S34 + u32(8))/4))];
    var _S38 : u32 = g_buffers_0[(((_S33) * 64u) + ((_S34 + u32(12))/4))];
    var color_1 : vec4<f32> = (bitcast<vec4<f32>>((vec4<u32>(_S35, _S36, _S37, _S38))));
    var worldPos_1 : vec4<f32> = (((world_0) * (vec4<f32>(vPos_0, 1.0f))));
    var worldN_0 : vec3<f32> = (((mat3x3<f32>(world_0[i32(0)].xyz, world_0[i32(1)].xyz, world_0[i32(2)].xyz)) * (vNormal_0)));
    var o_0 : VsOut_0;
    o_0.svPos_0 = (((mat4x4<f32>(args_0.viewProj_0.data_0[i32(0)][i32(0)], args_0.viewProj_0.data_0[i32(1)][i32(0)], args_0.viewProj_0.data_0[i32(2)][i32(0)], args_0.viewProj_0.data_0[i32(3)][i32(0)], args_0.viewProj_0.data_0[i32(0)][i32(1)], args_0.viewProj_0.data_0[i32(1)][i32(1)], args_0.viewProj_0.data_0[i32(2)][i32(1)], args_0.viewProj_0.data_0[i32(3)][i32(1)], args_0.viewProj_0.data_0[i32(0)][i32(2)], args_0.viewProj_0.data_0[i32(1)][i32(2)], args_0.viewProj_0.data_0[i32(2)][i32(2)], args_0.viewProj_0.data_0[i32(3)][i32(2)], args_0.viewProj_0.data_0[i32(0)][i32(3)], args_0.viewProj_0.data_0[i32(1)][i32(3)], args_0.viewProj_0.data_0[i32(2)][i32(3)], args_0.viewProj_0.data_0[i32(3)][i32(3)])) * (worldPos_1)));
    o_0.worldPos_0 = worldPos_1.xyz;
    o_0.normal_0 = normalize(worldN_0);
    o_0.color_0 = color_1.xyz;
    return o_0;
}

fn SampleShadow_0( worldPos_2 : vec3<f32>) -> f32
{
    var lp_0 : vec4<f32> = (((mat4x4<f32>(args_0.lightVP_0.data_0[i32(0)][i32(0)], args_0.lightVP_0.data_0[i32(1)][i32(0)], args_0.lightVP_0.data_0[i32(2)][i32(0)], args_0.lightVP_0.data_0[i32(3)][i32(0)], args_0.lightVP_0.data_0[i32(0)][i32(1)], args_0.lightVP_0.data_0[i32(1)][i32(1)], args_0.lightVP_0.data_0[i32(2)][i32(1)], args_0.lightVP_0.data_0[i32(3)][i32(1)], args_0.lightVP_0.data_0[i32(0)][i32(2)], args_0.lightVP_0.data_0[i32(1)][i32(2)], args_0.lightVP_0.data_0[i32(2)][i32(2)], args_0.lightVP_0.data_0[i32(3)][i32(2)], args_0.lightVP_0.data_0[i32(0)][i32(3)], args_0.lightVP_0.data_0[i32(1)][i32(3)], args_0.lightVP_0.data_0[i32(2)][i32(3)], args_0.lightVP_0.data_0[i32(3)][i32(3)])) * (vec4<f32>(worldPos_2, 1.0f))));
    var _S39 : f32 = lp_0.w;
    if(_S39 <= 0.0f)
    {
        return 1.0f;
    }
    var ndc_0 : vec2<f32> = lp_0.xy / vec2<f32>(_S39);
    var ndcZ_0 : f32 = lp_0.z / _S39;
    var _S40 : f32 = ndc_0.x;
    var _S41 : bool;
    if(_S40 < -1.0f)
    {
        _S41 = true;
    }
    else
    {
        _S41 = _S40 > 1.0f;
    }
    if(_S41)
    {
        _S41 = true;
    }
    else
    {
        _S41 = (ndc_0.y) < -1.0f;
    }
    if(_S41)
    {
        _S41 = true;
    }
    else
    {
        _S41 = (ndc_0.y) > 1.0f;
    }
    if(_S41)
    {
        _S41 = true;
    }
    else
    {
        _S41 = ndcZ_0 < 0.0f;
    }
    if(_S41)
    {
        _S41 = true;
    }
    else
    {
        _S41 = ndcZ_0 > 1.0f;
    }
    if(_S41)
    {
        return 1.0f;
    }
    var _S42 : u32 = g_buffers_0[(((args_0.shadowBufIndex_0) * 64u) + ((u32(i32((u32(clamp(i32((ndc_0.y * 0.5f + 0.5f) * f32(args_0.shadowH_0)), i32(0), i32(args_0.shadowH_0) - i32(1))) * args_0.shadowW_0 + u32(clamp(i32((_S40 * 0.5f + 0.5f) * f32(args_0.shadowW_0)), i32(0), i32(args_0.shadowW_0) - i32(1)))) * u32(4))))/4))];
    var _S43 : f32;
    if((ndcZ_0 - 0.00300000002607703f) > (bitcast<f32>((_S42))))
    {
        _S43 = 0.34999999403953552f;
    }
    else
    {
        _S43 = 1.0f;
    }
    return _S43;
}

struct pixelOutput_0
{
    @location(0) output_0 : vec4<f32>,
};

struct pixelInput_0
{
    @location(0) worldPos_3 : vec3<f32>,
    @location(1) normal_1 : vec3<f32>,
    @location(2) color_2 : vec3<f32>,
};

@fragment
fn psMain( _S44 : pixelInput_0, @builtin(position) svPos_1 : vec4<f32>) -> pixelOutput_0
{
    var _S45 : pixelOutput_0 = pixelOutput_0( vec4<f32>(_S44.color_2 * vec3<f32>((0.20000000298023224f + 0.80000001192092896f * saturate(dot(normalize(_S44.normal_1), normalize(vec3<f32>(0.5f, 0.94999998807907104f, 0.25f)))) * SampleShadow_0(_S44.worldPos_3))), 1.0f) );
    return _S45;
}
