// Generated by Slang 2026.14 + Luxel.ShaderWgslGen. Do not edit.
struct RasterArgs_std430_0
{
    @align(4) a_0 : f32,
    @align(4) b_0 : f32,
    @align(4) c_0 : f32,
    @align(4) d_0 : f32,
    @align(4) e_0 : f32,
    @align(4) f_0 : f32,
    @align(4) width_0 : u32,
    @align(4) height_0 : u32,
    @align(4) segIndex_0 : u32,
    @align(4) pathIndex_0 : u32,
    @align(4) transformIndex_0 : u32,
    @align(4) styleIndex_0 : u32,
    @align(4) clipIndex_0 : u32,
    @align(4) orderIndex_0 : u32,
    @align(4) orderCount_0 : u32,
    @align(4) fbIndex_0 : u32,
    @align(4) bgMode_0 : u32,
    @align(4) tilesX_0 : u32,
    @align(4) tileCap_0 : u32,
    @align(4) boundsIndex_0 : u32,
    @align(4) tileListIndex_0 : u32,
    @align(4) tileCountIndex_0 : u32,
};

@group(0) @binding(1) var<uniform> args_0 : RasterArgs_std430_0;
@group(0) @binding(0) var<storage, read_write> g_buffers_0 : array<u32>;

@compute
@workgroup_size(64, 1, 1)
fn main(@builtin(global_invocation_id) tid_0 : vec3<u32>)
{
    var tile_0 : u32 = tid_0.x;
    if(tile_0 >= (args_0.tilesX_0 * ((args_0.height_0 + u32(15)) / u32(16))))
    {
        return;
    }
    var tx_0 : u32 = tile_0 % args_0.tilesX_0;
    var ty_0 : u32 = tile_0 / args_0.tilesX_0;
    var _S1 : f32 = f32(tx_0 * u32(16));
    var _S2 : f32 = f32(ty_0 * u32(16));
    var _S3 : vec2<f32> = vec2<f32>(_S1, _S2) + vec2<f32>(16.0f, 16.0f);
    var _S4 : u32 = tile_0 * args_0.tileCap_0;
    var oi_0 : u32 = u32(0);
    var count_0 : u32 = u32(0);
    for(;;)
    {
        if(oi_0 < (args_0.orderCount_0))
        {
        }
        else
        {
            break;
        }
        var _S5 : u32 = args_0.boundsIndex_0;
        var _S6 : u32 = oi_0 * u32(16);
        var _S7 : u32 = g_buffers_0[(((args_0.boundsIndex_0) * 64u) + ((_S6)/4))];
        var _S8 : f32 = bitcast<f32>(_S7);
        var _S9 : u32 = g_buffers_0[(((_S5) * 64u) + ((_S6 + u32(4))/4))];
        var _S10 : f32 = bitcast<f32>(_S9);
        var _S11 : u32 = g_buffers_0[(((_S5) * 64u) + ((_S6 + u32(8))/4))];
        var _S12 : f32 = bitcast<f32>(_S11);
        var _S13 : u32 = g_buffers_0[(((_S5) * 64u) + ((_S6 + u32(12))/4))];
        var _S14 : f32 = bitcast<f32>(_S13);
        var _S15 : bool;
        if((_S3.x) < _S8)
        {
            _S15 = true;
        }
        else
        {
            _S15 = _S1 > _S12;
        }
        var _S16 : bool;
        if(_S15)
        {
            _S16 = true;
        }
        else
        {
            _S16 = (_S3.y) < _S10;
        }
        var _S17 : bool;
        if(_S16)
        {
            _S17 = true;
        }
        else
        {
            _S17 = _S2 > _S14;
        }
        if(_S17)
        {
            oi_0 = oi_0 + u32(1);
            continue;
        }
        if(count_0 < (args_0.tileCap_0))
        {
            g_buffers_0[(((args_0.tileListIndex_0) * 64u) + (((_S4 + count_0) * u32(4))/4))] = oi_0;
        }
        count_0 = count_0 + u32(1);
        oi_0 = oi_0 + u32(1);
    }
    g_buffers_0[(((args_0.tileCountIndex_0) * 64u) + ((tile_0 * u32(4))/4))] = count_0;
    return;
}
