// Generated by Slang 2026.14 + Luxel.ShaderWgslGen. Do not edit.
struct RasterArgs_std430_0
{
    @align(4) a_0 : f32,
    @align(4) b_0 : f32,
    @align(4) c_0 : f32,
    @align(4) d_0 : f32,
    @align(4) e_0 : f32,
    @align(4) f_0 : f32,
    @align(4) width_0 : u32,
    @align(4) height_0 : u32,
    @align(4) segIndex_0 : u32,
    @align(4) pathIndex_0 : u32,
    @align(4) transformIndex_0 : u32,
    @align(4) styleIndex_0 : u32,
    @align(4) clipIndex_0 : u32,
    @align(4) orderIndex_0 : u32,
    @align(4) orderCount_0 : u32,
    @align(4) fbIndex_0 : u32,
    @align(4) bgMode_0 : u32,
    @align(4) tilesX_0 : u32,
    @align(4) tileCap_0 : u32,
    @align(4) boundsIndex_0 : u32,
    @align(4) tileListIndex_0 : u32,
    @align(4) tileCountIndex_0 : u32,
};

@group(0) @binding(1) var<uniform> args_0 : RasterArgs_std430_0;
@group(0) @binding(0) var<storage, read_write> g_buffers_0 : array<u32>;

fn affine_0( a_1 : f32,  b_1 : f32,  c_1 : f32,  d_1 : f32,  e_1 : f32,  f_1 : f32,  p_0 : vec2<f32>) -> vec2<f32>
{
    var _S1 : f32 = p_0.x;
    var _S2 : f32 = p_0.y;
    return vec2<f32>(a_1 * _S1 + c_1 * _S2 + e_1, b_1 * _S1 + d_1 * _S2 + f_1);
}

struct Tf_0
{
     a_2 : f32,
     b_2 : f32,
     c_2 : f32,
     d_2 : f32,
     e_2 : f32,
     f_2 : f32,
     p0_0 : u32,
     p1_0 : u32,
};

fn toScreen_0( w_0 : vec2<f32>,  tf_0 : Tf_0) -> vec2<f32>
{
    return affine_0(args_0.a_0, args_0.b_0, args_0.c_0, args_0.d_0, args_0.e_0, args_0.f_0, affine_0(tf_0.a_2, tf_0.b_2, tf_0.c_2, tf_0.d_2, tf_0.e_2, tf_0.f_2, w_0));
}

@compute
@workgroup_size(64, 1, 1)
fn main(@builtin(global_invocation_id) tid_0 : vec3<u32>)
{
    var oi_0 : u32 = tid_0.x;
    if(oi_0 >= (args_0.orderCount_0))
    {
        return;
    }
    var _S3 : u32 = g_buffers_0[(((args_0.orderIndex_0) * 64u) + ((oi_0 * u32(4))/4))];
    var _S4 : u32 = args_0.pathIndex_0;
    var _S5 : u32 = _S3 * u32(72);
    var _S6 : u32 = g_buffers_0[(((args_0.pathIndex_0) * 64u) + ((_S5)/4))];
    var _S7 : u32 = g_buffers_0[(((_S4) * 64u) + ((_S5 + u32(4))/4))];
    var _S8 : u32 = g_buffers_0[(((_S4) * 64u) + ((_S5 + u32(8))/4))];
    var _S9 : u32 = g_buffers_0[(((_S4) * 64u) + ((_S5 + u32(12))/4))];
    var _S10 : u32 = g_buffers_0[(((_S4) * 64u) + ((_S5 + u32(16))/4))];
    var _S11 : u32 = g_buffers_0[(((_S4) * 64u) + ((_S5 + u32(20))/4))];
    var _S12 : u32 = g_buffers_0[(((_S4) * 64u) + ((_S5 + u32(24))/4))];
    var _S13 : u32 = g_buffers_0[(((_S4) * 64u) + ((_S5 + u32(28))/4))];
    var _S14 : u32 = g_buffers_0[(((_S4) * 64u) + ((_S5 + u32(32))/4))];
    var _S15 : f32 = bitcast<f32>(_S14);
    var _S16 : u32 = g_buffers_0[(((_S4) * 64u) + ((_S5 + u32(36))/4))];
    var _S17 : f32 = bitcast<f32>(_S16);
    var _S18 : u32 = g_buffers_0[(((_S4) * 64u) + ((_S5 + u32(40))/4))];
    var _S19 : f32 = bitcast<f32>(_S18);
    var _S20 : u32 = g_buffers_0[(((_S4) * 64u) + ((_S5 + u32(44))/4))];
    var _S21 : f32 = bitcast<f32>(_S20);
    var _S22 : u32 = g_buffers_0[(((_S4) * 64u) + ((_S5 + u32(48))/4))];
    var _S23 : f32 = bitcast<f32>(_S22);
    var _S24 : u32 = g_buffers_0[(((_S4) * 64u) + ((_S5 + u32(52))/4))];
    var _S25 : u32 = g_buffers_0[(((_S4) * 64u) + ((_S5 + u32(56))/4))];
    var _S26 : u32 = g_buffers_0[(((_S4) * 64u) + ((_S5 + u32(60))/4))];
    var _S27 : u32 = g_buffers_0[(((_S4) * 64u) + ((_S5 + u32(64))/4))];
    var _S28 : u32 = g_buffers_0[(((_S4) * 64u) + ((_S5 + u32(68))/4))];
    var _S29 : u32 = args_0.transformIndex_0;
    var _S30 : u32 = _S8 * u32(32);
    var _S31 : u32 = g_buffers_0[(((args_0.transformIndex_0) * 64u) + ((_S30)/4))];
    var _S32 : f32 = bitcast<f32>(_S31);
    var _S33 : u32 = g_buffers_0[(((_S29) * 64u) + ((_S30 + u32(4))/4))];
    var _S34 : f32 = bitcast<f32>(_S33);
    var _S35 : u32 = g_buffers_0[(((_S29) * 64u) + ((_S30 + u32(8))/4))];
    var _S36 : f32 = bitcast<f32>(_S35);
    var _S37 : u32 = g_buffers_0[(((_S29) * 64u) + ((_S30 + u32(12))/4))];
    var _S38 : f32 = bitcast<f32>(_S37);
    var _S39 : u32 = g_buffers_0[(((_S29) * 64u) + ((_S30 + u32(16))/4))];
    var _S40 : f32 = bitcast<f32>(_S39);
    var _S41 : u32 = g_buffers_0[(((_S29) * 64u) + ((_S30 + u32(20))/4))];
    var _S42 : f32 = bitcast<f32>(_S41);
    var _S43 : u32 = g_buffers_0[(((_S29) * 64u) + ((_S30 + u32(24))/4))];
    var _S44 : u32 = g_buffers_0[(((_S29) * 64u) + ((_S30 + u32(28))/4))];
    var _S45 : Tf_0 = Tf_0( _S32, _S34, _S36, _S38, _S40, _S42, _S43, _S44 );
    let _S46 : vec2<f32> = vec2<f32>(-1.00000001504746622e+30f, -1.00000001504746622e+30f);
    let _S47 : vec2<f32> = vec2<f32>(1.00000001504746622e+30f, 1.00000001504746622e+30f);
    var clo_0 : vec2<f32>;
    var chi_0 : vec2<f32>;
    if(_S12 != u32(4294967295))
    {
        var _S48 : u32 = args_0.clipIndex_0;
        var _S49 : u32 = _S12 * u32(16);
        var _S50 : u32 = g_buffers_0[(((args_0.clipIndex_0) * 64u) + ((_S49)/4))];
        var _S51 : f32 = bitcast<f32>(_S50);
        var _S52 : u32 = g_buffers_0[(((_S48) * 64u) + ((_S49 + u32(4))/4))];
        var _S53 : f32 = bitcast<f32>(_S52);
        var _S54 : u32 = g_buffers_0[(((_S48) * 64u) + ((_S49 + u32(8))/4))];
        var _S55 : f32 = bitcast<f32>(_S54);
        var _S56 : u32 = g_buffers_0[(((_S48) * 64u) + ((_S49 + u32(12))/4))];
        var _S57 : f32 = bitcast<f32>(_S56);
        var k0_0 : vec2<f32> = affine_0(args_0.a_0, args_0.b_0, args_0.c_0, args_0.d_0, args_0.e_0, args_0.f_0, vec2<f32>(_S51, _S53));
        var k1_0 : vec2<f32> = affine_0(args_0.a_0, args_0.b_0, args_0.c_0, args_0.d_0, args_0.e_0, args_0.f_0, vec2<f32>(_S55, _S53));
        var k2_0 : vec2<f32> = affine_0(args_0.a_0, args_0.b_0, args_0.c_0, args_0.d_0, args_0.e_0, args_0.f_0, vec2<f32>(_S51, _S57));
        var k3_0 : vec2<f32> = affine_0(args_0.a_0, args_0.b_0, args_0.c_0, args_0.d_0, args_0.e_0, args_0.f_0, vec2<f32>(_S55, _S57));
        var _S58 : vec2<f32> = max(max(k0_0, k1_0), max(k2_0, k3_0));
        clo_0 = min(min(k0_0, k1_0), min(k2_0, k3_0));
        chi_0 = _S58;
    }
    else
    {
        clo_0 = _S46;
        chi_0 = _S47;
    }
    var q0_0 : vec2<f32> = toScreen_0(vec2<f32>(_S15, _S17), _S45);
    var q1_0 : vec2<f32> = toScreen_0(vec2<f32>(_S19, _S17), _S45);
    var q2_0 : vec2<f32> = toScreen_0(vec2<f32>(_S15, _S21), _S45);
    var q3_0 : vec2<f32> = toScreen_0(vec2<f32>(_S19, _S21), _S45);
    var _S59 : vec2<f32> = vec2<f32>((_S23 + 1.5f));
    var lo_0 : vec2<f32> = max(min(min(q0_0, q1_0), min(q2_0, q3_0)) - _S59, clo_0);
    var hi_0 : vec2<f32> = min(max(max(q0_0, q1_0), max(q2_0, q3_0)) + _S59, chi_0);
    var _S60 : u32 = args_0.boundsIndex_0;
    var _S61 : u32 = oi_0 * u32(16);
    var _S62 : f32 = lo_0.y;
    var _S63 : f32 = hi_0.x;
    var _S64 : f32 = hi_0.y;
    g_buffers_0[(((args_0.boundsIndex_0) * 64u) + ((_S61)/4))] = bitcast<u32>(lo_0.x);
    g_buffers_0[(((_S60) * 64u) + ((_S61 + u32(4))/4))] = bitcast<u32>(_S62);
    g_buffers_0[(((_S60) * 64u) + ((_S61 + u32(8))/4))] = bitcast<u32>(_S63);
    g_buffers_0[(((_S60) * 64u) + ((_S61 + u32(12))/4))] = bitcast<u32>(_S64);
    return;
}
