// Generated by Slang 2026.14 + Luxel.ShaderWgslGen. Do not edit.
struct RasterArgs_std430_0
{
    @align(4) a_0 : f32,
    @align(4) b_0 : f32,
    @align(4) c_0 : f32,
    @align(4) d_0 : f32,
    @align(4) e_0 : f32,
    @align(4) f_0 : f32,
    @align(4) width_0 : u32,
    @align(4) height_0 : u32,
    @align(4) segIndex_0 : u32,
    @align(4) pathIndex_0 : u32,
    @align(4) transformIndex_0 : u32,
    @align(4) styleIndex_0 : u32,
    @align(4) clipIndex_0 : u32,
    @align(4) orderIndex_0 : u32,
    @align(4) orderCount_0 : u32,
    @align(4) fbIndex_0 : u32,
    @align(4) bgMode_0 : u32,
    @align(4) tilesX_0 : u32,
    @align(4) tileCap_0 : u32,
    @align(4) boundsIndex_0 : u32,
    @align(4) tileListIndex_0 : u32,
    @align(4) tileCountIndex_0 : u32,
};

@group(0) @binding(1) var<uniform> args_0 : RasterArgs_std430_0;
@group(0) @binding(0) var<storage, read_write> g_buffers_0 : array<u32>;

fn affine_0( a_1 : f32,  b_1 : f32,  c_1 : f32,  d_1 : f32,  e_1 : f32,  f_1 : f32,  p_0 : vec2<f32>) -> vec2<f32>
{
    var _S1 : f32 = p_0.x;
    var _S2 : f32 = p_0.y;
    return vec2<f32>(a_1 * _S1 + c_1 * _S2 + e_1, b_1 * _S1 + d_1 * _S2 + f_1);
}

struct Cl_0
{
     minx_0 : f32,
     miny_0 : f32,
     maxx_0 : f32,
     maxy_0 : f32,
     radiusX_0 : f32,
     radiusY_0 : f32,
     corners_0 : u32,
     parentSlot_0 : u32,
};

fn insideRoundedClip_0( p_1 : vec2<f32>,  cl_0 : Cl_0) -> bool
{
    var k0_0 : vec2<f32> = affine_0(args_0.a_0, args_0.b_0, args_0.c_0, args_0.d_0, args_0.e_0, args_0.f_0, vec2<f32>(cl_0.minx_0, cl_0.miny_0));
    var k1_0 : vec2<f32> = affine_0(args_0.a_0, args_0.b_0, args_0.c_0, args_0.d_0, args_0.e_0, args_0.f_0, vec2<f32>(cl_0.maxx_0, cl_0.miny_0));
    var k2_0 : vec2<f32> = affine_0(args_0.a_0, args_0.b_0, args_0.c_0, args_0.d_0, args_0.e_0, args_0.f_0, vec2<f32>(cl_0.minx_0, cl_0.maxy_0));
    var k3_0 : vec2<f32> = affine_0(args_0.a_0, args_0.b_0, args_0.c_0, args_0.d_0, args_0.e_0, args_0.f_0, vec2<f32>(cl_0.maxx_0, cl_0.maxy_0));
    var lo_0 : vec2<f32> = min(min(k0_0, k1_0), min(k2_0, k3_0));
    var hi_0 : vec2<f32> = max(max(k0_0, k1_0), max(k2_0, k3_0));
    var _S3 : f32 = p_1.x;
    var _S4 : f32 = lo_0.x;
    var _S5 : bool;
    if(_S3 < _S4)
    {
        _S5 = true;
    }
    else
    {
        _S5 = _S3 > (hi_0.x);
    }
    if(_S5)
    {
        _S5 = true;
    }
    else
    {
        _S5 = (p_1.y) < (lo_0.y);
    }
    if(_S5)
    {
        _S5 = true;
    }
    else
    {
        _S5 = (p_1.y) > (hi_0.y);
    }
    if(_S5)
    {
        return false;
    }
    var radius_0 : vec2<f32> = min(vec2<f32>(cl_0.radiusX_0 * length(vec2<f32>(args_0.a_0, args_0.b_0)), cl_0.radiusY_0 * length(vec2<f32>(args_0.c_0, args_0.d_0))), (hi_0 - lo_0) * vec2<f32>(0.5f));
    if((cl_0.corners_0) == u32(0))
    {
        _S5 = true;
    }
    else
    {
        _S5 = (radius_0.x) <= 0.0f;
    }
    if(_S5)
    {
        _S5 = true;
    }
    else
    {
        _S5 = (radius_0.y) <= 0.0f;
    }
    if(_S5)
    {
        return true;
    }
    if((((cl_0.corners_0) & (u32(1)))) != u32(0))
    {
        _S5 = _S3 < (_S4 + radius_0.x);
    }
    else
    {
        _S5 = false;
    }
    if(_S5)
    {
        _S5 = (p_1.y) < (lo_0.y + radius_0.y);
    }
    else
    {
        _S5 = false;
    }
    var q_0 : vec2<f32>;
    if(_S5)
    {
        q_0 = (p_1 - (lo_0 + radius_0)) / radius_0;
    }
    else
    {
        if((((cl_0.corners_0) & (u32(2)))) != u32(0))
        {
            _S5 = _S3 > (hi_0.x - radius_0.x);
        }
        else
        {
            _S5 = false;
        }
        if(_S5)
        {
            _S5 = (p_1.y) < (lo_0.y + radius_0.y);
        }
        else
        {
            _S5 = false;
        }
        if(_S5)
        {
            q_0 = (p_1 - vec2<f32>(hi_0.x - radius_0.x, lo_0.y + radius_0.y)) / radius_0;
        }
        else
        {
            if((((cl_0.corners_0) & (u32(4)))) != u32(0))
            {
                _S5 = _S3 > (hi_0.x - radius_0.x);
            }
            else
            {
                _S5 = false;
            }
            if(_S5)
            {
                _S5 = (p_1.y) > (hi_0.y - radius_0.y);
            }
            else
            {
                _S5 = false;
            }
            if(_S5)
            {
                q_0 = (p_1 - (hi_0 - radius_0)) / radius_0;
            }
            else
            {
                if((((cl_0.corners_0) & (u32(8)))) != u32(0))
                {
                    _S5 = _S3 < (_S4 + radius_0.x);
                }
                else
                {
                    _S5 = false;
                }
                if(_S5)
                {
                    _S5 = (p_1.y) > (hi_0.y - radius_0.y);
                }
                else
                {
                    _S5 = false;
                }
                var _S6 : vec2<f32>;
                if(_S5)
                {
                    _S6 = (p_1 - vec2<f32>(_S4 + radius_0.x, hi_0.y - radius_0.y)) / radius_0;
                }
                else
                {
                    return true;
                }
                q_0 = _S6;
            }
        }
    }
    return (dot(q_0, q_0)) <= 1.0f;
}

fn insideAllClips_0( p_2 : vec2<f32>,  clipSlot_0 : u32) -> bool
{
    var _S7 : u32 = clipSlot_0;
    var depth_0 : u32 = u32(0);
    for(;;)
    {
        var _S8 : bool;
        if(_S7 != u32(4294967295))
        {
            _S8 = depth_0 < u32(64);
        }
        else
        {
            _S8 = false;
        }
        if(_S8)
        {
        }
        else
        {
            break;
        }
        var _S9 : u32 = args_0.clipIndex_0;
        var _S10 : u32 = _S7 * u32(32);
        var _S11 : u32 = g_buffers_0[(((args_0.clipIndex_0) * 64u) + ((_S10)/4))];
        var _S12 : f32 = bitcast<f32>(_S11);
        var _S13 : u32 = g_buffers_0[(((_S9) * 64u) + ((_S10 + u32(4))/4))];
        var _S14 : f32 = bitcast<f32>(_S13);
        var _S15 : u32 = g_buffers_0[(((_S9) * 64u) + ((_S10 + u32(8))/4))];
        var _S16 : f32 = bitcast<f32>(_S15);
        var _S17 : u32 = g_buffers_0[(((_S9) * 64u) + ((_S10 + u32(12))/4))];
        var _S18 : f32 = bitcast<f32>(_S17);
        var _S19 : u32 = g_buffers_0[(((_S9) * 64u) + ((_S10 + u32(16))/4))];
        var _S20 : f32 = bitcast<f32>(_S19);
        var _S21 : u32 = g_buffers_0[(((_S9) * 64u) + ((_S10 + u32(20))/4))];
        var _S22 : f32 = bitcast<f32>(_S21);
        var _S23 : u32 = g_buffers_0[(((_S9) * 64u) + ((_S10 + u32(24))/4))];
        var _S24 : u32 = g_buffers_0[(((_S9) * 64u) + ((_S10 + u32(28))/4))];
        var _S25 : Cl_0 = Cl_0( _S12, _S14, _S16, _S18, _S20, _S22, _S23, _S24 );
        if(!insideRoundedClip_0(p_2, _S25))
        {
            return false;
        }
        var _S26 : u32 = depth_0 + u32(1);
        _S7 = _S24;
        depth_0 = _S26;
    }
    return true;
}

struct Tf_0
{
     a_2 : f32,
     b_2 : f32,
     c_2 : f32,
     d_2 : f32,
     e_2 : f32,
     f_2 : f32,
     p0_0 : u32,
     p1_0 : u32,
};

fn toScreen_0( w_0 : vec2<f32>,  tf_0 : Tf_0) -> vec2<f32>
{
    return affine_0(args_0.a_0, args_0.b_0, args_0.c_0, args_0.d_0, args_0.e_0, args_0.f_0, affine_0(tf_0.a_2, tf_0.b_2, tf_0.c_2, tf_0.d_2, tf_0.e_2, tf_0.f_2, w_0));
}

fn distSeg_0( p_3 : vec2<f32>,  a_3 : vec2<f32>,  b_3 : vec2<f32>) -> f32
{
    var pa_0 : vec2<f32> = p_3 - a_3;
    var ba_0 : vec2<f32> = b_3 - a_3;
    return length(pa_0 - ba_0 * vec2<f32>(saturate(dot(pa_0, ba_0) / max(dot(ba_0, ba_0), 9.99999997475242708e-07f))));
}

fn unpack_0( c_3 : u32) -> vec4<f32>
{
    return vec4<f32>(f32((c_3 & (u32(255)))) / 255.0f, f32((((c_3 >> (u32(8)))) & (u32(255)))) / 255.0f, f32((((c_3 >> (u32(16)))) & (u32(255)))) / 255.0f, f32((((c_3 >> (u32(24)))) & (u32(255)))) / 255.0f);
}

struct Path_0
{
     segStart_0 : u32,
     segCount_0 : u32,
     transformSlot_0 : u32,
     styleSlot_0 : u32,
     fillRule_0 : u32,
     kind_0 : u32,
     clipSlot_1 : u32,
     srcIndex_0 : u32,
     bminx_0 : f32,
     bminy_0 : f32,
     bmaxx_0 : f32,
     bmaxy_0 : f32,
     strokeHalfWidth_0 : f32,
     srcStride_0 : u32,
     srcW_0 : u32,
     srcH_0 : u32,
     srcX_0 : u32,
     srcY_0 : u32,
};

fn loadMask_0( path_0 : Path_0,  texel_0 : vec2<i32>) -> f32
{
    var byteOffset_0 : u32 = (u32(texel_0.y) + path_0.srcY_0) * path_0.srcStride_0 + u32(texel_0.x) + path_0.srcX_0;
    var _S27 : u32 = g_buffers_0[(((path_0.srcIndex_0) * 64u) + (((byteOffset_0 & (u32(4294967292))))/4))];
    return f32((((_S27 >> ((((byteOffset_0 & (u32(3)))) * u32(8))))) & (u32(255)))) / 255.0f;
}

fn pack_0( rgb_0 : vec3<f32>) -> u32
{
    return (((((u32(saturate(rgb_0.x) * 255.0f + 0.5f) | (((u32(saturate(rgb_0.y) * 255.0f + 0.5f) << (u32(8))))))) | (((u32(saturate(rgb_0.z) * 255.0f + 0.5f) << (u32(16))))))) | (u32(4278190080)));
}

fn packRgba_0( c_4 : vec4<f32>) -> u32
{
    return (((((u32(saturate(c_4.x) * 255.0f + 0.5f) | (((u32(saturate(c_4.y) * 255.0f + 0.5f) << (u32(8))))))) | (((u32(saturate(c_4.z) * 255.0f + 0.5f) << (u32(16))))))) | (((u32(saturate(c_4.w) * 255.0f + 0.5f) << (u32(24))))));
}

@compute
@workgroup_size(8, 8, 1)
fn main(@builtin(global_invocation_id) tid_0 : vec3<u32>)
{
    var wind_0 : i32;
    var _S28 : u32 = tid_0.x;
    var hasRounded_0 : bool;
    if(_S28 >= (args_0.width_0))
    {
        hasRounded_0 = true;
    }
    else
    {
        hasRounded_0 = (tid_0.y) >= (args_0.height_0);
    }
    if(hasRounded_0)
    {
        return;
    }
    var _S29 : f32 = f32(_S28);
    var _S30 : f32 = _S29 + 0.5f;
    var _S31 : u32 = tid_0.y;
    var _S32 : f32 = f32(_S31);
    var _S33 : f32 = _S32 + 0.5f;
    var _S34 : vec2<f32> = vec2<f32>(_S30, _S33);
    let _S35 : vec4<f32> = vec4<f32>(0.0f, 0.0f, 0.0f, 0.0f);
    var tile_0 : u32 = _S28 / u32(16) + _S31 / u32(16) * args_0.tilesX_0;
    var _S36 : u32 = g_buffers_0[(((args_0.tileCountIndex_0) * 64u) + ((tile_0 * u32(4))/4))];
    var binned_0 : bool = _S36 <= (args_0.tileCap_0);
    var outPacked_0 : u32;
    if(binned_0)
    {
        outPacked_0 = _S36;
    }
    else
    {
        outPacked_0 = args_0.orderCount_0;
    }
    var acc_0 : vec4<f32> = _S35;
    var i_0 : u32 = u32(0);
    for(;;)
    {
        if(i_0 < outPacked_0)
        {
        }
        else
        {
            break;
        }
        var oi_0 : u32;
        if(binned_0)
        {
            var _S37 : u32 = g_buffers_0[(((args_0.tileListIndex_0) * 64u) + (((tile_0 * args_0.tileCap_0 + i_0) * u32(4))/4))];
            oi_0 = _S37;
        }
        else
        {
            oi_0 = i_0;
        }
        var _S38 : u32 = g_buffers_0[(((args_0.orderIndex_0) * 64u) + ((oi_0 * u32(4))/4))];
        var _S39 : u32 = args_0.pathIndex_0;
        var _S40 : u32 = _S38 * u32(72);
        var _S41 : u32 = g_buffers_0[(((args_0.pathIndex_0) * 64u) + ((_S40)/4))];
        var _S42 : u32 = g_buffers_0[(((_S39) * 64u) + ((_S40 + u32(4))/4))];
        var _S43 : u32 = g_buffers_0[(((_S39) * 64u) + ((_S40 + u32(8))/4))];
        var _S44 : u32 = g_buffers_0[(((_S39) * 64u) + ((_S40 + u32(12))/4))];
        var _S45 : u32 = g_buffers_0[(((_S39) * 64u) + ((_S40 + u32(16))/4))];
        var _S46 : u32 = g_buffers_0[(((_S39) * 64u) + ((_S40 + u32(20))/4))];
        var _S47 : u32 = g_buffers_0[(((_S39) * 64u) + ((_S40 + u32(24))/4))];
        var _S48 : u32 = g_buffers_0[(((_S39) * 64u) + ((_S40 + u32(28))/4))];
        var _S49 : u32 = g_buffers_0[(((_S39) * 64u) + ((_S40 + u32(32))/4))];
        var _S50 : f32 = bitcast<f32>(_S49);
        var _S51 : u32 = g_buffers_0[(((_S39) * 64u) + ((_S40 + u32(36))/4))];
        var _S52 : f32 = bitcast<f32>(_S51);
        var _S53 : u32 = g_buffers_0[(((_S39) * 64u) + ((_S40 + u32(40))/4))];
        var _S54 : f32 = bitcast<f32>(_S53);
        var _S55 : u32 = g_buffers_0[(((_S39) * 64u) + ((_S40 + u32(44))/4))];
        var _S56 : f32 = bitcast<f32>(_S55);
        var _S57 : u32 = g_buffers_0[(((_S39) * 64u) + ((_S40 + u32(48))/4))];
        var _S58 : f32 = bitcast<f32>(_S57);
        var _S59 : u32 = g_buffers_0[(((_S39) * 64u) + ((_S40 + u32(52))/4))];
        var _S60 : u32 = g_buffers_0[(((_S39) * 64u) + ((_S40 + u32(56))/4))];
        var _S61 : u32 = g_buffers_0[(((_S39) * 64u) + ((_S40 + u32(60))/4))];
        var _S62 : u32 = g_buffers_0[(((_S39) * 64u) + ((_S40 + u32(64))/4))];
        var _S63 : u32 = g_buffers_0[(((_S39) * 64u) + ((_S40 + u32(68))/4))];
        var _S64 : Path_0 = Path_0( _S41, _S42, _S43, _S44, _S45, _S46, _S47, _S48, _S50, _S52, _S54, _S56, _S58, _S59, _S60, _S61, _S62, _S63 );
        var _S65 : u32 = args_0.transformIndex_0;
        var _S66 : u32 = _S43 * u32(32);
        var _S67 : u32 = g_buffers_0[(((args_0.transformIndex_0) * 64u) + ((_S66)/4))];
        var _S68 : f32 = bitcast<f32>(_S67);
        var _S69 : u32 = g_buffers_0[(((_S65) * 64u) + ((_S66 + u32(4))/4))];
        var _S70 : f32 = bitcast<f32>(_S69);
        var _S71 : u32 = g_buffers_0[(((_S65) * 64u) + ((_S66 + u32(8))/4))];
        var _S72 : f32 = bitcast<f32>(_S71);
        var _S73 : u32 = g_buffers_0[(((_S65) * 64u) + ((_S66 + u32(12))/4))];
        var _S74 : f32 = bitcast<f32>(_S73);
        var _S75 : u32 = g_buffers_0[(((_S65) * 64u) + ((_S66 + u32(16))/4))];
        var _S76 : f32 = bitcast<f32>(_S75);
        var _S77 : u32 = g_buffers_0[(((_S65) * 64u) + ((_S66 + u32(20))/4))];
        var _S78 : f32 = bitcast<f32>(_S77);
        var _S79 : u32 = g_buffers_0[(((_S65) * 64u) + ((_S66 + u32(24))/4))];
        var _S80 : u32 = g_buffers_0[(((_S65) * 64u) + ((_S66 + u32(28))/4))];
        var _S81 : Tf_0 = Tf_0( _S68, _S70, _S72, _S74, _S76, _S78, _S79, _S80 );
        let _S82 : vec2<f32> = vec2<f32>(-1.00000001504746622e+30f, -1.00000001504746622e+30f);
        let _S83 : vec2<f32> = vec2<f32>(1.00000001504746622e+30f, 1.00000001504746622e+30f);
        var _S84 : bool;
        var _S85 : bool;
        var _S86 : bool;
        var s_0 : u32;
        var bit_0 : u32;
        var clipMask_0 : u32;
        var clo_0 : vec2<f32>;
        var chi_0 : vec2<f32>;
        var clipSamples_0 : i32;
        var inside_0 : i32;
        if(_S47 != u32(4294967295))
        {
            s_0 = _S47;
            clo_0 = _S82;
            chi_0 = _S83;
            hasRounded_0 = false;
            bit_0 = u32(0);
            for(;;)
            {
                if(s_0 != u32(4294967295))
                {
                    _S84 = bit_0 < u32(64);
                }
                else
                {
                    _S84 = false;
                }
                if(_S84)
                {
                }
                else
                {
                    break;
                }
                var _S87 : u32 = args_0.clipIndex_0;
                var _S88 : u32 = s_0 * u32(32);
                var _S89 : u32 = g_buffers_0[(((args_0.clipIndex_0) * 64u) + ((_S88)/4))];
                var _S90 : f32 = bitcast<f32>(_S89);
                var _S91 : u32 = g_buffers_0[(((_S87) * 64u) + ((_S88 + u32(4))/4))];
                var _S92 : f32 = bitcast<f32>(_S91);
                var _S93 : u32 = g_buffers_0[(((_S87) * 64u) + ((_S88 + u32(8))/4))];
                var _S94 : f32 = bitcast<f32>(_S93);
                var _S95 : u32 = g_buffers_0[(((_S87) * 64u) + ((_S88 + u32(12))/4))];
                var _S96 : f32 = bitcast<f32>(_S95);
                var _S97 : u32 = g_buffers_0[(((_S87) * 64u) + ((_S88 + u32(16))/4))];
                var _S98 : f32 = bitcast<f32>(_S97);
                var _S99 : u32 = g_buffers_0[(((_S87) * 64u) + ((_S88 + u32(20))/4))];
                var _S100 : f32 = bitcast<f32>(_S99);
                var _S101 : u32 = g_buffers_0[(((_S87) * 64u) + ((_S88 + u32(24))/4))];
                var _S102 : u32 = g_buffers_0[(((_S87) * 64u) + ((_S88 + u32(28))/4))];
                var k0_1 : vec2<f32> = affine_0(args_0.a_0, args_0.b_0, args_0.c_0, args_0.d_0, args_0.e_0, args_0.f_0, vec2<f32>(_S90, _S92));
                var k1_1 : vec2<f32> = affine_0(args_0.a_0, args_0.b_0, args_0.c_0, args_0.d_0, args_0.e_0, args_0.f_0, vec2<f32>(_S94, _S92));
                var k2_1 : vec2<f32> = affine_0(args_0.a_0, args_0.b_0, args_0.c_0, args_0.d_0, args_0.e_0, args_0.f_0, vec2<f32>(_S90, _S96));
                var k3_1 : vec2<f32> = affine_0(args_0.a_0, args_0.b_0, args_0.c_0, args_0.d_0, args_0.e_0, args_0.f_0, vec2<f32>(_S94, _S96));
                var _S103 : vec2<f32> = max(clo_0, min(min(k0_1, k1_1), min(k2_1, k3_1)));
                var _S104 : vec2<f32> = min(chi_0, max(max(k0_1, k1_1), max(k2_1, k3_1)));
                if(hasRounded_0)
                {
                    hasRounded_0 = true;
                }
                else
                {
                    if(_S101 != u32(0))
                    {
                        _S85 = _S98 > 0.0f;
                    }
                    else
                    {
                        _S85 = false;
                    }
                    if(_S85)
                    {
                        _S86 = _S100 > 0.0f;
                    }
                    else
                    {
                        _S86 = false;
                    }
                    hasRounded_0 = _S86;
                }
                var _S105 : u32 = bit_0 + u32(1);
                s_0 = _S102;
                clo_0 = _S103;
                chi_0 = _S104;
                bit_0 = _S105;
            }
            var _S106 : vec2<f32> = vec2<f32>(tid_0.xy);
            var pixelHi_0 : vec2<f32> = _S106 + vec2<f32>(1.0f);
            var _S107 : f32 = pixelHi_0.x;
            var _S108 : f32 = clo_0.x;
            if(_S107 <= _S108)
            {
                _S85 = true;
            }
            else
            {
                _S85 = (_S106.x) >= (chi_0.x);
            }
            if(_S85)
            {
                _S86 = true;
            }
            else
            {
                _S86 = (pixelHi_0.y) <= (clo_0.y);
            }
            var _S109 : bool;
            if(_S86)
            {
                _S109 = true;
            }
            else
            {
                _S109 = (_S106.y) >= (chi_0.y);
            }
            if(_S109)
            {
                i_0 = i_0 + u32(1);
                continue;
            }
            var _S110 : bool;
            if(hasRounded_0)
            {
                _S110 = true;
            }
            else
            {
                _S110 = (_S106.x) < _S108;
            }
            var _S111 : bool;
            if(_S110)
            {
                _S111 = true;
            }
            else
            {
                _S111 = _S107 > (chi_0.x);
            }
            var _S112 : bool;
            if(_S111)
            {
                _S112 = true;
            }
            else
            {
                _S112 = (_S106.y) < (clo_0.y);
            }
            var _S113 : bool;
            if(_S112)
            {
                _S113 = true;
            }
            else
            {
                _S113 = (pixelHi_0.y) > (chi_0.y);
            }
            if(_S113)
            {
                clipSamples_0 = i32(0);
                var clipMask_1 : u32 = u32(0);
                for(;;)
                {
                    if(clipSamples_0 < i32(4))
                    {
                    }
                    else
                    {
                        break;
                    }
                    inside_0 = i32(0);
                    clipMask_0 = clipMask_1;
                    for(;;)
                    {
                        if(inside_0 < i32(4))
                        {
                        }
                        else
                        {
                            break;
                        }
                        var bit_1 : u32 = u32(clipSamples_0 * i32(4) + inside_0);
                        if(insideAllClips_0(vec2<f32>(_S29 + (f32(inside_0) + 0.5f) * 0.25f, _S32 + (f32(clipSamples_0) + 0.5f) * 0.25f), _S47))
                        {
                            clipMask_0 = (clipMask_0 | (((u32(1) << (bit_1)))));
                        }
                        inside_0 = inside_0 + i32(1);
                    }
                    clipSamples_0 = clipSamples_0 + i32(1);
                    clipMask_1 = clipMask_0;
                }
                if(clipMask_1 == u32(0))
                {
                    i_0 = i_0 + u32(1);
                    continue;
                }
                clipMask_0 = clipMask_1;
            }
            else
            {
                clipMask_0 = u32(65535);
            }
        }
        else
        {
            clo_0 = _S82;
            chi_0 = _S83;
            clipMask_0 = u32(65535);
        }
        var _S114 : vec2<f32> = vec2<f32>(_S50, _S52);
        var q0_0 : vec2<f32> = toScreen_0(_S114, _S81);
        var q1_0 : vec2<f32> = toScreen_0(vec2<f32>(_S54, _S52), _S81);
        var q2_0 : vec2<f32> = toScreen_0(vec2<f32>(_S50, _S56), _S81);
        var q3_0 : vec2<f32> = toScreen_0(vec2<f32>(_S54, _S56), _S81);
        var _S115 : vec2<f32> = vec2<f32>((_S58 + 1.5f));
        var lo_1 : vec2<f32> = max(min(min(q0_0, q1_0), min(q2_0, q3_0)) - _S115, clo_0);
        var hi_1 : vec2<f32> = min(max(max(q0_0, q1_0), max(q2_0, q3_0)) + _S115, chi_0);
        if(_S30 < (lo_1.x))
        {
            hasRounded_0 = true;
        }
        else
        {
            hasRounded_0 = _S30 > (hi_1.x);
        }
        if(hasRounded_0)
        {
            _S84 = true;
        }
        else
        {
            _S84 = _S33 < (lo_1.y);
        }
        if(_S84)
        {
            _S85 = true;
        }
        else
        {
            _S85 = _S33 > (hi_1.y);
        }
        if(_S85)
        {
            i_0 = i_0 + u32(1);
            continue;
        }
        var cov_0 : f32;
        if(_S46 == u32(1))
        {
            cov_0 = 1.0e+09f;
            s_0 = u32(0);
            for(;;)
            {
                if(s_0 < _S42)
                {
                }
                else
                {
                    break;
                }
                var _S116 : u32 = args_0.segIndex_0;
                var _S117 : u32 = (_S41 + s_0) * u32(32);
                var _S118 : u32 = g_buffers_0[(((args_0.segIndex_0) * 64u) + ((_S117)/4))];
                var _S119 : f32 = bitcast<f32>(_S118);
                var _S120 : u32 = g_buffers_0[(((_S116) * 64u) + ((_S117 + u32(4))/4))];
                var _S121 : f32 = bitcast<f32>(_S120);
                var _S122 : u32 = g_buffers_0[(((_S116) * 64u) + ((_S117 + u32(8))/4))];
                var _S123 : f32 = bitcast<f32>(_S122);
                var _S124 : u32 = g_buffers_0[(((_S116) * 64u) + ((_S117 + u32(12))/4))];
                var _S125 : f32 = bitcast<f32>(_S124);
                var _S126 : u32 = g_buffers_0[(((_S116) * 64u) + ((_S117 + u32(16))/4))];
                var _S127 : u32 = g_buffers_0[(((_S116) * 64u) + ((_S117 + u32(20))/4))];
                var _S128 : u32 = g_buffers_0[(((_S116) * 64u) + ((_S117 + u32(24))/4))];
                var _S129 : u32 = g_buffers_0[(((_S116) * 64u) + ((_S117 + u32(28))/4))];
                var _S130 : f32 = min(cov_0, distSeg_0(_S34, toScreen_0(vec2<f32>(_S119, _S121), _S81), toScreen_0(vec2<f32>(_S123, _S125), _S81)));
                var _S131 : u32 = s_0 + u32(1);
                cov_0 = _S130;
                s_0 = _S131;
            }
            var cov_1 : f32 = 1.0f - smoothstep(_S58 - 0.75f, _S58 + 0.75f, cov_0);
            bit_0 = u32(0);
            clipSamples_0 = i32(0);
            for(;;)
            {
                if(bit_0 < u32(16))
                {
                }
                else
                {
                    break;
                }
                if(((clipMask_0 & (((u32(1) << (bit_0)))))) != u32(0))
                {
                    clipSamples_0 = clipSamples_0 + i32(1);
                }
                bit_0 = bit_0 + u32(1);
            }
            cov_0 = cov_1 * (f32(clipSamples_0) / 16.0f);
        }
        else
        {
            clipSamples_0 = i32(0);
            inside_0 = i32(0);
            for(;;)
            {
                if(clipSamples_0 < i32(4))
                {
                }
                else
                {
                    break;
                }
                var sx_0 : i32 = i32(0);
                var inside_1 : i32 = inside_0;
                for(;;)
                {
                    if(sx_0 < i32(4))
                    {
                    }
                    else
                    {
                        break;
                    }
                    if(((clipMask_0 & (((u32(1) << (u32(clipSamples_0 * i32(4) + sx_0))))))) == u32(0))
                    {
                        sx_0 = sx_0 + i32(1);
                        continue;
                    }
                    var _S132 : f32 = _S29 + (f32(sx_0) + 0.5f) * 0.25f;
                    var _S133 : f32 = _S32 + (f32(clipSamples_0) + 0.5f) * 0.25f;
                    s_0 = u32(0);
                    var wind_1 : i32 = i32(0);
                    for(;;)
                    {
                        if(s_0 < _S42)
                        {
                        }
                        else
                        {
                            break;
                        }
                        var _S134 : u32 = args_0.segIndex_0;
                        var _S135 : u32 = (_S41 + s_0) * u32(32);
                        var _S136 : u32 = g_buffers_0[(((args_0.segIndex_0) * 64u) + ((_S135)/4))];
                        var _S137 : f32 = bitcast<f32>(_S136);
                        var _S138 : u32 = g_buffers_0[(((_S134) * 64u) + ((_S135 + u32(4))/4))];
                        var _S139 : f32 = bitcast<f32>(_S138);
                        var _S140 : u32 = g_buffers_0[(((_S134) * 64u) + ((_S135 + u32(8))/4))];
                        var _S141 : f32 = bitcast<f32>(_S140);
                        var _S142 : u32 = g_buffers_0[(((_S134) * 64u) + ((_S135 + u32(12))/4))];
                        var _S143 : f32 = bitcast<f32>(_S142);
                        var _S144 : u32 = g_buffers_0[(((_S134) * 64u) + ((_S135 + u32(16))/4))];
                        var _S145 : u32 = g_buffers_0[(((_S134) * 64u) + ((_S135 + u32(20))/4))];
                        var _S146 : u32 = g_buffers_0[(((_S134) * 64u) + ((_S135 + u32(24))/4))];
                        var _S147 : u32 = g_buffers_0[(((_S134) * 64u) + ((_S135 + u32(28))/4))];
                        var A_0 : vec2<f32> = toScreen_0(vec2<f32>(_S137, _S139), _S81);
                        var B_0 : vec2<f32> = toScreen_0(vec2<f32>(_S141, _S143), _S81);
                        var _S148 : f32 = A_0.y;
                        var _S149 : f32 = B_0.y;
                        if((_S148 <= _S133) != (_S149 <= _S133))
                        {
                            var _S150 : f32 = A_0.x;
                            if((_S150 + (_S133 - _S148) / (_S149 - _S148) * (B_0.x - _S150)) > _S132)
                            {
                                if(_S149 > _S148)
                                {
                                    wind_0 = i32(1);
                                }
                                else
                                {
                                    wind_0 = i32(-1);
                                }
                                wind_0 = wind_1 + wind_0;
                            }
                            else
                            {
                                wind_0 = wind_1;
                            }
                            wind_1 = wind_0;
                        }
                        s_0 = s_0 + u32(1);
                    }
                    if(_S45 == u32(0))
                    {
                        _S86 = wind_1 != i32(0);
                    }
                    else
                    {
                        _S86 = ((wind_1 & (i32(1)))) != i32(0);
                    }
                    if(_S86)
                    {
                        wind_0 = inside_1 + i32(1);
                    }
                    else
                    {
                        wind_0 = inside_1;
                    }
                    inside_1 = wind_0;
                    sx_0 = sx_0 + i32(1);
                }
                clipSamples_0 = clipSamples_0 + i32(1);
                inside_0 = inside_1;
            }
            cov_0 = f32(inside_0) / 16.0f;
        }
        var acc_1 : vec4<f32>;
        if(cov_0 > 0.0f)
        {
            var _S151 : u32 = args_0.styleIndex_0;
            var _S152 : u32 = _S44 * u32(16);
            var _S153 : u32 = g_buffers_0[(((args_0.styleIndex_0) * 64u) + ((_S152)/4))];
            var _S154 : u32 = g_buffers_0[(((_S151) * 64u) + ((_S152 + u32(4))/4))];
            var _S155 : f32 = bitcast<f32>(_S154);
            var _S156 : u32 = g_buffers_0[(((_S151) * 64u) + ((_S152 + u32(8))/4))];
            var _S157 : u32 = g_buffers_0[(((_S151) * 64u) + ((_S152 + u32(12))/4))];
            var id_0 : f32;
            if(_S46 == u32(2))
            {
                var ca_0 : f32 = args_0.a_0 * _S68 + args_0.c_0 * _S70;
                var cb_0 : f32 = args_0.b_0 * _S68 + args_0.d_0 * _S70;
                var cc_0 : f32 = args_0.a_0 * _S72 + args_0.c_0 * _S74;
                var cd_0 : f32 = args_0.b_0 * _S72 + args_0.d_0 * _S74;
                var ce_0 : f32 = args_0.a_0 * _S76 + args_0.c_0 * _S78 + args_0.e_0;
                var cf_0 : f32 = args_0.b_0 * _S76 + args_0.d_0 * _S78 + args_0.f_0;
                var det_0 : f32 = ca_0 * cd_0 - cc_0 * cb_0;
                if((abs(det_0)) < 9.999999960041972e-13f)
                {
                    id_0 = 0.0f;
                }
                else
                {
                    id_0 = 1.0f / det_0;
                }
                var rel_0 : vec2<f32> = _S34 - vec2<f32>(ce_0, cf_0);
                var _S158 : f32 = rel_0.x;
                var _S159 : f32 = rel_0.y;
                var tex_0 : vec2<f32> = (vec2<f32>((cd_0 * _S158 - cc_0 * _S159) * id_0, (- cb_0 * _S158 + ca_0 * _S159) * id_0) - _S114) / max(vec2<f32>(_S54 - _S50, _S56 - _S52), vec2<f32>(9.99999997475242708e-07f)) * vec2<f32>(f32(_S60), f32(_S61)) - vec2<f32>(0.5f);
                var tf_1 : vec2<f32> = floor(tex_0);
                var fr_0 : vec2<f32> = tex_0 - tf_1;
                var tmax_0 : vec2<i32> = vec2<i32>(i32(_S60) - i32(1), i32(_S61) - i32(1));
                var t0_0 : vec2<i32> = clamp(vec2<i32>(tf_1), vec2<i32>(i32(0), i32(0)), tmax_0);
                var t1_0 : vec2<i32> = min(t0_0 + vec2<i32>(i32(1), i32(1)), tmax_0);
                var _S160 : u32 = (u32(t0_0.y) + _S63) * _S59;
                var _S161 : u32 = u32(t0_0.x);
                var _S162 : u32 = g_buffers_0[(((_S48) * 64u) + (((_S160 + _S161 + _S62) * u32(4))/4))];
                var c00_0 : vec4<f32> = unpack_0(_S162);
                var _S163 : u32 = u32(t1_0.x);
                var _S164 : u32 = g_buffers_0[(((_S48) * 64u) + (((_S160 + _S163 + _S62) * u32(4))/4))];
                var c10_0 : vec4<f32> = unpack_0(_S164);
                var _S165 : u32 = (u32(t1_0.y) + _S63) * _S59;
                var _S166 : u32 = g_buffers_0[(((_S48) * 64u) + (((_S165 + _S161 + _S62) * u32(4))/4))];
                var c01_0 : vec4<f32> = unpack_0(_S166);
                var _S167 : u32 = g_buffers_0[(((_S48) * 64u) + (((_S165 + _S163 + _S62) * u32(4))/4))];
                var _S168 : vec4<f32> = vec4<f32>(fr_0.x);
                var ic_0 : vec4<f32> = mix(mix(c00_0, c10_0, _S168), mix(c01_0, unpack_0(_S167), _S168), vec4<f32>(fr_0.y));
                var f_3 : f32 = _S155 * cov_0;
                acc_1 = vec4<f32>(ic_0.xyz * vec3<f32>(f_3), ic_0.w * f_3);
            }
            else
            {
                if(_S46 == u32(3))
                {
                    var ca_1 : f32 = args_0.a_0 * _S68 + args_0.c_0 * _S70;
                    var cb_1 : f32 = args_0.b_0 * _S68 + args_0.d_0 * _S70;
                    var cc_1 : f32 = args_0.a_0 * _S72 + args_0.c_0 * _S74;
                    var cd_1 : f32 = args_0.b_0 * _S72 + args_0.d_0 * _S74;
                    var ce_1 : f32 = args_0.a_0 * _S76 + args_0.c_0 * _S78 + args_0.e_0;
                    var cf_1 : f32 = args_0.b_0 * _S76 + args_0.d_0 * _S78 + args_0.f_0;
                    var det_1 : f32 = ca_1 * cd_1 - cc_1 * cb_1;
                    if((abs(det_1)) < 9.999999960041972e-13f)
                    {
                        id_0 = 0.0f;
                    }
                    else
                    {
                        id_0 = 1.0f / det_1;
                    }
                    var rel_1 : vec2<f32> = _S34 - vec2<f32>(ce_1, cf_1);
                    var _S169 : f32 = rel_1.x;
                    var _S170 : f32 = rel_1.y;
                    var _S171 : vec2<f32> = vec2<f32>(0.5f);
                    var tex_1 : vec2<f32> = (vec2<f32>((cd_1 * _S169 - cc_1 * _S170) * id_0, (- cb_1 * _S169 + ca_1 * _S170) * id_0) - _S114) / max(vec2<f32>(_S54 - _S50, _S56 - _S52), vec2<f32>(9.99999997475242708e-07f)) * vec2<f32>(f32(_S60), f32(_S61)) - _S171;
                    var tmax_1 : vec2<i32> = vec2<i32>(i32(_S60) - i32(1), i32(_S61) - i32(1));
                    var mask_0 : f32;
                    if(_S45 == u32(0))
                    {
                        mask_0 = loadMask_0(_S64, clamp(vec2<i32>(floor(tex_1 + _S171)), vec2<i32>(i32(0), i32(0)), tmax_1));
                    }
                    else
                    {
                        var tb_0 : vec2<f32> = floor(tex_1);
                        var fr_1 : vec2<f32> = tex_1 - tb_0;
                        var t0_1 : vec2<i32> = clamp(vec2<i32>(tb_0), vec2<i32>(i32(0), i32(0)), tmax_1);
                        var t1_1 : vec2<i32> = min(t0_1 + vec2<i32>(i32(1), i32(1)), tmax_1);
                        var _S172 : f32 = fr_1.x;
                        mask_0 = mix(mix(loadMask_0(_S64, t0_1), loadMask_0(_S64, vec2<i32>(t1_1.x, t0_1.y)), _S172), mix(loadMask_0(_S64, vec2<i32>(t0_1.x, t1_1.y)), loadMask_0(_S64, t1_1), _S172), fr_1.y);
                    }
                    var col_0 : vec4<f32> = unpack_0(_S153);
                    var a_4 : f32 = col_0.w * _S155 * cov_0 * mask_0;
                    acc_1 = vec4<f32>(col_0.xyz * vec3<f32>(a_4), a_4);
                }
                else
                {
                    var col_1 : vec4<f32> = unpack_0(_S153);
                    var a_5 : f32 = col_1.w * _S155 * cov_0;
                    acc_1 = vec4<f32>(col_1.xyz * vec3<f32>(a_5), a_5);
                }
            }
            acc_1 = acc_1 + acc_0 * vec4<f32>((1.0f - acc_1.w));
        }
        else
        {
            acc_1 = acc_0;
        }
        acc_0 = acc_1;
        i_0 = i_0 + u32(1);
    }
    if((args_0.bgMode_0) == u32(0))
    {
        outPacked_0 = pack_0(acc_0.xyz + vec3<f32>((1.0f - acc_0.w)));
    }
    else
    {
        outPacked_0 = packRgba_0(acc_0);
    }
    g_buffers_0[(((args_0.fbIndex_0) * 64u) + (((_S31 * args_0.width_0 + _S28) * u32(4))/4))] = outPacked_0;
    return;
}
