// Generated by Slang 2026.14 + Luxel.ShaderWgslGen. Do not edit.
struct _MatrixStorage_float4x4_ColMajorstd430_0
{
    @align(16) data_0 : array<vec4<f32>, i32(4)>,
};

struct RootArgs_std430_0
{
    @align(16) viewProj_0 : _MatrixStorage_float4x4_ColMajorstd430_0,
    @align(16) vertexBufIndex_0 : u32,
    @align(4) indexBufIndex_0 : u32,
    @align(8) instanceBufIndex_0 : u32,
    @align(4) jointBufIndex_0 : u32,
    @align(16) instanceStart_0 : u32,
    @align(4) _pad0_0 : u32,
    @align(8) _pad1_0 : u32,
    @align(4) _pad2_0 : u32,
};

@group(0) @binding(1) var<uniform> args_0 : RootArgs_std430_0;
@group(0) @binding(0) var<storage, read> g_buffers_0 : array<u32>;

fn LoadJoint_0( idx_0 : u32) -> mat4x4<f32>
{
    var addr_0 : u32 = idx_0 * u32(64);
    var _S1 : u32 = args_0.jointBufIndex_0;
    var _S2 : u32 = g_buffers_0[(((args_0.jointBufIndex_0) * 64u) + ((addr_0)/4))];
    var _S3 : u32 = g_buffers_0[(((_S1) * 64u) + ((addr_0 + u32(4))/4))];
    var _S4 : u32 = g_buffers_0[(((_S1) * 64u) + ((addr_0 + u32(8))/4))];
    var _S5 : u32 = g_buffers_0[(((_S1) * 64u) + ((addr_0 + u32(12))/4))];
    var r0_0 : vec4<f32> = (bitcast<vec4<f32>>((vec4<u32>(_S2, _S3, _S4, _S5))));
    var _S6 : u32 = args_0.jointBufIndex_0;
    var _S7 : u32 = addr_0 + u32(16);
    var _S8 : u32 = g_buffers_0[(((args_0.jointBufIndex_0) * 64u) + ((_S7)/4))];
    var _S9 : u32 = g_buffers_0[(((_S6) * 64u) + ((_S7 + u32(4))/4))];
    var _S10 : u32 = g_buffers_0[(((_S6) * 64u) + ((_S7 + u32(8))/4))];
    var _S11 : u32 = g_buffers_0[(((_S6) * 64u) + ((_S7 + u32(12))/4))];
    var r1_0 : vec4<f32> = (bitcast<vec4<f32>>((vec4<u32>(_S8, _S9, _S10, _S11))));
    var _S12 : u32 = args_0.jointBufIndex_0;
    var _S13 : u32 = addr_0 + u32(32);
    var _S14 : u32 = g_buffers_0[(((args_0.jointBufIndex_0) * 64u) + ((_S13)/4))];
    var _S15 : u32 = g_buffers_0[(((_S12) * 64u) + ((_S13 + u32(4))/4))];
    var _S16 : u32 = g_buffers_0[(((_S12) * 64u) + ((_S13 + u32(8))/4))];
    var _S17 : u32 = g_buffers_0[(((_S12) * 64u) + ((_S13 + u32(12))/4))];
    var r2_0 : vec4<f32> = (bitcast<vec4<f32>>((vec4<u32>(_S14, _S15, _S16, _S17))));
    var _S18 : u32 = args_0.jointBufIndex_0;
    var _S19 : u32 = addr_0 + u32(48);
    var _S20 : u32 = g_buffers_0[(((args_0.jointBufIndex_0) * 64u) + ((_S19)/4))];
    var _S21 : u32 = g_buffers_0[(((_S18) * 64u) + ((_S19 + u32(4))/4))];
    var _S22 : u32 = g_buffers_0[(((_S18) * 64u) + ((_S19 + u32(8))/4))];
    var _S23 : u32 = g_buffers_0[(((_S18) * 64u) + ((_S19 + u32(12))/4))];
    return mat4x4<f32>(r0_0, r1_0, r2_0, (bitcast<vec4<f32>>((vec4<u32>(_S20, _S21, _S22, _S23)))));
}

struct VsOut_0
{
    @builtin(position) svPos_0 : vec4<f32>,
    @location(0) normal_0 : vec3<f32>,
    @location(1) color_0 : vec3<f32>,
    @location(2) uv_0 : vec2<f32>,
};

@vertex
fn vsMain(@builtin(vertex_index) vid_0 : u32, @builtin(instance_index) iid_0 : u32) -> VsOut_0
{
    var actualVid_0 : u32;
    if((args_0.indexBufIndex_0) == u32(4294967295))
    {
        actualVid_0 = vid_0;
    }
    else
    {
        var _S24 : u32 = g_buffers_0[(((args_0.indexBufIndex_0) * 64u) + ((vid_0 * u32(4))/4))];
        actualVid_0 = _S24;
    }
    var vAddr_0 : u32 = actualVid_0 * u32(56);
    var _S25 : u32 = args_0.vertexBufIndex_0;
    var _S26 : u32 = g_buffers_0[(((args_0.vertexBufIndex_0) * 64u) + ((vAddr_0)/4))];
    var _S27 : u32 = g_buffers_0[(((_S25) * 64u) + ((vAddr_0 + u32(4))/4))];
    var _S28 : u32 = g_buffers_0[(((_S25) * 64u) + ((vAddr_0 + u32(8))/4))];
    var vPos_0 : vec3<f32> = (bitcast<vec3<f32>>((vec3<u32>(_S26, _S27, _S28))));
    var _S29 : u32 = args_0.vertexBufIndex_0;
    var _S30 : u32 = vAddr_0 + u32(12);
    var _S31 : u32 = g_buffers_0[(((args_0.vertexBufIndex_0) * 64u) + ((_S30)/4))];
    var _S32 : u32 = g_buffers_0[(((_S29) * 64u) + ((_S30 + u32(4))/4))];
    var _S33 : u32 = g_buffers_0[(((_S29) * 64u) + ((_S30 + u32(8))/4))];
    var vNrm_0 : vec3<f32> = (bitcast<vec3<f32>>((vec3<u32>(_S31, _S32, _S33))));
    var _S34 : u32 = args_0.vertexBufIndex_0;
    var _S35 : u32 = vAddr_0 + u32(24);
    var _S36 : u32 = g_buffers_0[(((args_0.vertexBufIndex_0) * 64u) + ((_S35)/4))];
    var _S37 : u32 = g_buffers_0[(((_S34) * 64u) + ((_S35 + u32(4))/4))];
    var vUv_0 : vec2<f32> = (bitcast<vec2<f32>>((vec2<u32>(_S36, _S37))));
    var _S38 : u32 = g_buffers_0[(((args_0.vertexBufIndex_0) * 64u) + ((vAddr_0 + u32(32))/4))];
    var _S39 : u32 = g_buffers_0[(((args_0.vertexBufIndex_0) * 64u) + ((vAddr_0 + u32(36))/4))];
    var _S40 : u32 = args_0.vertexBufIndex_0;
    var _S41 : u32 = vAddr_0 + u32(40);
    var _S42 : u32 = g_buffers_0[(((args_0.vertexBufIndex_0) * 64u) + ((_S41)/4))];
    var _S43 : u32 = g_buffers_0[(((_S40) * 64u) + ((_S41 + u32(4))/4))];
    var _S44 : u32 = g_buffers_0[(((_S40) * 64u) + ((_S41 + u32(8))/4))];
    var _S45 : u32 = g_buffers_0[(((_S40) * 64u) + ((_S41 + u32(12))/4))];
    var weights_0 : vec4<f32> = (bitcast<vec4<f32>>((vec4<u32>(_S42, _S43, _S44, _S45))));
    var _S46 : mat4x4<f32> = LoadJoint_0((_S38 & (u32(65535))));
    var _S47 : mat4x4<f32> = mat4x4<f32>(weights_0.x, weights_0.x, weights_0.x, weights_0.x, weights_0.x, weights_0.x, weights_0.x, weights_0.x, weights_0.x, weights_0.x, weights_0.x, weights_0.x, weights_0.x, weights_0.x, weights_0.x, weights_0.x);
    var _S48 : mat4x4<f32> = LoadJoint_0((((_S38 >> (u32(16)))) & (u32(65535))));
    var _S49 : mat4x4<f32> = mat4x4<f32>(weights_0.y, weights_0.y, weights_0.y, weights_0.y, weights_0.y, weights_0.y, weights_0.y, weights_0.y, weights_0.y, weights_0.y, weights_0.y, weights_0.y, weights_0.y, weights_0.y, weights_0.y, weights_0.y);
    var _S50 : mat4x4<f32> = LoadJoint_0((_S39 & (u32(65535))));
    var _S51 : mat4x4<f32> = mat4x4<f32>(weights_0.z, weights_0.z, weights_0.z, weights_0.z, weights_0.z, weights_0.z, weights_0.z, weights_0.z, weights_0.z, weights_0.z, weights_0.z, weights_0.z, weights_0.z, weights_0.z, weights_0.z, weights_0.z);
    var _S52 : mat4x4<f32> = LoadJoint_0((((_S39 >> (u32(16)))) & (u32(65535))));
    var _S53 : mat4x4<f32> = mat4x4<f32>(weights_0.w, weights_0.w, weights_0.w, weights_0.w, weights_0.w, weights_0.w, weights_0.w, weights_0.w, weights_0.w, weights_0.w, weights_0.w, weights_0.w, weights_0.w, weights_0.w, weights_0.w, weights_0.w);
    var skinMat_0 : mat4x4<f32> = mat4x4<f32>(_S47[0] * _S46[0], _S47[1] * _S46[1], _S47[2] * _S46[2], _S47[3] * _S46[3]) + mat4x4<f32>(_S49[0] * _S48[0], _S49[1] * _S48[1], _S49[2] * _S48[2], _S49[3] * _S48[3]) + mat4x4<f32>(_S51[0] * _S50[0], _S51[1] * _S50[1], _S51[2] * _S50[2], _S51[3] * _S50[3]) + mat4x4<f32>(_S53[0] * _S52[0], _S53[1] * _S52[1], _S53[2] * _S52[2], _S53[3] * _S52[3]);
    var skinnedPos_0 : vec4<f32> = (((skinMat_0) * (vec4<f32>(vPos_0, 1.0f))));
    var skinnedNrm_0 : vec3<f32> = (((mat3x3<f32>(skinMat_0[i32(0)].xyz, skinMat_0[i32(1)].xyz, skinMat_0[i32(2)].xyz)) * (vNrm_0)));
    var iAddr_0 : u32 = (args_0.instanceStart_0 + iid_0) * u32(80);
    var _S54 : u32 = args_0.instanceBufIndex_0;
    var _S55 : u32 = g_buffers_0[(((args_0.instanceBufIndex_0) * 64u) + ((iAddr_0)/4))];
    var _S56 : u32 = g_buffers_0[(((_S54) * 64u) + ((iAddr_0 + u32(4))/4))];
    var _S57 : u32 = g_buffers_0[(((_S54) * 64u) + ((iAddr_0 + u32(8))/4))];
    var _S58 : u32 = g_buffers_0[(((_S54) * 64u) + ((iAddr_0 + u32(12))/4))];
    var r0_1 : vec4<f32> = (bitcast<vec4<f32>>((vec4<u32>(_S55, _S56, _S57, _S58))));
    var _S59 : u32 = args_0.instanceBufIndex_0;
    var _S60 : u32 = iAddr_0 + u32(16);
    var _S61 : u32 = g_buffers_0[(((args_0.instanceBufIndex_0) * 64u) + ((_S60)/4))];
    var _S62 : u32 = g_buffers_0[(((_S59) * 64u) + ((_S60 + u32(4))/4))];
    var _S63 : u32 = g_buffers_0[(((_S59) * 64u) + ((_S60 + u32(8))/4))];
    var _S64 : u32 = g_buffers_0[(((_S59) * 64u) + ((_S60 + u32(12))/4))];
    var r1_1 : vec4<f32> = (bitcast<vec4<f32>>((vec4<u32>(_S61, _S62, _S63, _S64))));
    var _S65 : u32 = args_0.instanceBufIndex_0;
    var _S66 : u32 = iAddr_0 + u32(32);
    var _S67 : u32 = g_buffers_0[(((args_0.instanceBufIndex_0) * 64u) + ((_S66)/4))];
    var _S68 : u32 = g_buffers_0[(((_S65) * 64u) + ((_S66 + u32(4))/4))];
    var _S69 : u32 = g_buffers_0[(((_S65) * 64u) + ((_S66 + u32(8))/4))];
    var _S70 : u32 = g_buffers_0[(((_S65) * 64u) + ((_S66 + u32(12))/4))];
    var r2_1 : vec4<f32> = (bitcast<vec4<f32>>((vec4<u32>(_S67, _S68, _S69, _S70))));
    var _S71 : u32 = args_0.instanceBufIndex_0;
    var _S72 : u32 = iAddr_0 + u32(48);
    var _S73 : u32 = g_buffers_0[(((args_0.instanceBufIndex_0) * 64u) + ((_S72)/4))];
    var _S74 : u32 = g_buffers_0[(((_S71) * 64u) + ((_S72 + u32(4))/4))];
    var _S75 : u32 = g_buffers_0[(((_S71) * 64u) + ((_S72 + u32(8))/4))];
    var _S76 : u32 = g_buffers_0[(((_S71) * 64u) + ((_S72 + u32(12))/4))];
    var world_0 : mat4x4<f32> = mat4x4<f32>(r0_1, r1_1, r2_1, (bitcast<vec4<f32>>((vec4<u32>(_S73, _S74, _S75, _S76)))));
    var _S77 : u32 = args_0.instanceBufIndex_0;
    var _S78 : u32 = iAddr_0 + u32(64);
    var _S79 : u32 = g_buffers_0[(((args_0.instanceBufIndex_0) * 64u) + ((_S78)/4))];
    var _S80 : u32 = g_buffers_0[(((_S77) * 64u) + ((_S78 + u32(4))/4))];
    var _S81 : u32 = g_buffers_0[(((_S77) * 64u) + ((_S78 + u32(8))/4))];
    var _S82 : u32 = g_buffers_0[(((_S77) * 64u) + ((_S78 + u32(12))/4))];
    var baseColor_0 : vec4<f32> = (bitcast<vec4<f32>>((vec4<u32>(_S79, _S80, _S81, _S82))));
    var worldN_0 : vec3<f32> = (((mat3x3<f32>(world_0[i32(0)].xyz, world_0[i32(1)].xyz, world_0[i32(2)].xyz)) * (skinnedNrm_0)));
    var o_0 : VsOut_0;
    o_0.svPos_0 = (((mat4x4<f32>(args_0.viewProj_0.data_0[i32(0)][i32(0)], args_0.viewProj_0.data_0[i32(1)][i32(0)], args_0.viewProj_0.data_0[i32(2)][i32(0)], args_0.viewProj_0.data_0[i32(3)][i32(0)], args_0.viewProj_0.data_0[i32(0)][i32(1)], args_0.viewProj_0.data_0[i32(1)][i32(1)], args_0.viewProj_0.data_0[i32(2)][i32(1)], args_0.viewProj_0.data_0[i32(3)][i32(1)], args_0.viewProj_0.data_0[i32(0)][i32(2)], args_0.viewProj_0.data_0[i32(1)][i32(2)], args_0.viewProj_0.data_0[i32(2)][i32(2)], args_0.viewProj_0.data_0[i32(3)][i32(2)], args_0.viewProj_0.data_0[i32(0)][i32(3)], args_0.viewProj_0.data_0[i32(1)][i32(3)], args_0.viewProj_0.data_0[i32(2)][i32(3)], args_0.viewProj_0.data_0[i32(3)][i32(3)])) * ((((world_0) * (skinnedPos_0))))));
    o_0.normal_0 = normalize(worldN_0);
    o_0.color_0 = baseColor_0.xyz;
    o_0.uv_0 = vUv_0;
    return o_0;
}

struct pixelOutput_0
{
    @location(0) output_0 : vec4<f32>,
};

struct pixelInput_0
{
    @location(0) normal_1 : vec3<f32>,
    @location(1) color_1 : vec3<f32>,
    @location(2) uv_1 : vec2<f32>,
};

@fragment
fn psMain( _S83 : pixelInput_0, @builtin(position) svPos_1 : vec4<f32>) -> pixelOutput_0
{
    var _S84 : pixelOutput_0 = pixelOutput_0( vec4<f32>(_S83.color_1 * vec3<f32>((0.25f + 0.75f * saturate(dot(normalize(_S83.normal_1), normalize(vec3<f32>(0.60000002384185791f, 0.85000002384185791f, 0.40000000596046448f)))))), 1.0f) );
    return _S84;
}
