// Generated by Slang 2026.14 + Luxel.ShaderWgslGen. Do not edit.
struct _MatrixStorage_float4x4_ColMajorstd430_0
{
    @align(16) data_0 : array<vec4<f32>, i32(4)>,
};

struct RootArgs_std430_0
{
    @align(16) viewProj_0 : _MatrixStorage_float4x4_ColMajorstd430_0,
    @align(16) vertexBufIndex_0 : u32,
    @align(4) indexBufIndex_0 : u32,
    @align(8) instanceBufIndex_0 : u32,
    @align(4) instanceStart_0 : u32,
    @align(16) morphBufIndex_0 : u32,
    @align(4) weightBufIndex_0 : u32,
    @align(8) targetCount_0 : u32,
    @align(4) vertexCount_0 : u32,
};

@group(0) @binding(1) var<uniform> args_0 : RootArgs_std430_0;
@group(0) @binding(0) var<storage, read> g_buffers_0 : array<u32>;

struct VsOut_0
{
    @builtin(position) svPos_0 : vec4<f32>,
    @location(0) normal_0 : vec3<f32>,
    @location(1) color_0 : vec3<f32>,
    @location(2) uv_0 : vec2<f32>,
};

@vertex
fn vsMain(@builtin(vertex_index) vid_0 : u32, @builtin(instance_index) iid_0 : u32) -> VsOut_0
{
    var actualVid_0 : u32;
    if((args_0.indexBufIndex_0) == u32(4294967295))
    {
        actualVid_0 = vid_0;
    }
    else
    {
        var _S1 : u32 = g_buffers_0[(((args_0.indexBufIndex_0) * 64u) + ((vid_0 * u32(4))/4))];
        actualVid_0 = _S1;
    }
    var vAddr_0 : u32 = actualVid_0 * u32(32);
    var _S2 : u32 = args_0.vertexBufIndex_0;
    var _S3 : u32 = g_buffers_0[(((args_0.vertexBufIndex_0) * 64u) + ((vAddr_0)/4))];
    var _S4 : u32 = g_buffers_0[(((_S2) * 64u) + ((vAddr_0 + u32(4))/4))];
    var _S5 : u32 = g_buffers_0[(((_S2) * 64u) + ((vAddr_0 + u32(8))/4))];
    var _S6 : vec3<f32> = (bitcast<vec3<f32>>((vec3<u32>(_S3, _S4, _S5))));
    var _S7 : u32 = args_0.vertexBufIndex_0;
    var _S8 : u32 = vAddr_0 + u32(12);
    var _S9 : u32 = g_buffers_0[(((args_0.vertexBufIndex_0) * 64u) + ((_S8)/4))];
    var _S10 : u32 = g_buffers_0[(((_S7) * 64u) + ((_S8 + u32(4))/4))];
    var _S11 : u32 = g_buffers_0[(((_S7) * 64u) + ((_S8 + u32(8))/4))];
    var _S12 : vec3<f32> = (bitcast<vec3<f32>>((vec3<u32>(_S9, _S10, _S11))));
    var _S13 : u32 = args_0.vertexBufIndex_0;
    var _S14 : u32 = vAddr_0 + u32(24);
    var _S15 : u32 = g_buffers_0[(((args_0.vertexBufIndex_0) * 64u) + ((_S14)/4))];
    var _S16 : u32 = g_buffers_0[(((_S13) * 64u) + ((_S14 + u32(4))/4))];
    var vUv_0 : vec2<f32> = (bitcast<vec2<f32>>((vec2<u32>(_S15, _S16))));
    var t_0 : u32 = u32(0);
    var vPos_0 : vec3<f32> = _S6;
    var vNrm_0 : vec3<f32> = _S12;
    for(;;)
    {
        if(t_0 < (args_0.targetCount_0))
        {
        }
        else
        {
            break;
        }
        var _S17 : u32 = g_buffers_0[(((args_0.weightBufIndex_0) * 64u) + ((u32(i32(t_0 * u32(4))))/4))];
        var w_0 : f32 = (bitcast<f32>((_S17)));
        var mAddr_0 : u32 = (t_0 * args_0.vertexCount_0 + actualVid_0) * u32(24);
        var _S18 : u32 = args_0.morphBufIndex_0;
        var _S19 : u32 = g_buffers_0[(((args_0.morphBufIndex_0) * 64u) + ((mAddr_0)/4))];
        var _S20 : u32 = g_buffers_0[(((_S18) * 64u) + ((mAddr_0 + u32(4))/4))];
        var _S21 : u32 = g_buffers_0[(((_S18) * 64u) + ((mAddr_0 + u32(8))/4))];
        var dPos_0 : vec3<f32> = (bitcast<vec3<f32>>((vec3<u32>(_S19, _S20, _S21))));
        var _S22 : u32 = args_0.morphBufIndex_0;
        var _S23 : u32 = mAddr_0 + u32(12);
        var _S24 : u32 = g_buffers_0[(((args_0.morphBufIndex_0) * 64u) + ((_S23)/4))];
        var _S25 : u32 = g_buffers_0[(((_S22) * 64u) + ((_S23 + u32(4))/4))];
        var _S26 : u32 = g_buffers_0[(((_S22) * 64u) + ((_S23 + u32(8))/4))];
        var _S27 : vec3<f32> = vec3<f32>(w_0);
        var vPos_1 : vec3<f32> = vPos_0 + _S27 * dPos_0;
        var vNrm_1 : vec3<f32> = vNrm_0 + _S27 * (bitcast<vec3<f32>>((vec3<u32>(_S24, _S25, _S26))));
        t_0 = t_0 + u32(1);
        vPos_0 = vPos_1;
        vNrm_0 = vNrm_1;
    }
    var iAddr_0 : u32 = (args_0.instanceStart_0 + iid_0) * u32(80);
    var _S28 : u32 = args_0.instanceBufIndex_0;
    var _S29 : u32 = g_buffers_0[(((args_0.instanceBufIndex_0) * 64u) + ((iAddr_0)/4))];
    var _S30 : u32 = g_buffers_0[(((_S28) * 64u) + ((iAddr_0 + u32(4))/4))];
    var _S31 : u32 = g_buffers_0[(((_S28) * 64u) + ((iAddr_0 + u32(8))/4))];
    var _S32 : u32 = g_buffers_0[(((_S28) * 64u) + ((iAddr_0 + u32(12))/4))];
    var r0_0 : vec4<f32> = (bitcast<vec4<f32>>((vec4<u32>(_S29, _S30, _S31, _S32))));
    var _S33 : u32 = args_0.instanceBufIndex_0;
    var _S34 : u32 = iAddr_0 + u32(16);
    var _S35 : u32 = g_buffers_0[(((args_0.instanceBufIndex_0) * 64u) + ((_S34)/4))];
    var _S36 : u32 = g_buffers_0[(((_S33) * 64u) + ((_S34 + u32(4))/4))];
    var _S37 : u32 = g_buffers_0[(((_S33) * 64u) + ((_S34 + u32(8))/4))];
    var _S38 : u32 = g_buffers_0[(((_S33) * 64u) + ((_S34 + u32(12))/4))];
    var r1_0 : vec4<f32> = (bitcast<vec4<f32>>((vec4<u32>(_S35, _S36, _S37, _S38))));
    var _S39 : u32 = args_0.instanceBufIndex_0;
    var _S40 : u32 = iAddr_0 + u32(32);
    var _S41 : u32 = g_buffers_0[(((args_0.instanceBufIndex_0) * 64u) + ((_S40)/4))];
    var _S42 : u32 = g_buffers_0[(((_S39) * 64u) + ((_S40 + u32(4))/4))];
    var _S43 : u32 = g_buffers_0[(((_S39) * 64u) + ((_S40 + u32(8))/4))];
    var _S44 : u32 = g_buffers_0[(((_S39) * 64u) + ((_S40 + u32(12))/4))];
    var r2_0 : vec4<f32> = (bitcast<vec4<f32>>((vec4<u32>(_S41, _S42, _S43, _S44))));
    var _S45 : u32 = args_0.instanceBufIndex_0;
    var _S46 : u32 = iAddr_0 + u32(48);
    var _S47 : u32 = g_buffers_0[(((args_0.instanceBufIndex_0) * 64u) + ((_S46)/4))];
    var _S48 : u32 = g_buffers_0[(((_S45) * 64u) + ((_S46 + u32(4))/4))];
    var _S49 : u32 = g_buffers_0[(((_S45) * 64u) + ((_S46 + u32(8))/4))];
    var _S50 : u32 = g_buffers_0[(((_S45) * 64u) + ((_S46 + u32(12))/4))];
    var world_0 : mat4x4<f32> = mat4x4<f32>(r0_0, r1_0, r2_0, (bitcast<vec4<f32>>((vec4<u32>(_S47, _S48, _S49, _S50)))));
    var _S51 : u32 = args_0.instanceBufIndex_0;
    var _S52 : u32 = iAddr_0 + u32(64);
    var _S53 : u32 = g_buffers_0[(((args_0.instanceBufIndex_0) * 64u) + ((_S52)/4))];
    var _S54 : u32 = g_buffers_0[(((_S51) * 64u) + ((_S52 + u32(4))/4))];
    var _S55 : u32 = g_buffers_0[(((_S51) * 64u) + ((_S52 + u32(8))/4))];
    var _S56 : u32 = g_buffers_0[(((_S51) * 64u) + ((_S52 + u32(12))/4))];
    var baseColor_0 : vec4<f32> = (bitcast<vec4<f32>>((vec4<u32>(_S53, _S54, _S55, _S56))));
    var worldN_0 : vec3<f32> = (((mat3x3<f32>(world_0[i32(0)].xyz, world_0[i32(1)].xyz, world_0[i32(2)].xyz)) * (vNrm_0)));
    var o_0 : VsOut_0;
    o_0.svPos_0 = (((mat4x4<f32>(args_0.viewProj_0.data_0[i32(0)][i32(0)], args_0.viewProj_0.data_0[i32(1)][i32(0)], args_0.viewProj_0.data_0[i32(2)][i32(0)], args_0.viewProj_0.data_0[i32(3)][i32(0)], args_0.viewProj_0.data_0[i32(0)][i32(1)], args_0.viewProj_0.data_0[i32(1)][i32(1)], args_0.viewProj_0.data_0[i32(2)][i32(1)], args_0.viewProj_0.data_0[i32(3)][i32(1)], args_0.viewProj_0.data_0[i32(0)][i32(2)], args_0.viewProj_0.data_0[i32(1)][i32(2)], args_0.viewProj_0.data_0[i32(2)][i32(2)], args_0.viewProj_0.data_0[i32(3)][i32(2)], args_0.viewProj_0.data_0[i32(0)][i32(3)], args_0.viewProj_0.data_0[i32(1)][i32(3)], args_0.viewProj_0.data_0[i32(2)][i32(3)], args_0.viewProj_0.data_0[i32(3)][i32(3)])) * ((((world_0) * (vec4<f32>(vPos_0, 1.0f)))))));
    o_0.normal_0 = normalize(worldN_0);
    o_0.color_0 = baseColor_0.xyz;
    o_0.uv_0 = vUv_0;
    return o_0;
}

struct pixelOutput_0
{
    @location(0) output_0 : vec4<f32>,
};

struct pixelInput_0
{
    @location(0) normal_1 : vec3<f32>,
    @location(1) color_1 : vec3<f32>,
    @location(2) uv_1 : vec2<f32>,
};

@fragment
fn psMain( _S57 : pixelInput_0, @builtin(position) svPos_1 : vec4<f32>) -> pixelOutput_0
{
    var _S58 : pixelOutput_0 = pixelOutput_0( vec4<f32>(_S57.color_1 * vec3<f32>((0.25f + 0.75f * saturate(dot(normalize(_S57.normal_1), normalize(vec3<f32>(0.60000002384185791f, 0.85000002384185791f, 0.40000000596046448f)))))), 1.0f) );
    return _S58;
}
