// Generated by Slang 2026.14 + Luxel.ShaderWgslGen. Do not edit.
// Fixed WebGPU sampled-resource ABI: group 1, textures 0..15, samplers 16..31.
@group(1) @binding(0) var luxelTexture0 : texture_2d<f32>;
@group(1) @binding(1) var luxelTexture1 : texture_2d<f32>;
@group(1) @binding(2) var luxelTexture2 : texture_2d<f32>;
@group(1) @binding(3) var luxelTexture3 : texture_2d<f32>;
@group(1) @binding(4) var luxelTexture4 : texture_2d<f32>;
@group(1) @binding(5) var luxelTexture5 : texture_2d<f32>;
@group(1) @binding(6) var luxelTexture6 : texture_2d<f32>;
@group(1) @binding(7) var luxelTexture7 : texture_2d<f32>;
@group(1) @binding(8) var luxelTexture8 : texture_2d<f32>;
@group(1) @binding(9) var luxelTexture9 : texture_2d<f32>;
@group(1) @binding(10) var luxelTexture10 : texture_2d<f32>;
@group(1) @binding(11) var luxelTexture11 : texture_2d<f32>;
@group(1) @binding(12) var luxelTexture12 : texture_2d<f32>;
@group(1) @binding(13) var luxelTexture13 : texture_2d<f32>;
@group(1) @binding(14) var luxelTexture14 : texture_2d<f32>;
@group(1) @binding(15) var luxelTexture15 : texture_2d<f32>;
@group(1) @binding(16) var luxelSampler0 : sampler;
@group(1) @binding(17) var luxelSampler1 : sampler;
@group(1) @binding(18) var luxelSampler2 : sampler;
@group(1) @binding(19) var luxelSampler3 : sampler;
@group(1) @binding(20) var luxelSampler4 : sampler;
@group(1) @binding(21) var luxelSampler5 : sampler;
@group(1) @binding(22) var luxelSampler6 : sampler;
@group(1) @binding(23) var luxelSampler7 : sampler;
@group(1) @binding(24) var luxelSampler8 : sampler;
@group(1) @binding(25) var luxelSampler9 : sampler;
@group(1) @binding(26) var luxelSampler10 : sampler;
@group(1) @binding(27) var luxelSampler11 : sampler;
@group(1) @binding(28) var luxelSampler12 : sampler;
@group(1) @binding(29) var luxelSampler13 : sampler;
@group(1) @binding(30) var luxelSampler14 : sampler;
@group(1) @binding(31) var luxelSampler15 : sampler;

fn luxelSampleTexture0(samplerIndex: u32, uv: vec2<f32>) -> vec4<f32> {
  switch samplerIndex {
    case 0u: { return textureSample(luxelTexture0, luxelSampler0, uv); }
    case 1u: { return textureSample(luxelTexture0, luxelSampler1, uv); }
    case 2u: { return textureSample(luxelTexture0, luxelSampler2, uv); }
    case 3u: { return textureSample(luxelTexture0, luxelSampler3, uv); }
    case 4u: { return textureSample(luxelTexture0, luxelSampler4, uv); }
    case 5u: { return textureSample(luxelTexture0, luxelSampler5, uv); }
    case 6u: { return textureSample(luxelTexture0, luxelSampler6, uv); }
    case 7u: { return textureSample(luxelTexture0, luxelSampler7, uv); }
    case 8u: { return textureSample(luxelTexture0, luxelSampler8, uv); }
    case 9u: { return textureSample(luxelTexture0, luxelSampler9, uv); }
    case 10u: { return textureSample(luxelTexture0, luxelSampler10, uv); }
    case 11u: { return textureSample(luxelTexture0, luxelSampler11, uv); }
    case 12u: { return textureSample(luxelTexture0, luxelSampler12, uv); }
    case 13u: { return textureSample(luxelTexture0, luxelSampler13, uv); }
    case 14u: { return textureSample(luxelTexture0, luxelSampler14, uv); }
    case 15u: { return textureSample(luxelTexture0, luxelSampler15, uv); }
    default: { return textureSample(luxelTexture0, luxelSampler0, uv); }
  }
}
fn luxelSampleTexture1(samplerIndex: u32, uv: vec2<f32>) -> vec4<f32> {
  switch samplerIndex {
    case 0u: { return textureSample(luxelTexture1, luxelSampler0, uv); }
    case 1u: { return textureSample(luxelTexture1, luxelSampler1, uv); }
    case 2u: { return textureSample(luxelTexture1, luxelSampler2, uv); }
    case 3u: { return textureSample(luxelTexture1, luxelSampler3, uv); }
    case 4u: { return textureSample(luxelTexture1, luxelSampler4, uv); }
    case 5u: { return textureSample(luxelTexture1, luxelSampler5, uv); }
    case 6u: { return textureSample(luxelTexture1, luxelSampler6, uv); }
    case 7u: { return textureSample(luxelTexture1, luxelSampler7, uv); }
    case 8u: { return textureSample(luxelTexture1, luxelSampler8, uv); }
    case 9u: { return textureSample(luxelTexture1, luxelSampler9, uv); }
    case 10u: { return textureSample(luxelTexture1, luxelSampler10, uv); }
    case 11u: { return textureSample(luxelTexture1, luxelSampler11, uv); }
    case 12u: { return textureSample(luxelTexture1, luxelSampler12, uv); }
    case 13u: { return textureSample(luxelTexture1, luxelSampler13, uv); }
    case 14u: { return textureSample(luxelTexture1, luxelSampler14, uv); }
    case 15u: { return textureSample(luxelTexture1, luxelSampler15, uv); }
    default: { return textureSample(luxelTexture1, luxelSampler0, uv); }
  }
}
fn luxelSampleTexture2(samplerIndex: u32, uv: vec2<f32>) -> vec4<f32> {
  switch samplerIndex {
    case 0u: { return textureSample(luxelTexture2, luxelSampler0, uv); }
    case 1u: { return textureSample(luxelTexture2, luxelSampler1, uv); }
    case 2u: { return textureSample(luxelTexture2, luxelSampler2, uv); }
    case 3u: { return textureSample(luxelTexture2, luxelSampler3, uv); }
    case 4u: { return textureSample(luxelTexture2, luxelSampler4, uv); }
    case 5u: { return textureSample(luxelTexture2, luxelSampler5, uv); }
    case 6u: { return textureSample(luxelTexture2, luxelSampler6, uv); }
    case 7u: { return textureSample(luxelTexture2, luxelSampler7, uv); }
    case 8u: { return textureSample(luxelTexture2, luxelSampler8, uv); }
    case 9u: { return textureSample(luxelTexture2, luxelSampler9, uv); }
    case 10u: { return textureSample(luxelTexture2, luxelSampler10, uv); }
    case 11u: { return textureSample(luxelTexture2, luxelSampler11, uv); }
    case 12u: { return textureSample(luxelTexture2, luxelSampler12, uv); }
    case 13u: { return textureSample(luxelTexture2, luxelSampler13, uv); }
    case 14u: { return textureSample(luxelTexture2, luxelSampler14, uv); }
    case 15u: { return textureSample(luxelTexture2, luxelSampler15, uv); }
    default: { return textureSample(luxelTexture2, luxelSampler0, uv); }
  }
}
fn luxelSampleTexture3(samplerIndex: u32, uv: vec2<f32>) -> vec4<f32> {
  switch samplerIndex {
    case 0u: { return textureSample(luxelTexture3, luxelSampler0, uv); }
    case 1u: { return textureSample(luxelTexture3, luxelSampler1, uv); }
    case 2u: { return textureSample(luxelTexture3, luxelSampler2, uv); }
    case 3u: { return textureSample(luxelTexture3, luxelSampler3, uv); }
    case 4u: { return textureSample(luxelTexture3, luxelSampler4, uv); }
    case 5u: { return textureSample(luxelTexture3, luxelSampler5, uv); }
    case 6u: { return textureSample(luxelTexture3, luxelSampler6, uv); }
    case 7u: { return textureSample(luxelTexture3, luxelSampler7, uv); }
    case 8u: { return textureSample(luxelTexture3, luxelSampler8, uv); }
    case 9u: { return textureSample(luxelTexture3, luxelSampler9, uv); }
    case 10u: { return textureSample(luxelTexture3, luxelSampler10, uv); }
    case 11u: { return textureSample(luxelTexture3, luxelSampler11, uv); }
    case 12u: { return textureSample(luxelTexture3, luxelSampler12, uv); }
    case 13u: { return textureSample(luxelTexture3, luxelSampler13, uv); }
    case 14u: { return textureSample(luxelTexture3, luxelSampler14, uv); }
    case 15u: { return textureSample(luxelTexture3, luxelSampler15, uv); }
    default: { return textureSample(luxelTexture3, luxelSampler0, uv); }
  }
}
fn luxelSampleTexture4(samplerIndex: u32, uv: vec2<f32>) -> vec4<f32> {
  switch samplerIndex {
    case 0u: { return textureSample(luxelTexture4, luxelSampler0, uv); }
    case 1u: { return textureSample(luxelTexture4, luxelSampler1, uv); }
    case 2u: { return textureSample(luxelTexture4, luxelSampler2, uv); }
    case 3u: { return textureSample(luxelTexture4, luxelSampler3, uv); }
    case 4u: { return textureSample(luxelTexture4, luxelSampler4, uv); }
    case 5u: { return textureSample(luxelTexture4, luxelSampler5, uv); }
    case 6u: { return textureSample(luxelTexture4, luxelSampler6, uv); }
    case 7u: { return textureSample(luxelTexture4, luxelSampler7, uv); }
    case 8u: { return textureSample(luxelTexture4, luxelSampler8, uv); }
    case 9u: { return textureSample(luxelTexture4, luxelSampler9, uv); }
    case 10u: { return textureSample(luxelTexture4, luxelSampler10, uv); }
    case 11u: { return textureSample(luxelTexture4, luxelSampler11, uv); }
    case 12u: { return textureSample(luxelTexture4, luxelSampler12, uv); }
    case 13u: { return textureSample(luxelTexture4, luxelSampler13, uv); }
    case 14u: { return textureSample(luxelTexture4, luxelSampler14, uv); }
    case 15u: { return textureSample(luxelTexture4, luxelSampler15, uv); }
    default: { return textureSample(luxelTexture4, luxelSampler0, uv); }
  }
}
fn luxelSampleTexture5(samplerIndex: u32, uv: vec2<f32>) -> vec4<f32> {
  switch samplerIndex {
    case 0u: { return textureSample(luxelTexture5, luxelSampler0, uv); }
    case 1u: { return textureSample(luxelTexture5, luxelSampler1, uv); }
    case 2u: { return textureSample(luxelTexture5, luxelSampler2, uv); }
    case 3u: { return textureSample(luxelTexture5, luxelSampler3, uv); }
    case 4u: { return textureSample(luxelTexture5, luxelSampler4, uv); }
    case 5u: { return textureSample(luxelTexture5, luxelSampler5, uv); }
    case 6u: { return textureSample(luxelTexture5, luxelSampler6, uv); }
    case 7u: { return textureSample(luxelTexture5, luxelSampler7, uv); }
    case 8u: { return textureSample(luxelTexture5, luxelSampler8, uv); }
    case 9u: { return textureSample(luxelTexture5, luxelSampler9, uv); }
    case 10u: { return textureSample(luxelTexture5, luxelSampler10, uv); }
    case 11u: { return textureSample(luxelTexture5, luxelSampler11, uv); }
    case 12u: { return textureSample(luxelTexture5, luxelSampler12, uv); }
    case 13u: { return textureSample(luxelTexture5, luxelSampler13, uv); }
    case 14u: { return textureSample(luxelTexture5, luxelSampler14, uv); }
    case 15u: { return textureSample(luxelTexture5, luxelSampler15, uv); }
    default: { return textureSample(luxelTexture5, luxelSampler0, uv); }
  }
}
fn luxelSampleTexture6(samplerIndex: u32, uv: vec2<f32>) -> vec4<f32> {
  switch samplerIndex {
    case 0u: { return textureSample(luxelTexture6, luxelSampler0, uv); }
    case 1u: { return textureSample(luxelTexture6, luxelSampler1, uv); }
    case 2u: { return textureSample(luxelTexture6, luxelSampler2, uv); }
    case 3u: { return textureSample(luxelTexture6, luxelSampler3, uv); }
    case 4u: { return textureSample(luxelTexture6, luxelSampler4, uv); }
    case 5u: { return textureSample(luxelTexture6, luxelSampler5, uv); }
    case 6u: { return textureSample(luxelTexture6, luxelSampler6, uv); }
    case 7u: { return textureSample(luxelTexture6, luxelSampler7, uv); }
    case 8u: { return textureSample(luxelTexture6, luxelSampler8, uv); }
    case 9u: { return textureSample(luxelTexture6, luxelSampler9, uv); }
    case 10u: { return textureSample(luxelTexture6, luxelSampler10, uv); }
    case 11u: { return textureSample(luxelTexture6, luxelSampler11, uv); }
    case 12u: { return textureSample(luxelTexture6, luxelSampler12, uv); }
    case 13u: { return textureSample(luxelTexture6, luxelSampler13, uv); }
    case 14u: { return textureSample(luxelTexture6, luxelSampler14, uv); }
    case 15u: { return textureSample(luxelTexture6, luxelSampler15, uv); }
    default: { return textureSample(luxelTexture6, luxelSampler0, uv); }
  }
}
fn luxelSampleTexture7(samplerIndex: u32, uv: vec2<f32>) -> vec4<f32> {
  switch samplerIndex {
    case 0u: { return textureSample(luxelTexture7, luxelSampler0, uv); }
    case 1u: { return textureSample(luxelTexture7, luxelSampler1, uv); }
    case 2u: { return textureSample(luxelTexture7, luxelSampler2, uv); }
    case 3u: { return textureSample(luxelTexture7, luxelSampler3, uv); }
    case 4u: { return textureSample(luxelTexture7, luxelSampler4, uv); }
    case 5u: { return textureSample(luxelTexture7, luxelSampler5, uv); }
    case 6u: { return textureSample(luxelTexture7, luxelSampler6, uv); }
    case 7u: { return textureSample(luxelTexture7, luxelSampler7, uv); }
    case 8u: { return textureSample(luxelTexture7, luxelSampler8, uv); }
    case 9u: { return textureSample(luxelTexture7, luxelSampler9, uv); }
    case 10u: { return textureSample(luxelTexture7, luxelSampler10, uv); }
    case 11u: { return textureSample(luxelTexture7, luxelSampler11, uv); }
    case 12u: { return textureSample(luxelTexture7, luxelSampler12, uv); }
    case 13u: { return textureSample(luxelTexture7, luxelSampler13, uv); }
    case 14u: { return textureSample(luxelTexture7, luxelSampler14, uv); }
    case 15u: { return textureSample(luxelTexture7, luxelSampler15, uv); }
    default: { return textureSample(luxelTexture7, luxelSampler0, uv); }
  }
}
fn luxelSampleTexture8(samplerIndex: u32, uv: vec2<f32>) -> vec4<f32> {
  switch samplerIndex {
    case 0u: { return textureSample(luxelTexture8, luxelSampler0, uv); }
    case 1u: { return textureSample(luxelTexture8, luxelSampler1, uv); }
    case 2u: { return textureSample(luxelTexture8, luxelSampler2, uv); }
    case 3u: { return textureSample(luxelTexture8, luxelSampler3, uv); }
    case 4u: { return textureSample(luxelTexture8, luxelSampler4, uv); }
    case 5u: { return textureSample(luxelTexture8, luxelSampler5, uv); }
    case 6u: { return textureSample(luxelTexture8, luxelSampler6, uv); }
    case 7u: { return textureSample(luxelTexture8, luxelSampler7, uv); }
    case 8u: { return textureSample(luxelTexture8, luxelSampler8, uv); }
    case 9u: { return textureSample(luxelTexture8, luxelSampler9, uv); }
    case 10u: { return textureSample(luxelTexture8, luxelSampler10, uv); }
    case 11u: { return textureSample(luxelTexture8, luxelSampler11, uv); }
    case 12u: { return textureSample(luxelTexture8, luxelSampler12, uv); }
    case 13u: { return textureSample(luxelTexture8, luxelSampler13, uv); }
    case 14u: { return textureSample(luxelTexture8, luxelSampler14, uv); }
    case 15u: { return textureSample(luxelTexture8, luxelSampler15, uv); }
    default: { return textureSample(luxelTexture8, luxelSampler0, uv); }
  }
}
fn luxelSampleTexture9(samplerIndex: u32, uv: vec2<f32>) -> vec4<f32> {
  switch samplerIndex {
    case 0u: { return textureSample(luxelTexture9, luxelSampler0, uv); }
    case 1u: { return textureSample(luxelTexture9, luxelSampler1, uv); }
    case 2u: { return textureSample(luxelTexture9, luxelSampler2, uv); }
    case 3u: { return textureSample(luxelTexture9, luxelSampler3, uv); }
    case 4u: { return textureSample(luxelTexture9, luxelSampler4, uv); }
    case 5u: { return textureSample(luxelTexture9, luxelSampler5, uv); }
    case 6u: { return textureSample(luxelTexture9, luxelSampler6, uv); }
    case 7u: { return textureSample(luxelTexture9, luxelSampler7, uv); }
    case 8u: { return textureSample(luxelTexture9, luxelSampler8, uv); }
    case 9u: { return textureSample(luxelTexture9, luxelSampler9, uv); }
    case 10u: { return textureSample(luxelTexture9, luxelSampler10, uv); }
    case 11u: { return textureSample(luxelTexture9, luxelSampler11, uv); }
    case 12u: { return textureSample(luxelTexture9, luxelSampler12, uv); }
    case 13u: { return textureSample(luxelTexture9, luxelSampler13, uv); }
    case 14u: { return textureSample(luxelTexture9, luxelSampler14, uv); }
    case 15u: { return textureSample(luxelTexture9, luxelSampler15, uv); }
    default: { return textureSample(luxelTexture9, luxelSampler0, uv); }
  }
}
fn luxelSampleTexture10(samplerIndex: u32, uv: vec2<f32>) -> vec4<f32> {
  switch samplerIndex {
    case 0u: { return textureSample(luxelTexture10, luxelSampler0, uv); }
    case 1u: { return textureSample(luxelTexture10, luxelSampler1, uv); }
    case 2u: { return textureSample(luxelTexture10, luxelSampler2, uv); }
    case 3u: { return textureSample(luxelTexture10, luxelSampler3, uv); }
    case 4u: { return textureSample(luxelTexture10, luxelSampler4, uv); }
    case 5u: { return textureSample(luxelTexture10, luxelSampler5, uv); }
    case 6u: { return textureSample(luxelTexture10, luxelSampler6, uv); }
    case 7u: { return textureSample(luxelTexture10, luxelSampler7, uv); }
    case 8u: { return textureSample(luxelTexture10, luxelSampler8, uv); }
    case 9u: { return textureSample(luxelTexture10, luxelSampler9, uv); }
    case 10u: { return textureSample(luxelTexture10, luxelSampler10, uv); }
    case 11u: { return textureSample(luxelTexture10, luxelSampler11, uv); }
    case 12u: { return textureSample(luxelTexture10, luxelSampler12, uv); }
    case 13u: { return textureSample(luxelTexture10, luxelSampler13, uv); }
    case 14u: { return textureSample(luxelTexture10, luxelSampler14, uv); }
    case 15u: { return textureSample(luxelTexture10, luxelSampler15, uv); }
    default: { return textureSample(luxelTexture10, luxelSampler0, uv); }
  }
}
fn luxelSampleTexture11(samplerIndex: u32, uv: vec2<f32>) -> vec4<f32> {
  switch samplerIndex {
    case 0u: { return textureSample(luxelTexture11, luxelSampler0, uv); }
    case 1u: { return textureSample(luxelTexture11, luxelSampler1, uv); }
    case 2u: { return textureSample(luxelTexture11, luxelSampler2, uv); }
    case 3u: { return textureSample(luxelTexture11, luxelSampler3, uv); }
    case 4u: { return textureSample(luxelTexture11, luxelSampler4, uv); }
    case 5u: { return textureSample(luxelTexture11, luxelSampler5, uv); }
    case 6u: { return textureSample(luxelTexture11, luxelSampler6, uv); }
    case 7u: { return textureSample(luxelTexture11, luxelSampler7, uv); }
    case 8u: { return textureSample(luxelTexture11, luxelSampler8, uv); }
    case 9u: { return textureSample(luxelTexture11, luxelSampler9, uv); }
    case 10u: { return textureSample(luxelTexture11, luxelSampler10, uv); }
    case 11u: { return textureSample(luxelTexture11, luxelSampler11, uv); }
    case 12u: { return textureSample(luxelTexture11, luxelSampler12, uv); }
    case 13u: { return textureSample(luxelTexture11, luxelSampler13, uv); }
    case 14u: { return textureSample(luxelTexture11, luxelSampler14, uv); }
    case 15u: { return textureSample(luxelTexture11, luxelSampler15, uv); }
    default: { return textureSample(luxelTexture11, luxelSampler0, uv); }
  }
}
fn luxelSampleTexture12(samplerIndex: u32, uv: vec2<f32>) -> vec4<f32> {
  switch samplerIndex {
    case 0u: { return textureSample(luxelTexture12, luxelSampler0, uv); }
    case 1u: { return textureSample(luxelTexture12, luxelSampler1, uv); }
    case 2u: { return textureSample(luxelTexture12, luxelSampler2, uv); }
    case 3u: { return textureSample(luxelTexture12, luxelSampler3, uv); }
    case 4u: { return textureSample(luxelTexture12, luxelSampler4, uv); }
    case 5u: { return textureSample(luxelTexture12, luxelSampler5, uv); }
    case 6u: { return textureSample(luxelTexture12, luxelSampler6, uv); }
    case 7u: { return textureSample(luxelTexture12, luxelSampler7, uv); }
    case 8u: { return textureSample(luxelTexture12, luxelSampler8, uv); }
    case 9u: { return textureSample(luxelTexture12, luxelSampler9, uv); }
    case 10u: { return textureSample(luxelTexture12, luxelSampler10, uv); }
    case 11u: { return textureSample(luxelTexture12, luxelSampler11, uv); }
    case 12u: { return textureSample(luxelTexture12, luxelSampler12, uv); }
    case 13u: { return textureSample(luxelTexture12, luxelSampler13, uv); }
    case 14u: { return textureSample(luxelTexture12, luxelSampler14, uv); }
    case 15u: { return textureSample(luxelTexture12, luxelSampler15, uv); }
    default: { return textureSample(luxelTexture12, luxelSampler0, uv); }
  }
}
fn luxelSampleTexture13(samplerIndex: u32, uv: vec2<f32>) -> vec4<f32> {
  switch samplerIndex {
    case 0u: { return textureSample(luxelTexture13, luxelSampler0, uv); }
    case 1u: { return textureSample(luxelTexture13, luxelSampler1, uv); }
    case 2u: { return textureSample(luxelTexture13, luxelSampler2, uv); }
    case 3u: { return textureSample(luxelTexture13, luxelSampler3, uv); }
    case 4u: { return textureSample(luxelTexture13, luxelSampler4, uv); }
    case 5u: { return textureSample(luxelTexture13, luxelSampler5, uv); }
    case 6u: { return textureSample(luxelTexture13, luxelSampler6, uv); }
    case 7u: { return textureSample(luxelTexture13, luxelSampler7, uv); }
    case 8u: { return textureSample(luxelTexture13, luxelSampler8, uv); }
    case 9u: { return textureSample(luxelTexture13, luxelSampler9, uv); }
    case 10u: { return textureSample(luxelTexture13, luxelSampler10, uv); }
    case 11u: { return textureSample(luxelTexture13, luxelSampler11, uv); }
    case 12u: { return textureSample(luxelTexture13, luxelSampler12, uv); }
    case 13u: { return textureSample(luxelTexture13, luxelSampler13, uv); }
    case 14u: { return textureSample(luxelTexture13, luxelSampler14, uv); }
    case 15u: { return textureSample(luxelTexture13, luxelSampler15, uv); }
    default: { return textureSample(luxelTexture13, luxelSampler0, uv); }
  }
}
fn luxelSampleTexture14(samplerIndex: u32, uv: vec2<f32>) -> vec4<f32> {
  switch samplerIndex {
    case 0u: { return textureSample(luxelTexture14, luxelSampler0, uv); }
    case 1u: { return textureSample(luxelTexture14, luxelSampler1, uv); }
    case 2u: { return textureSample(luxelTexture14, luxelSampler2, uv); }
    case 3u: { return textureSample(luxelTexture14, luxelSampler3, uv); }
    case 4u: { return textureSample(luxelTexture14, luxelSampler4, uv); }
    case 5u: { return textureSample(luxelTexture14, luxelSampler5, uv); }
    case 6u: { return textureSample(luxelTexture14, luxelSampler6, uv); }
    case 7u: { return textureSample(luxelTexture14, luxelSampler7, uv); }
    case 8u: { return textureSample(luxelTexture14, luxelSampler8, uv); }
    case 9u: { return textureSample(luxelTexture14, luxelSampler9, uv); }
    case 10u: { return textureSample(luxelTexture14, luxelSampler10, uv); }
    case 11u: { return textureSample(luxelTexture14, luxelSampler11, uv); }
    case 12u: { return textureSample(luxelTexture14, luxelSampler12, uv); }
    case 13u: { return textureSample(luxelTexture14, luxelSampler13, uv); }
    case 14u: { return textureSample(luxelTexture14, luxelSampler14, uv); }
    case 15u: { return textureSample(luxelTexture14, luxelSampler15, uv); }
    default: { return textureSample(luxelTexture14, luxelSampler0, uv); }
  }
}
fn luxelSampleTexture15(samplerIndex: u32, uv: vec2<f32>) -> vec4<f32> {
  switch samplerIndex {
    case 0u: { return textureSample(luxelTexture15, luxelSampler0, uv); }
    case 1u: { return textureSample(luxelTexture15, luxelSampler1, uv); }
    case 2u: { return textureSample(luxelTexture15, luxelSampler2, uv); }
    case 3u: { return textureSample(luxelTexture15, luxelSampler3, uv); }
    case 4u: { return textureSample(luxelTexture15, luxelSampler4, uv); }
    case 5u: { return textureSample(luxelTexture15, luxelSampler5, uv); }
    case 6u: { return textureSample(luxelTexture15, luxelSampler6, uv); }
    case 7u: { return textureSample(luxelTexture15, luxelSampler7, uv); }
    case 8u: { return textureSample(luxelTexture15, luxelSampler8, uv); }
    case 9u: { return textureSample(luxelTexture15, luxelSampler9, uv); }
    case 10u: { return textureSample(luxelTexture15, luxelSampler10, uv); }
    case 11u: { return textureSample(luxelTexture15, luxelSampler11, uv); }
    case 12u: { return textureSample(luxelTexture15, luxelSampler12, uv); }
    case 13u: { return textureSample(luxelTexture15, luxelSampler13, uv); }
    case 14u: { return textureSample(luxelTexture15, luxelSampler14, uv); }
    case 15u: { return textureSample(luxelTexture15, luxelSampler15, uv); }
    default: { return textureSample(luxelTexture15, luxelSampler0, uv); }
  }
}
fn luxelSample2d(textureIndex: u32, samplerIndex: u32, uv: vec2<f32>) -> vec4<f32> {
  switch textureIndex {
    case 0u: { return luxelSampleTexture0(samplerIndex, uv); }
    case 1u: { return luxelSampleTexture1(samplerIndex, uv); }
    case 2u: { return luxelSampleTexture2(samplerIndex, uv); }
    case 3u: { return luxelSampleTexture3(samplerIndex, uv); }
    case 4u: { return luxelSampleTexture4(samplerIndex, uv); }
    case 5u: { return luxelSampleTexture5(samplerIndex, uv); }
    case 6u: { return luxelSampleTexture6(samplerIndex, uv); }
    case 7u: { return luxelSampleTexture7(samplerIndex, uv); }
    case 8u: { return luxelSampleTexture8(samplerIndex, uv); }
    case 9u: { return luxelSampleTexture9(samplerIndex, uv); }
    case 10u: { return luxelSampleTexture10(samplerIndex, uv); }
    case 11u: { return luxelSampleTexture11(samplerIndex, uv); }
    case 12u: { return luxelSampleTexture12(samplerIndex, uv); }
    case 13u: { return luxelSampleTexture13(samplerIndex, uv); }
    case 14u: { return luxelSampleTexture14(samplerIndex, uv); }
    case 15u: { return luxelSampleTexture15(samplerIndex, uv); }
    default: { return luxelSampleTexture0(samplerIndex, uv); }
  }
}

struct _MatrixStorage_float4x4_ColMajorstd430_0
{
    @align(16) data_0 : array<vec4<f32>, i32(4)>,
};

struct RootArgs_std430_0
{
    @align(16) viewProj_0 : _MatrixStorage_float4x4_ColMajorstd430_0,
    @align(16) vertexBufIndex_0 : u32,
    @align(4) indexBufIndex_0 : u32,
    @align(8) instanceBufIndex_0 : u32,
    @align(4) materialBufIndex_0 : u32,
    @align(16) _pad0_0 : u32,
    @align(4) _pad1_0 : u32,
    @align(8) _pad2_0 : u32,
    @align(4) _pad3_0 : u32,
};

@group(0) @binding(1) var<uniform> args_0 : RootArgs_std430_0;
@group(0) @binding(0) var<storage, read> g_buffers_0 : array<u32>;



struct VsOut_0
{
    @builtin(position) svPos_0 : vec4<f32>,
    @location(0) normal_0 : vec3<f32>,
    @location(2) uv_0 : vec2<f32>,
    @interpolate(flat) @location(1) matIdx_0 : u32,
};

@vertex
fn vsMain(@builtin(vertex_index) vid_0 : u32, @builtin(instance_index) iid_0 : u32) -> VsOut_0
{
    var actualVid_0 : u32;
    if((args_0.indexBufIndex_0) == u32(4294967295))
    {
        actualVid_0 = vid_0;
    }
    else
    {
        var _S1 : u32 = g_buffers_0[(((args_0.indexBufIndex_0) * 64u) + ((vid_0 * u32(4))/4))];
        actualVid_0 = _S1;
    }
    var vAddr_0 : u32 = actualVid_0 * u32(32);
    var _S2 : u32 = args_0.vertexBufIndex_0;
    var _S3 : u32 = g_buffers_0[(((args_0.vertexBufIndex_0) * 64u) + ((vAddr_0)/4))];
    var _S4 : u32 = g_buffers_0[(((_S2) * 64u) + ((vAddr_0 + u32(4))/4))];
    var _S5 : u32 = g_buffers_0[(((_S2) * 64u) + ((vAddr_0 + u32(8))/4))];
    var vPos_0 : vec3<f32> = (bitcast<vec3<f32>>((vec3<u32>(_S3, _S4, _S5))));
    var _S6 : u32 = args_0.vertexBufIndex_0;
    var _S7 : u32 = vAddr_0 + u32(12);
    var _S8 : u32 = g_buffers_0[(((args_0.vertexBufIndex_0) * 64u) + ((_S7)/4))];
    var _S9 : u32 = g_buffers_0[(((_S6) * 64u) + ((_S7 + u32(4))/4))];
    var _S10 : u32 = g_buffers_0[(((_S6) * 64u) + ((_S7 + u32(8))/4))];
    var vNormal_0 : vec3<f32> = (bitcast<vec3<f32>>((vec3<u32>(_S8, _S9, _S10))));
    var _S11 : u32 = args_0.vertexBufIndex_0;
    var _S12 : u32 = vAddr_0 + u32(24);
    var _S13 : u32 = g_buffers_0[(((args_0.vertexBufIndex_0) * 64u) + ((_S12)/4))];
    var _S14 : u32 = g_buffers_0[(((_S11) * 64u) + ((_S12 + u32(4))/4))];
    var vUv_0 : vec2<f32> = (bitcast<vec2<f32>>((vec2<u32>(_S13, _S14))));
    var iAddr_0 : u32 = iid_0 * u32(80);
    var _S15 : u32 = args_0.instanceBufIndex_0;
    var _S16 : u32 = g_buffers_0[(((args_0.instanceBufIndex_0) * 64u) + ((iAddr_0)/4))];
    var _S17 : u32 = g_buffers_0[(((_S15) * 64u) + ((iAddr_0 + u32(4))/4))];
    var _S18 : u32 = g_buffers_0[(((_S15) * 64u) + ((iAddr_0 + u32(8))/4))];
    var _S19 : u32 = g_buffers_0[(((_S15) * 64u) + ((iAddr_0 + u32(12))/4))];
    var r0_0 : vec4<f32> = (bitcast<vec4<f32>>((vec4<u32>(_S16, _S17, _S18, _S19))));
    var _S20 : u32 = args_0.instanceBufIndex_0;
    var _S21 : u32 = iAddr_0 + u32(16);
    var _S22 : u32 = g_buffers_0[(((args_0.instanceBufIndex_0) * 64u) + ((_S21)/4))];
    var _S23 : u32 = g_buffers_0[(((_S20) * 64u) + ((_S21 + u32(4))/4))];
    var _S24 : u32 = g_buffers_0[(((_S20) * 64u) + ((_S21 + u32(8))/4))];
    var _S25 : u32 = g_buffers_0[(((_S20) * 64u) + ((_S21 + u32(12))/4))];
    var r1_0 : vec4<f32> = (bitcast<vec4<f32>>((vec4<u32>(_S22, _S23, _S24, _S25))));
    var _S26 : u32 = args_0.instanceBufIndex_0;
    var _S27 : u32 = iAddr_0 + u32(32);
    var _S28 : u32 = g_buffers_0[(((args_0.instanceBufIndex_0) * 64u) + ((_S27)/4))];
    var _S29 : u32 = g_buffers_0[(((_S26) * 64u) + ((_S27 + u32(4))/4))];
    var _S30 : u32 = g_buffers_0[(((_S26) * 64u) + ((_S27 + u32(8))/4))];
    var _S31 : u32 = g_buffers_0[(((_S26) * 64u) + ((_S27 + u32(12))/4))];
    var r2_0 : vec4<f32> = (bitcast<vec4<f32>>((vec4<u32>(_S28, _S29, _S30, _S31))));
    var _S32 : u32 = args_0.instanceBufIndex_0;
    var _S33 : u32 = iAddr_0 + u32(48);
    var _S34 : u32 = g_buffers_0[(((args_0.instanceBufIndex_0) * 64u) + ((_S33)/4))];
    var _S35 : u32 = g_buffers_0[(((_S32) * 64u) + ((_S33 + u32(4))/4))];
    var _S36 : u32 = g_buffers_0[(((_S32) * 64u) + ((_S33 + u32(8))/4))];
    var _S37 : u32 = g_buffers_0[(((_S32) * 64u) + ((_S33 + u32(12))/4))];
    var world_0 : mat4x4<f32> = mat4x4<f32>(r0_0, r1_0, r2_0, (bitcast<vec4<f32>>((vec4<u32>(_S34, _S35, _S36, _S37)))));
    var _S38 : u32 = g_buffers_0[(((args_0.instanceBufIndex_0) * 64u) + ((iAddr_0 + u32(64))/4))];
    var worldN_0 : vec3<f32> = (((mat3x3<f32>(world_0[i32(0)].xyz, world_0[i32(1)].xyz, world_0[i32(2)].xyz)) * (vNormal_0)));
    var o_0 : VsOut_0;
    o_0.svPos_0 = (((mat4x4<f32>(args_0.viewProj_0.data_0[i32(0)][i32(0)], args_0.viewProj_0.data_0[i32(1)][i32(0)], args_0.viewProj_0.data_0[i32(2)][i32(0)], args_0.viewProj_0.data_0[i32(3)][i32(0)], args_0.viewProj_0.data_0[i32(0)][i32(1)], args_0.viewProj_0.data_0[i32(1)][i32(1)], args_0.viewProj_0.data_0[i32(2)][i32(1)], args_0.viewProj_0.data_0[i32(3)][i32(1)], args_0.viewProj_0.data_0[i32(0)][i32(2)], args_0.viewProj_0.data_0[i32(1)][i32(2)], args_0.viewProj_0.data_0[i32(2)][i32(2)], args_0.viewProj_0.data_0[i32(3)][i32(2)], args_0.viewProj_0.data_0[i32(0)][i32(3)], args_0.viewProj_0.data_0[i32(1)][i32(3)], args_0.viewProj_0.data_0[i32(2)][i32(3)], args_0.viewProj_0.data_0[i32(3)][i32(3)])) * ((((world_0) * (vec4<f32>(vPos_0, 1.0f)))))));
    o_0.normal_0 = normalize(worldN_0);
    o_0.uv_0 = vUv_0;
    o_0.matIdx_0 = _S38;
    return o_0;
}

struct pixelOutput_0
{
    @location(0) output_0 : vec4<f32>,
};

struct pixelInput_0
{
    @location(0) normal_1 : vec3<f32>,
    @location(2) uv_1 : vec2<f32>,
    @interpolate(flat) @location(1) matIdx_1 : u32,
};

@fragment
fn psMain( _S39 : pixelInput_0, @builtin(position) svPos_1 : vec4<f32>) -> pixelOutput_0
{
    var mAddr_0 : u32 = _S39.matIdx_1 * u32(32);
    var _S40 : u32 = args_0.materialBufIndex_0;
    var _S41 : u32 = g_buffers_0[(((args_0.materialBufIndex_0) * 64u) + ((mAddr_0)/4))];
    var _S42 : u32 = g_buffers_0[(((_S40) * 64u) + ((mAddr_0 + u32(4))/4))];
    var _S43 : u32 = g_buffers_0[(((_S40) * 64u) + ((mAddr_0 + u32(8))/4))];
    var _S44 : u32 = g_buffers_0[(((_S40) * 64u) + ((mAddr_0 + u32(12))/4))];
    var baseColor_0 : vec4<f32> = (bitcast<vec4<f32>>((vec4<u32>(_S41, _S42, _S43, _S44))));
    var _S45 : u32 = g_buffers_0[(((args_0.materialBufIndex_0) * 64u) + ((mAddr_0 + u32(16))/4))];
    var _S46 : u32 = g_buffers_0[(((args_0.materialBufIndex_0) * 64u) + ((mAddr_0 + u32(20))/4))];
    var _S47 : u32 = g_buffers_0[(((args_0.materialBufIndex_0) * 64u) + ((mAddr_0 + u32(24))/4))];
    var albedo_0 : vec3<f32> = baseColor_0.xyz;
    var albedo_1 : vec3<f32>;
    if(((_S47 & (u32(1)))) != u32(0))
    {
        albedo_1 = albedo_0 * (luxelSample2d(_S45, _S46, _S39.uv_1)).xyz;
    }
    else
    {
        albedo_1 = albedo_0;
    }
    var _S48 : pixelOutput_0 = pixelOutput_0( vec4<f32>(albedo_1 * vec3<f32>((0.30000001192092896f + 0.75f * saturate(dot(normalize(_S39.normal_1), normalize(vec3<f32>(0.60000002384185791f, 0.85000002384185791f, 0.40000000596046448f)))))), 1.0f) );
    return _S48;
}
