// Generated by Slang 2026.14 + Luxel.ShaderWgslGen. Do not edit.
struct _MatrixStorage_float4x4_ColMajorstd430_0
{
    @align(16) data_0 : array<vec4<f32>, i32(4)>,
};

struct ShadowArgs_std430_0
{
    @align(16) lightVP_0 : _MatrixStorage_float4x4_ColMajorstd430_0,
    @align(16) vertexBufIndex_0 : u32,
    @align(4) instanceBufIndex_0 : u32,
    @align(8) _pad0_0 : u32,
    @align(4) _pad1_0 : u32,
};

@group(0) @binding(1) var<uniform> args_0 : ShadowArgs_std430_0;
@group(0) @binding(0) var<storage, read> g_buffers_0 : array<u32>;

struct VsOut_0
{
    @builtin(position) svPos_0 : vec4<f32>,
};

@vertex
fn vsMain(@builtin(vertex_index) vid_0 : u32, @builtin(instance_index) iid_0 : u32) -> VsOut_0
{
    var vAddr_0 : u32 = vid_0 * u32(24);
    var _S1 : u32 = args_0.vertexBufIndex_0;
    var _S2 : u32 = g_buffers_0[(((args_0.vertexBufIndex_0) * 64u) + ((vAddr_0)/4))];
    var _S3 : u32 = g_buffers_0[(((_S1) * 64u) + ((vAddr_0 + u32(4))/4))];
    var _S4 : u32 = g_buffers_0[(((_S1) * 64u) + ((vAddr_0 + u32(8))/4))];
    var vPos_0 : vec3<f32> = (bitcast<vec3<f32>>((vec3<u32>(_S2, _S3, _S4))));
    var iAddr_0 : u32 = iid_0 * u32(80);
    var _S5 : u32 = args_0.instanceBufIndex_0;
    var _S6 : u32 = g_buffers_0[(((args_0.instanceBufIndex_0) * 64u) + ((iAddr_0)/4))];
    var _S7 : u32 = g_buffers_0[(((_S5) * 64u) + ((iAddr_0 + u32(4))/4))];
    var _S8 : u32 = g_buffers_0[(((_S5) * 64u) + ((iAddr_0 + u32(8))/4))];
    var _S9 : u32 = g_buffers_0[(((_S5) * 64u) + ((iAddr_0 + u32(12))/4))];
    var r0_0 : vec4<f32> = (bitcast<vec4<f32>>((vec4<u32>(_S6, _S7, _S8, _S9))));
    var _S10 : u32 = args_0.instanceBufIndex_0;
    var _S11 : u32 = iAddr_0 + u32(16);
    var _S12 : u32 = g_buffers_0[(((args_0.instanceBufIndex_0) * 64u) + ((_S11)/4))];
    var _S13 : u32 = g_buffers_0[(((_S10) * 64u) + ((_S11 + u32(4))/4))];
    var _S14 : u32 = g_buffers_0[(((_S10) * 64u) + ((_S11 + u32(8))/4))];
    var _S15 : u32 = g_buffers_0[(((_S10) * 64u) + ((_S11 + u32(12))/4))];
    var r1_0 : vec4<f32> = (bitcast<vec4<f32>>((vec4<u32>(_S12, _S13, _S14, _S15))));
    var _S16 : u32 = args_0.instanceBufIndex_0;
    var _S17 : u32 = iAddr_0 + u32(32);
    var _S18 : u32 = g_buffers_0[(((args_0.instanceBufIndex_0) * 64u) + ((_S17)/4))];
    var _S19 : u32 = g_buffers_0[(((_S16) * 64u) + ((_S17 + u32(4))/4))];
    var _S20 : u32 = g_buffers_0[(((_S16) * 64u) + ((_S17 + u32(8))/4))];
    var _S21 : u32 = g_buffers_0[(((_S16) * 64u) + ((_S17 + u32(12))/4))];
    var r2_0 : vec4<f32> = (bitcast<vec4<f32>>((vec4<u32>(_S18, _S19, _S20, _S21))));
    var _S22 : u32 = args_0.instanceBufIndex_0;
    var _S23 : u32 = iAddr_0 + u32(48);
    var _S24 : u32 = g_buffers_0[(((args_0.instanceBufIndex_0) * 64u) + ((_S23)/4))];
    var _S25 : u32 = g_buffers_0[(((_S22) * 64u) + ((_S23 + u32(4))/4))];
    var _S26 : u32 = g_buffers_0[(((_S22) * 64u) + ((_S23 + u32(8))/4))];
    var _S27 : u32 = g_buffers_0[(((_S22) * 64u) + ((_S23 + u32(12))/4))];
    var o_0 : VsOut_0;
    o_0.svPos_0 = (((mat4x4<f32>(args_0.lightVP_0.data_0[i32(0)][i32(0)], args_0.lightVP_0.data_0[i32(1)][i32(0)], args_0.lightVP_0.data_0[i32(2)][i32(0)], args_0.lightVP_0.data_0[i32(3)][i32(0)], args_0.lightVP_0.data_0[i32(0)][i32(1)], args_0.lightVP_0.data_0[i32(1)][i32(1)], args_0.lightVP_0.data_0[i32(2)][i32(1)], args_0.lightVP_0.data_0[i32(3)][i32(1)], args_0.lightVP_0.data_0[i32(0)][i32(2)], args_0.lightVP_0.data_0[i32(1)][i32(2)], args_0.lightVP_0.data_0[i32(2)][i32(2)], args_0.lightVP_0.data_0[i32(3)][i32(2)], args_0.lightVP_0.data_0[i32(0)][i32(3)], args_0.lightVP_0.data_0[i32(1)][i32(3)], args_0.lightVP_0.data_0[i32(2)][i32(3)], args_0.lightVP_0.data_0[i32(3)][i32(3)])) * ((((mat4x4<f32>(r0_0, r1_0, r2_0, (bitcast<vec4<f32>>((vec4<u32>(_S24, _S25, _S26, _S27)))))) * (vec4<f32>(vPos_0, 1.0f)))))));
    return o_0;
}

struct pixelOutput_0
{
    @builtin(frag_depth) output_0 : f32,
};

@fragment
fn psMain(@builtin(position) svPos_1 : vec4<f32>) -> pixelOutput_0
{
    var _S28 : pixelOutput_0 = pixelOutput_0( svPos_1.z );
    return _S28;
}
