// Generated by Slang 2026.14 + Luxel.ShaderWgslGen. Do not edit.
struct DrawArgs_std430_0
{
    @align(4) vertexBufferIndex_0 : u32,
};

@group(0) @binding(1) var<uniform> g_args_0 : DrawArgs_std430_0;
@group(0) @binding(0) var<storage, read> g_buffers_0 : array<u32>;

struct VSOut_0
{
    @builtin(position) position_0 : vec4<f32>,
    @location(0) color_0 : vec4<f32>,
};

@vertex
fn vsMain(@builtin(vertex_index) vid_0 : u32) -> VSOut_0
{
    var _S1 : u32 = g_args_0.vertexBufferIndex_0;
    var _S2 : u32 = vid_0 * u32(32);
    var _S3 : u32 = g_buffers_0[(((g_args_0.vertexBufferIndex_0) * 64u) + ((_S2)/4))];
    var _S4 : f32 = bitcast<f32>(_S3);
    var _S5 : u32 = g_buffers_0[(((_S1) * 64u) + ((_S2 + u32(4))/4))];
    var _S6 : f32 = bitcast<f32>(_S5);
    var _S7 : u32 = g_buffers_0[(((_S1) * 64u) + ((_S2 + u32(8))/4))];
    var _S8 : f32 = bitcast<f32>(_S7);
    var _S9 : u32 = g_buffers_0[(((_S1) * 64u) + ((_S2 + u32(12))/4))];
    var _S10 : vec4<f32> = vec4<f32>(_S4, _S6, _S8, bitcast<f32>(_S9));
    var _S11 : u32 = g_buffers_0[(((_S1) * 64u) + ((_S2 + u32(16))/4))];
    var _S12 : f32 = bitcast<f32>(_S11);
    var _S13 : u32 = g_buffers_0[(((_S1) * 64u) + ((_S2 + u32(20))/4))];
    var _S14 : f32 = bitcast<f32>(_S13);
    var _S15 : u32 = g_buffers_0[(((_S1) * 64u) + ((_S2 + u32(24))/4))];
    var _S16 : f32 = bitcast<f32>(_S15);
    var _S17 : u32 = g_buffers_0[(((_S1) * 64u) + ((_S2 + u32(28))/4))];
    var _S18 : vec4<f32> = vec4<f32>(_S12, _S14, _S16, bitcast<f32>(_S17));
    var o_0 : VSOut_0;
    o_0.position_0 = _S10;
    o_0.color_0 = _S18;
    return o_0;
}

struct pixelOutput_0
{
    @location(0) output_0 : vec4<f32>,
};

struct pixelInput_0
{
    @location(0) color_1 : vec4<f32>,
};

@fragment
fn psMain( _S19 : pixelInput_0, @builtin(position) position_1 : vec4<f32>) -> pixelOutput_0
{
    var _S20 : pixelOutput_0 = pixelOutput_0( _S19.color_1 );
    return _S20;
}
