// Generated by Slang 2026.14 + Luxel.ShaderWgslGen. Do not edit.
struct _MatrixStorage_float4x4_ColMajorstd430_0
{
    @align(16) data_0 : array<vec4<f32>, i32(4)>,
};

struct UiQuadArgs_std430_0
{
    @align(16) mvp_0 : _MatrixStorage_float4x4_ColMajorstd430_0,
    @align(16) vertexBufIndex_0 : u32,
    @align(4) uiBufferIndex_0 : u32,
    @align(8) uiWidth_0 : u32,
    @align(4) uiHeight_0 : u32,
};

@group(0) @binding(1) var<uniform> args_0 : UiQuadArgs_std430_0;
@group(0) @binding(0) var<storage, read> g_buffers_0 : array<u32>;

struct VsOut_0
{
    @builtin(position) svPos_0 : vec4<f32>,
    @location(0) uv_0 : vec2<f32>,
};

@vertex
fn vsMain(@builtin(vertex_index) vid_0 : u32) -> VsOut_0
{
    var addr_0 : u32 = vid_0 * u32(24);
    var _S1 : u32 = args_0.vertexBufIndex_0;
    var _S2 : u32 = g_buffers_0[(((args_0.vertexBufIndex_0) * 64u) + ((addr_0)/4))];
    var _S3 : u32 = g_buffers_0[(((_S1) * 64u) + ((addr_0 + u32(4))/4))];
    var _S4 : u32 = g_buffers_0[(((_S1) * 64u) + ((addr_0 + u32(8))/4))];
    var pos_0 : vec3<f32> = (bitcast<vec3<f32>>((vec3<u32>(_S2, _S3, _S4))));
    var _S5 : u32 = args_0.vertexBufIndex_0;
    var _S6 : u32 = addr_0 + u32(12);
    var _S7 : u32 = g_buffers_0[(((args_0.vertexBufIndex_0) * 64u) + ((_S6)/4))];
    var _S8 : u32 = g_buffers_0[(((_S5) * 64u) + ((_S6 + u32(4))/4))];
    var uv_1 : vec2<f32> = (bitcast<vec2<f32>>((vec2<u32>(_S7, _S8))));
    var o_0 : VsOut_0;
    o_0.svPos_0 = (((mat4x4<f32>(args_0.mvp_0.data_0[i32(0)][i32(0)], args_0.mvp_0.data_0[i32(1)][i32(0)], args_0.mvp_0.data_0[i32(2)][i32(0)], args_0.mvp_0.data_0[i32(3)][i32(0)], args_0.mvp_0.data_0[i32(0)][i32(1)], args_0.mvp_0.data_0[i32(1)][i32(1)], args_0.mvp_0.data_0[i32(2)][i32(1)], args_0.mvp_0.data_0[i32(3)][i32(1)], args_0.mvp_0.data_0[i32(0)][i32(2)], args_0.mvp_0.data_0[i32(1)][i32(2)], args_0.mvp_0.data_0[i32(2)][i32(2)], args_0.mvp_0.data_0[i32(3)][i32(2)], args_0.mvp_0.data_0[i32(0)][i32(3)], args_0.mvp_0.data_0[i32(1)][i32(3)], args_0.mvp_0.data_0[i32(2)][i32(3)], args_0.mvp_0.data_0[i32(3)][i32(3)])) * (vec4<f32>(pos_0, 1.0f))));
    o_0.uv_0 = uv_1;
    return o_0;
}

struct pixelOutput_0
{
    @location(0) output_0 : vec4<f32>,
};

struct pixelInput_0
{
    @location(0) uv_2 : vec2<f32>,
};

@fragment
fn psMain( _S9 : pixelInput_0, @builtin(position) svPos_1 : vec4<f32>) -> pixelOutput_0
{
    var w_0 : i32 = i32(args_0.uiWidth_0);
    var h_0 : i32 = i32(args_0.uiHeight_0);
    var _S10 : u32 = g_buffers_0[(((args_0.uiBufferIndex_0) * 64u) + ((u32(i32(u32((clamp(i32(_S9.uv_2.y * f32(h_0)), i32(0), h_0 - i32(1)) * w_0 + clamp(i32(_S9.uv_2.x * f32(w_0)), i32(0), w_0 - i32(1))) * i32(4)))))/4))];
    var _S11 : pixelOutput_0 = pixelOutput_0( vec4<f32>(f32((((_S10 >> (u32(0)))) & (u32(255)))) / 255.0f, f32((((_S10 >> (u32(8)))) & (u32(255)))) / 255.0f, f32((((_S10 >> (u32(16)))) & (u32(255)))) / 255.0f, f32((((_S10 >> (u32(24)))) & (u32(255)))) / 255.0f) );
    return _S11;
}
