<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\Graphics\Luxel.Graphics\Luxel.Graphics.csproj" />
    <ProjectReference Include="..\..\Graphics\Luxel.Graphics.MessagePipe\Luxel.Graphics.MessagePipe.csproj" />
    <ProjectReference Include="..\Luxel.Ecs\Luxel.Ecs.csproj" />
    <ProjectReference Include="..\..\Graphics\Luxel.Graphics.RenderSystem\Luxel.Graphics.RenderSystem.csproj" />
    <ProjectReference Include="..\..\Graphics\Luxel.Graphics.RenderGraph\Luxel.Graphics.RenderGraph.csproj" />
    <ProjectReference Include="..\..\Resources\Luxel.Resources\Luxel.Resources.csproj" />
    <ProjectReference Include="..\..\Input\Luxel.Input\Luxel.Input.csproj" />
    <ProjectReference Include="..\..\Audio\Luxel.Audio\Luxel.Audio.csproj" />
    <ProjectReference Include="..\..\UI\Luxel.UI\Luxel.UI.csproj" />
    <ProjectReference Include="..\Luxel.Settings\Luxel.Settings.csproj" />
    <ProjectReference Include="..\..\Resources\Luxel.Assets\Luxel.Assets.csproj" />
    <ProjectReference Include="..\..\Resources\Luxel.AssetsGpu\Luxel.AssetsGpu.csproj" />
    <ProjectReference Include="..\..\Resources\Luxel.AssetRuntime\Luxel.AssetRuntime.csproj" />
    <ProjectReference Include="..\..\Platform\Luxel.Platform\Luxel.Platform.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\DevTools\Luxel.Diagnostics\Luxel.Diagnostics.csproj" />
  </ItemGroup>

  <PropertyGroup>

    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Luxel.Animation.Tests" />
    <InternalsVisibleTo Include="Luxel.Audio.Tests" />
    <InternalsVisibleTo Include="Luxel.DevTools.Tests" />
    <InternalsVisibleTo Include="Luxel.Editor.Tests" />
    <InternalsVisibleTo Include="Luxel.Framework.Tests" />
    <InternalsVisibleTo Include="Luxel.Gallery.Tests" />
    <InternalsVisibleTo Include="Luxel.GamesSamples.Tests" />
    <InternalsVisibleTo Include="Luxel.Graphics.Tests" />
    <InternalsVisibleTo Include="Luxel.Input.Tests" />
    <InternalsVisibleTo Include="Luxel.Particles.Tests" />
    <InternalsVisibleTo Include="Luxel.Platform.Tests" />
    <InternalsVisibleTo Include="Luxel.Resources.Tests" />
    <InternalsVisibleTo Include="Luxel.Scripting.Tests" />
    <InternalsVisibleTo Include="Luxel.Shared.Tests" />
    <InternalsVisibleTo Include="Luxel.UI.Tests" />
    <InternalsVisibleTo Include="Luxel.Audio.Silk.Tests" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Luxel.Graphics" />
  </ItemGroup>
</Project>
