<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Luxel.Graphics\Luxel.Graphics.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Silk.NET.WebGPU" Version="2.23.0" />
    <PackageReference Include="Silk.NET.WebGPU.Extensions.WGPU" Version="2.23.0" />
    <PackageReference Include="Silk.NET.WebGPU.Native.WGPU" Version="2.23.0" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Luxel.Graphics" />
  </ItemGroup>
</Project>
