<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Luxel.Animation\Luxel.Animation.csproj" />
    <ProjectReference Include="..\Luxel.Graphics.TwoD\Luxel.Graphics.TwoD.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Luxel.Mathematics\Luxel.Mathematics.csproj" />
    <Using Include="Luxel.Mathematics" />
  </ItemGroup>

  <PropertyGroup>

    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
