<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Luxel.Framework.Game\Luxel.Framework.Game.csproj" />
    <ProjectReference Include="..\..\Luxel.Audio.Browser\Luxel.Audio.Browser.csproj" />
    <ProjectReference Include="..\..\Luxel.Graphics.WebGPU.Browser\Luxel.Graphics.WebGPU.Browser.csproj" />
    <ProjectReference Include="..\..\Luxel.Platform.Web\Luxel.Platform.Web.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Luxel.Graphics" />
    <Using Include="Luxel.Platform" />
  </ItemGroup>
</Project>
