<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Luxel.Gallery\Luxel.Gallery.csproj" />
    <ProjectReference Include="..\Luxel.Gallery.Rendering\Luxel.Gallery.Rendering.csproj" />
    <ProjectReference Include="..\Luxel.Gallery.Stories\Luxel.Gallery.Stories.csproj" />
    <ProjectReference Include="..\Luxel.Graphics\Luxel.Graphics.csproj" />
    <ProjectReference Include="..\Luxel.Graphics.TwoD\Luxel.Graphics.TwoD.csproj" />
    <ProjectReference Include="..\Luxel.Graphics.TwoD.Skia\Luxel.Graphics.TwoD.Skia.csproj" />
    <ProjectReference Include="..\Luxel.Platform\Luxel.Platform.csproj" />
    <ProjectReference Include="..\Luxel.UI\Luxel.UI.csproj" />
    <ProjectReference Include="..\Luxel.UI.App\Luxel.UI.App.csproj" />
    <ProjectReference Include="..\Luxel.DevTools\Luxel.DevTools.csproj" />
    <ProjectReference Include="..\Luxel.Diagnostics\Luxel.Diagnostics.csproj" />
    <ProjectReference Include="..\Luxel.Typography\Luxel.Typography.csproj" />
  </ItemGroup>
  <Import Project="..\..\assets\Luxel.FontAssets.targets" />
  <Import Project="..\..\shaders\Luxel.Shaders.targets" />
  <ItemGroup>
    <Using Include="Luxel.Graphics" />
    <Using Include="Luxel.Platform" />
  </ItemGroup>
</Project>
