<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><IsPackable>false</IsPackable></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Luxel.Audio\Luxel.Audio.csproj" />
    <ProjectReference Include="..\..\src\Luxel.Audio.Linux\Luxel.Audio.Linux.csproj" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.7.0" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5"><PrivateAssets>all</PrivateAssets><IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets></PackageReference>
  </ItemGroup>
  <ItemGroup><Using Include="Luxel.Audio" /><Using Include="Luxel.Audio.Linux" /><Using Include="Xunit" /></ItemGroup>
</Project>
