<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Luxel.Graphics\Luxel.Graphics.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\DevTools\Luxel.Diagnostics\Luxel.Diagnostics.csproj" />
  </ItemGroup>

  <PropertyGroup>

    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Luxel.Tests" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Luxel.Graphics" />
  </ItemGroup>
</Project>
