<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Luxel.Graphics\Luxel.Graphics.csproj" />
    <ProjectReference Include="..\Luxel.Resources\Luxel.Resources.csproj" />
  </ItemGroup>
</Project>
