<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\Platform\Luxel.Platform\Luxel.Platform.csproj" />
    <ProjectReference Include="..\..\UI\Luxel.UI\Luxel.UI.csproj" />
    <ProjectReference Include="..\..\Resources\Luxel.Resources\Luxel.Resources.csproj" />
  </ItemGroup>

  <PropertyGroup>

    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Luxel.Tests" />
  </ItemGroup>

</Project>
