<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\Graphics\Luxel.Graphics\Luxel.Graphics.csproj" />
    <ProjectReference Include="..\..\Framework\Luxel.Ecs\Luxel.Ecs.csproj" />
    <ProjectReference Include="..\..\Graphics\Luxel.Graphics.RenderGraph\Luxel.Graphics.RenderGraph.csproj" />
    <ProjectReference Include="..\..\Animation\Luxel.Animation\Luxel.Animation.csproj" />
    <ProjectReference Include="..\Luxel.Resources\Luxel.Resources.csproj" />
  </ItemGroup>

  <PropertyGroup>

    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Luxel.Tests" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Luxel.Graphics" />
  </ItemGroup>
</Project>
