<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>

    <AssemblyName>LuxelTriangle</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Nullable>enable</Nullable>
    <PlatformTarget Condition="$([System.Runtime.InteropServices.RuntimeInformation]::ProcessArchitecture) == 'X64'">x64</PlatformTarget>
    <PlatformTarget Condition="$([System.Runtime.InteropServices.RuntimeInformation]::ProcessArchitecture) == 'Arm64'">arm64</PlatformTarget>
  </PropertyGroup>

  <PropertyGroup Condition="$([MSBuild]::IsOSPlatform('Windows'))">
    <DefineConstants>$(DefineConstants);LUXEL_WINDOWS</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Luxel.Graphics\Luxel.Graphics.csproj" />
    <ProjectReference Include="..\..\src\Luxel.Graphics.RenderGraph\Luxel.Graphics.RenderGraph.csproj" />
    <ProjectReference Include="..\..\src\Luxel.Graphics.WebGPU\Luxel.Graphics.WebGPU.csproj" />
    <ProjectReference Include="..\..\src\Luxel.Graphics.Vulkan\Luxel.Graphics.Vulkan.csproj" />
  </ItemGroup>

  <ItemGroup Condition="$([MSBuild]::IsOSPlatform('Windows'))">
    <ProjectReference Include="..\..\src\Luxel.Platform.Windows\Luxel.Platform.Windows.csproj" />
    <ProjectReference Include="..\..\src\Luxel.Platform\Luxel.Platform.csproj" />
    <ProjectReference Include="..\..\src\Luxel.Graphics.DirectX12\Luxel.Graphics.DirectX12.csproj" />
  </ItemGroup>

  <ItemGroup Condition="$([MSBuild]::IsOSPlatform('Linux'))">
    <ProjectReference Include="..\..\src\Luxel.Platform.Silk\Luxel.Platform.Silk.csproj" />
  </ItemGroup>

  <Import Project="..\..\shaders\Luxel.Shaders.targets" />
  <ItemGroup>
    <Compile Include="..\CanonicalTriangleRecipe.cs" Link="CanonicalTriangleRecipe.cs" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Luxel.Graphics" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Luxel.Platform" />
  </ItemGroup>
  <ItemGroup Condition="$([MSBuild]::IsOSPlatform('Windows'))">
    <Using Include="Luxel.Platform.Windows" />
  </ItemGroup>
</Project>
