<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Luxel.Graphics\Luxel.Graphics.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="wwwroot\luxel-webgpu-browser.js" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Using Include="Luxel.Graphics" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Luxel.WebGPU.Browser.Tests" />
  </ItemGroup>
</Project>
