<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Resource\Luxel.Assets\Luxel.Assets.csproj" />
    <ProjectReference Include="..\Resource\Luxel.AssetRuntime\Luxel.AssetRuntime.csproj" />
    <ProjectReference Include="..\Luxel.Ecs\Luxel.Ecs.csproj" />
    <ProjectReference Include="..\Luxel.Ecs.Signal\Luxel.Ecs.Signal.csproj" />
    <ProjectReference Include="..\Luxel.UI\Luxel.UI.csproj" />
  </ItemGroup>

  <PropertyGroup>

    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Luxel.Tests" />
  </ItemGroup>

</Project>
