<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\UI\Luxel.UI\Luxel.UI.csproj" />
    <ProjectReference Include="..\..\Resources\Luxel.Resources\Luxel.Resources.csproj" />
  </ItemGroup>

  <PropertyGroup>

    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Luxel.Animation.Tests" />
    <InternalsVisibleTo Include="Luxel.Audio.Tests" />
    <InternalsVisibleTo Include="Luxel.DevTools.Tests" />
    <InternalsVisibleTo Include="Luxel.Editor.Tests" />
    <InternalsVisibleTo Include="Luxel.Framework.Tests" />
    <InternalsVisibleTo Include="Luxel.Gallery.Tests" />
    <InternalsVisibleTo Include="Luxel.GamesSamples.Tests" />
    <InternalsVisibleTo Include="Luxel.Graphics.Tests" />
    <InternalsVisibleTo Include="Luxel.Input.Tests" />
    <InternalsVisibleTo Include="Luxel.Particles.Tests" />
    <InternalsVisibleTo Include="Luxel.Platform.Tests" />
    <InternalsVisibleTo Include="Luxel.Resources.Tests" />
    <InternalsVisibleTo Include="Luxel.Scripting.Tests" />
    <InternalsVisibleTo Include="Luxel.Shared.Tests" />
    <InternalsVisibleTo Include="Luxel.UI.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NAudio.Core" Version="2.3.0" />
    <PackageReference Include="NAudio.Vorbis" Version="1.5.0" />
  </ItemGroup>

</Project>
