<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Luxel.Ecs\Luxel.Ecs.csproj" />
    <ProjectReference Include="..\..\UI\Luxel.UI\Luxel.UI.csproj" />
  </ItemGroup>

  <PropertyGroup>

    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Luxel.Tests" />
  </ItemGroup>

</Project>
